SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t0`;
CREATE TABLE `t0` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(1) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint DEFAULT NULL,
  `decimal_col` decimal(24,6) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(6) DEFAULT NULL,
  `timestamp_col` timestamp(6) NULL DEFAULT NULL,
  `time_col` time(2) DEFAULT NULL,
  `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(7) DEFAULT NULL,
  `varbinary_col` varbinary(155) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(5) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(20,5) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t0_000` json DEFAULT NULL,
  `extra_t0_001` mediumint unsigned DEFAULT NULL,
  `extra_t0_002` smallint DEFAULT NULL,
  `extra_t0_003` time DEFAULT NULL,
  `extra_t0_004` bit(18) DEFAULT NULL,
  `extra_t0_005` decimal(19,7) DEFAULT NULL,
  `extra_t0_006` int DEFAULT NULL,
  `extra_t0_007` set('s7_1','s7_2','s7_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_008` enum('e8_1','e8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_009` decimal(20,3) DEFAULT NULL,
  `extra_t0_010` smallint DEFAULT NULL,
  `extra_t0_011` bit(44) DEFAULT NULL,
  `extra_t0_012` varbinary(29) DEFAULT NULL,
  `extra_t0_013` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_014` decimal(10,2) DEFAULT NULL,
  `extra_t0_015` longblob,
  `extra_t0_016` decimal(7,5) DEFAULT NULL,
  `extra_t0_017` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_018` tinyblob,
  `extra_t0_019` bit(23) DEFAULT NULL,
  `extra_t0_020` time(1) DEFAULT NULL,
  `extra_t0_021` varbinary(9) DEFAULT NULL,
  `extra_t0_022` smallint DEFAULT NULL,
  `extra_t0_023` decimal(16,2) DEFAULT NULL,
  `extra_t0_024` float DEFAULT NULL,
  `extra_t0_025` timestamp(3) DEFAULT NULL,
  `extra_t0_026` bit(54) DEFAULT NULL,
  `extra_t0_027` tinyblob,
  `extra_t0_028` bit(22) DEFAULT NULL,
  `extra_t0_029` tinyint DEFAULT NULL,
  `extra_t0_030` tinyint unsigned DEFAULT NULL,
  `extra_t0_031` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_032` bit(19) DEFAULT NULL,
  `extra_t0_033` json DEFAULT NULL,
  `extra_t0_034` longblob,
  `extra_t0_035` set('s5_1','s5_2','s5_3','s5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_036` decimal(19,5) DEFAULT NULL,
  `extra_t0_037` decimal(8,0) DEFAULT NULL,
  `extra_t0_038` json DEFAULT NULL,
  `extra_t0_039` json DEFAULT NULL,
  `extra_t0_040` datetime DEFAULT NULL,
  `extra_t0_041` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_042` double DEFAULT NULL,
  `extra_t0_043` json DEFAULT NULL,
  `extra_t0_044` tinyblob,
  `extra_t0_045` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_046` tinyblob,
  `extra_t0_047` longblob,
  `extra_t0_048` bit(55) DEFAULT NULL,
  `extra_t0_049` binary(20) DEFAULT NULL,
  `extra_t0_050` int unsigned DEFAULT NULL,
  `extra_t0_051` binary(26) DEFAULT NULL,
  `extra_t0_052` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_053` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_054` mediumblob,
  `extra_t0_055` varbinary(16) DEFAULT NULL,
  `extra_t0_056` date DEFAULT NULL,
  `extra_t0_057` json DEFAULT NULL,
  `extra_t0_058` decimal(7,3) DEFAULT NULL,
  `extra_t0_059` blob,
  `extra_t0_060` timestamp(2) DEFAULT NULL,
  `extra_t0_061` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_062` set('s2_1','s2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_063` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_064` double unsigned DEFAULT NULL,
  `extra_t0_065` bit(13) DEFAULT NULL,
  `extra_t0_066` date DEFAULT NULL,
  `extra_t0_067` bit(14) DEFAULT NULL,
  `extra_t0_068` mediumblob,
  `extra_t0_069` json DEFAULT NULL,
  `extra_t0_070` year DEFAULT NULL,
  `extra_t0_071` bit(14) DEFAULT NULL,
  `extra_t0_072` blob,
  `extra_t0_073` bit(56) DEFAULT NULL,
  `extra_t0_074` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_075` decimal(16,4) DEFAULT NULL,
  `extra_t0_076` binary(12) DEFAULT NULL,
  `extra_t0_077` decimal(14,2) DEFAULT NULL,
  `extra_t0_078` year DEFAULT NULL,
  `extra_t0_079` json DEFAULT NULL,
  `extra_t0_080` blob,
  `extra_t0_081` double unsigned DEFAULT NULL,
  `extra_t0_082` enum('e2_1','e2_2','e2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_083` mediumblob,
  `extra_t0_084` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_085` bit(26) DEFAULT NULL,
  `extra_t0_086` double unsigned DEFAULT NULL,
  `extra_t0_087` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_088` bigint DEFAULT NULL,
  `extra_t0_089` mediumint DEFAULT NULL,
  `extra_t0_090` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_091` json DEFAULT NULL,
  `extra_t0_092` timestamp(1) DEFAULT NULL,
  `extra_t0_093` decimal(11,6) DEFAULT NULL,
  `extra_t0_094` json DEFAULT NULL,
  `extra_t0_095` longblob,
  `extra_t0_096` decimal(12,3) DEFAULT NULL,
  `extra_t0_097` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_098` decimal(17,0) DEFAULT NULL,
  `extra_t0_099` bigint unsigned DEFAULT NULL,
  `extra_t0_100` decimal(11,1) DEFAULT NULL,
  `extra_t0_101` bit(59) DEFAULT NULL,
  `extra_t0_102` decimal(17,3) DEFAULT NULL,
  `extra_t0_103` time(6) DEFAULT NULL,
  `extra_t0_104` json DEFAULT NULL,
  `extra_t0_105` json DEFAULT NULL,
  `extra_t0_106` decimal(15,7) DEFAULT NULL,
  `extra_t0_107` decimal(8,7) DEFAULT NULL,
  `extra_t0_108` decimal(18,3) DEFAULT NULL,
  `extra_t0_109` bit(9) DEFAULT NULL,
  `extra_t0_110` timestamp(1) DEFAULT NULL,
  `extra_t0_111` bigint unsigned DEFAULT NULL,
  `extra_t0_112` date DEFAULT NULL,
  `extra_t0_113` varbinary(26) DEFAULT NULL,
  `extra_t0_114` tinyint DEFAULT NULL,
  `extra_t0_115` bit(55) DEFAULT NULL,
  `extra_t0_116` decimal(10,4) DEFAULT NULL,
  `extra_t0_117` json DEFAULT NULL,
  `extra_t0_118` binary(8) DEFAULT NULL,
  `extra_t0_119` decimal(7,2) DEFAULT NULL,
  `extra_t0_120` longblob,
  `extra_t0_121` char(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_122` float DEFAULT NULL,
  `extra_t0_123` bit(15) DEFAULT NULL,
  `extra_t0_124` json DEFAULT NULL,
  `extra_t0_125` decimal(14,8) DEFAULT NULL,
  `extra_t0_126` mediumblob,
  `extra_t0_127` json DEFAULT NULL,
  `extra_t0_128` timestamp(4) DEFAULT NULL,
  `extra_t0_129` date DEFAULT NULL,
  `extra_t0_130` time DEFAULT NULL,
  `extra_t0_131` json DEFAULT NULL,
  `extra_t0_132` blob,
  `extra_t0_133` set('s3_1','s3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_134` bit(41) DEFAULT NULL,
  `extra_t0_135` decimal(14,3) DEFAULT NULL,
  `extra_t0_136` bigint DEFAULT NULL,
  `extra_t0_137` float unsigned DEFAULT NULL,
  `extra_t0_138` int DEFAULT NULL,
  `extra_t0_139` float unsigned DEFAULT NULL,
  `extra_t0_140` json DEFAULT NULL,
  `extra_t0_141` decimal(16,3) DEFAULT NULL,
  `extra_t0_142` time(5) DEFAULT NULL,
  `extra_t0_143` bit(43) DEFAULT NULL,
  `extra_t0_144` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_145` decimal(19,7) DEFAULT NULL,
  `extra_t0_146` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t0_147` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_148` json DEFAULT NULL,
  `extra_t0_149` mediumint unsigned DEFAULT NULL,
  `extra_t0_150` json DEFAULT NULL,
  `extra_t0_151` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t0_152` bit(50) DEFAULT NULL,
  `extra_t0_153` decimal(13,5) DEFAULT NULL,
  `extra_t0_154` decimal(12,0) DEFAULT NULL,
  `extra_t0_155` date DEFAULT NULL,
  `extra_t0_156` year DEFAULT NULL,
  `extra_t0_157` bigint DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t0_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t0_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t0_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t0_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t0_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t0_int_col` (`int_col`),
  UNIQUE KEY `idx_t0_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t0_year_char` (`year_col`,`char_col`),
  UNIQUE KEY `idx_t0_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  UNIQUE KEY `idx_t0_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  UNIQUE KEY `idx_t0_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t0_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t0_binary_combo` (`binary_col`,`varbinary_col`),
  UNIQUE KEY `idx_t0_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  UNIQUE KEY `idx_t0_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t0_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  UNIQUE KEY `idx_t0_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t0_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t0_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t0_year_func` ((year(`datetime_col`))),
  UNIQUE KEY `idx_t0_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  UNIQUE KEY `idx_t0_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t0_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  UNIQUE KEY `idx_t0_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  UNIQUE KEY `idx_t0_extra_float_floor` ((floor(`float_col`))),
  UNIQUE KEY `idx_t0_extra_date_days` ((to_days(`date_col`))),
  UNIQUE KEY `idx_t0_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  UNIQUE KEY `idx_t0_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t0_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t0_extra_month_datetime` ((month(`datetime_col`))),
  UNIQUE KEY `idx_t0_extra_decimal_desc` (`decimal_col` DESC),
  UNIQUE KEY `idx_t0_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  UNIQUE KEY `idx_t0_extra_subpart_big` (`subpart_id`,`bigint_col`),
  UNIQUE KEY `idx_t0_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  UNIQUE KEY `idx_t0_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t0_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t0_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t0_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  UNIQUE KEY `idx_t0_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  UNIQUE KEY `idx_t0_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  UNIQUE KEY `idx_t0_extra_time_to_sec` ((time_to_sec(`time_col`))),
  UNIQUE KEY `idx_t0_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  UNIQUE KEY `idx_t0_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t0_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  UNIQUE KEY `idx_t0_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  UNIQUE KEY `idx_t0_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t0_extra_dayofweek` ((dayofweek(`date_col`))),
  UNIQUE KEY `idx_t0_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t0_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t0_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  UNIQUE KEY `idx_t0_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  UNIQUE KEY `idx_t0_extra_double_ceiling` ((ceiling(`double_col`))),
  UNIQUE KEY `idx_t0_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t0_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t0_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t0_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t0_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `idx_t0_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t0_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t0_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t0_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
