SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t15`;
CREATE TABLE `t15` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(123) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(27,7) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(1) DEFAULT NULL,
  `timestamp_col` timestamp NULL DEFAULT NULL,
  `time_col` time(6) DEFAULT NULL,
  `varchar_col` varchar(47) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(239) DEFAULT NULL,
  `varbinary_col` varbinary(32) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(39) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(15,5) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t15_000` datetime(5) DEFAULT NULL,
  `extra_t15_001` varbinary(24) DEFAULT NULL,
  `extra_t15_002` int unsigned DEFAULT NULL,
  `extra_t15_003` json DEFAULT NULL,
  `extra_t15_004` int unsigned DEFAULT NULL,
  `extra_t15_005` datetime(5) DEFAULT NULL,
  `extra_t15_006` decimal(18,2) DEFAULT NULL,
  `extra_t15_007` float DEFAULT NULL,
  `extra_t15_008` double DEFAULT NULL,
  `extra_t15_009` bit(1) DEFAULT NULL,
  `extra_t15_010` bit(51) DEFAULT NULL,
  `extra_t15_011` bit(10) DEFAULT NULL,
  `extra_t15_012` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_013` int DEFAULT NULL,
  `extra_t15_014` mediumint unsigned DEFAULT NULL,
  `extra_t15_015` date DEFAULT NULL,
  `extra_t15_016` date DEFAULT NULL,
  `extra_t15_017` double DEFAULT NULL,
  `extra_t15_018` bit(52) DEFAULT NULL,
  `extra_t15_019` bit(11) DEFAULT NULL,
  `extra_t15_020` tinyint unsigned DEFAULT NULL,
  `extra_t15_021` datetime(1) DEFAULT NULL,
  `extra_t15_022` double unsigned DEFAULT NULL,
  `extra_t15_023` json DEFAULT NULL,
  `extra_t15_024` int DEFAULT NULL,
  `extra_t15_025` tinyint unsigned DEFAULT NULL,
  `extra_t15_026` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_027` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_028` json DEFAULT NULL,
  `extra_t15_029` decimal(23,5) DEFAULT NULL,
  `extra_t15_030` bit(3) DEFAULT NULL,
  `extra_t15_031` bit(61) DEFAULT NULL,
  `extra_t15_032` double DEFAULT NULL,
  `extra_t15_033` binary(29) DEFAULT NULL,
  `extra_t15_034` mediumint DEFAULT NULL,
  `extra_t15_035` varbinary(30) DEFAULT NULL,
  `extra_t15_036` timestamp(3) DEFAULT NULL,
  `extra_t15_037` json DEFAULT NULL,
  `extra_t15_038` json DEFAULT NULL,
  `extra_t15_039` decimal(12,5) DEFAULT NULL,
  `extra_t15_040` float unsigned DEFAULT NULL,
  `extra_t15_041` int unsigned DEFAULT NULL,
  `extra_t15_042` decimal(23,7) DEFAULT NULL,
  `extra_t15_043` binary(12) DEFAULT NULL,
  `extra_t15_044` bit(21) DEFAULT NULL,
  `extra_t15_045` mediumint DEFAULT NULL,
  `extra_t15_046` mediumblob,
  `extra_t15_047` decimal(16,4) DEFAULT NULL,
  `extra_t15_048` bit(60) DEFAULT NULL,
  `extra_t15_049` decimal(12,0) DEFAULT NULL,
  `extra_t15_050` timestamp(3) DEFAULT NULL,
  `extra_t15_051` int DEFAULT NULL,
  `extra_t15_052` float DEFAULT NULL,
  `extra_t15_053` mediumint unsigned DEFAULT NULL,
  `extra_t15_054` enum('e4_1','e4_2','e4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_055` time DEFAULT NULL,
  `extra_t15_056` decimal(11,6) DEFAULT NULL,
  `extra_t15_057` set('s7_1','s7_2','s7_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_058` double DEFAULT NULL,
  `extra_t15_059` double unsigned DEFAULT NULL,
  `extra_t15_060` set('s0_1','s0_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_061` bit(47) DEFAULT NULL,
  `extra_t15_062` json DEFAULT NULL,
  `extra_t15_063` bit(61) DEFAULT NULL,
  `extra_t15_064` bit(14) DEFAULT NULL,
  `extra_t15_065` json DEFAULT NULL,
  `extra_t15_066` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_067` bit(15) DEFAULT NULL,
  `extra_t15_068` blob,
  `extra_t15_069` longblob,
  `extra_t15_070` set('s0_1','s0_2','s0_3','s0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_071` double DEFAULT NULL,
  `extra_t15_072` json DEFAULT NULL,
  `extra_t15_073` int DEFAULT NULL,
  `extra_t15_074` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_075` decimal(25,7) DEFAULT NULL,
  `extra_t15_076` json DEFAULT NULL,
  `extra_t15_077` json DEFAULT NULL,
  `extra_t15_078` json DEFAULT NULL,
  `extra_t15_079` json DEFAULT NULL,
  `extra_t15_080` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_081` varbinary(8) DEFAULT NULL,
  `extra_t15_082` int unsigned DEFAULT NULL,
  `extra_t15_083` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_084` blob,
  `extra_t15_085` tinyint unsigned DEFAULT NULL,
  `extra_t15_086` bit(39) DEFAULT NULL,
  `extra_t15_087` json DEFAULT NULL,
  `extra_t15_088` json DEFAULT NULL,
  `extra_t15_089` smallint unsigned DEFAULT NULL,
  `extra_t15_090` float unsigned DEFAULT NULL,
  `extra_t15_091` blob,
  `extra_t15_092` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_093` bit(63) DEFAULT NULL,
  `extra_t15_094` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_095` mediumint unsigned DEFAULT NULL,
  `extra_t15_096` bit(31) DEFAULT NULL,
  `extra_t15_097` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_098` decimal(6,3) DEFAULT NULL,
  `extra_t15_099` bigint DEFAULT NULL,
  `extra_t15_100` set('s0_1','s0_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_101` tinyblob,
  `extra_t15_102` json DEFAULT NULL,
  `extra_t15_103` set('s3_1','s3_2','s3_3','s3_4','s3_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_104` bit(15) DEFAULT NULL,
  `extra_t15_105` set('s5_1','s5_2','s5_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_106` json DEFAULT NULL,
  `extra_t15_107` set('s7_1','s7_2','s7_3','s7_4','s7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_108` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_109` longblob,
  `extra_t15_110` bit(37) DEFAULT NULL,
  `extra_t15_111` year DEFAULT NULL,
  `extra_t15_112` longblob,
  `extra_t15_113` bit(40) DEFAULT NULL,
  `extra_t15_114` double unsigned DEFAULT NULL,
  `extra_t15_115` double unsigned DEFAULT NULL,
  `extra_t15_116` tinyint DEFAULT NULL,
  `extra_t15_117` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_118` json DEFAULT NULL,
  `extra_t15_119` time(2) DEFAULT NULL,
  `extra_t15_120` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_121` float unsigned DEFAULT NULL,
  `extra_t15_122` bit(59) DEFAULT NULL,
  `extra_t15_123` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_124` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_125` float DEFAULT NULL,
  `extra_t15_126` tinyint unsigned DEFAULT NULL,
  `extra_t15_127` json DEFAULT NULL,
  `extra_t15_128` decimal(14,4) DEFAULT NULL,
  `extra_t15_129` float DEFAULT NULL,
  `extra_t15_130` set('s0_1','s0_2','s0_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_131` json DEFAULT NULL,
  `extra_t15_132` decimal(18,1) DEFAULT NULL,
  `extra_t15_133` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_134` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_135` enum('e5_1','e5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_136` timestamp(6) DEFAULT NULL,
  `extra_t15_137` date DEFAULT NULL,
  `extra_t15_138` blob,
  `extra_t15_139` date DEFAULT NULL,
  `extra_t15_140` decimal(12,4) DEFAULT NULL,
  `extra_t15_141` float DEFAULT NULL,
  `extra_t15_142` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_143` year DEFAULT NULL,
  `extra_t15_144` char(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_145` mediumblob,
  `extra_t15_146` set('s6_1','s6_2','s6_3','s6_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_147` bigint unsigned DEFAULT NULL,
  `extra_t15_148` mediumblob,
  `extra_t15_149` blob,
  `extra_t15_150` double DEFAULT NULL,
  `extra_t15_151` double unsigned DEFAULT NULL,
  `extra_t15_152` bigint DEFAULT NULL,
  `extra_t15_153` json DEFAULT NULL,
  `extra_t15_154` json DEFAULT NULL,
  `extra_t15_155` json DEFAULT NULL,
  `extra_t15_156` decimal(7,6) DEFAULT NULL,
  `extra_t15_157` int DEFAULT NULL,
  `extra_t15_158` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_159` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_160` timestamp(4) DEFAULT NULL,
  `extra_t15_161` timestamp(1) DEFAULT NULL,
  `extra_t15_162` int unsigned DEFAULT NULL,
  `extra_t15_163` int DEFAULT NULL,
  `extra_t15_164` tinyblob,
  `extra_t15_165` enum('e5_1','e5_2','e5_3','e5_4','e5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_166` bigint unsigned DEFAULT NULL,
  `extra_t15_167` json DEFAULT NULL,
  `extra_t15_168` float DEFAULT NULL,
  `extra_t15_169` year DEFAULT NULL,
  `extra_t15_170` smallint unsigned DEFAULT NULL,
  `extra_t15_171` json DEFAULT NULL,
  `extra_t15_172` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t15_173` longblob,
  `extra_t15_174` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_175` year DEFAULT NULL,
  `extra_t15_176` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t15_177` json DEFAULT NULL,
  `extra_t15_178` timestamp(5) DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t15_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t15_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t15_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t15_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t15_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t15_int_col` (`int_col`),
  KEY `idx_t15_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t15_year_char` (`year_col`,`char_col`),
  KEY `idx_t15_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t15_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t15_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t15_varchar_prefix` (`varchar_col`(47)),
  KEY `idx_t15_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t15_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t15_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t15_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t15_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t15_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t15_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t15_year_func` ((year(`datetime_col`))),
  KEY `idx_t15_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t15_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t15_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t15_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t15_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t15_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t15_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t15_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t15_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t15_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t15_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t15_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t15_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t15_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t15_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t15_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t15_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t15_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t15_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t15_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t15_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t15_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t15_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t15_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t15_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t15_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t15_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t15_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t15_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t15_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t15_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t15_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t15_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t15_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t15_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t15_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t15_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t15_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t15_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t15_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t15_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE (`tenant_id`)
SUBPARTITION BY RANGE (`subpart_id`) (
  PARTITION p0 VALUES LESS THAN (2) (
    SUBPARTITION p0sp0 VALUES LESS THAN (2),
    SUBPARTITION p0sp1 VALUES LESS THAN (3),
    SUBPARTITION p0sp2 VALUES LESS THAN (4),
    SUBPARTITION p0sp3 VALUES LESS THAN (5),
    SUBPARTITION p0sp4 VALUES LESS THAN (6),
    SUBPARTITION p0sp5 VALUES LESS THAN (7),
    SUBPARTITION p0sp6 VALUES LESS THAN (8),
    SUBPARTITION p0sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p1 VALUES LESS THAN (3) (
    SUBPARTITION p1sp0 VALUES LESS THAN (2),
    SUBPARTITION p1sp1 VALUES LESS THAN (3),
    SUBPARTITION p1sp2 VALUES LESS THAN (4),
    SUBPARTITION p1sp3 VALUES LESS THAN (5),
    SUBPARTITION p1sp4 VALUES LESS THAN (6),
    SUBPARTITION p1sp5 VALUES LESS THAN (7),
    SUBPARTITION p1sp6 VALUES LESS THAN (8),
    SUBPARTITION p1sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p2 VALUES LESS THAN (4) (
    SUBPARTITION p2sp0 VALUES LESS THAN (2),
    SUBPARTITION p2sp1 VALUES LESS THAN (3),
    SUBPARTITION p2sp2 VALUES LESS THAN (4),
    SUBPARTITION p2sp3 VALUES LESS THAN (5),
    SUBPARTITION p2sp4 VALUES LESS THAN (6),
    SUBPARTITION p2sp5 VALUES LESS THAN (7),
    SUBPARTITION p2sp6 VALUES LESS THAN (8),
    SUBPARTITION p2sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p3 VALUES LESS THAN (5) (
    SUBPARTITION p3sp0 VALUES LESS THAN (2),
    SUBPARTITION p3sp1 VALUES LESS THAN (3),
    SUBPARTITION p3sp2 VALUES LESS THAN (4),
    SUBPARTITION p3sp3 VALUES LESS THAN (5),
    SUBPARTITION p3sp4 VALUES LESS THAN (6),
    SUBPARTITION p3sp5 VALUES LESS THAN (7),
    SUBPARTITION p3sp6 VALUES LESS THAN (8),
    SUBPARTITION p3sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p4 VALUES LESS THAN (6) (
    SUBPARTITION p4sp0 VALUES LESS THAN (2),
    SUBPARTITION p4sp1 VALUES LESS THAN (3),
    SUBPARTITION p4sp2 VALUES LESS THAN (4),
    SUBPARTITION p4sp3 VALUES LESS THAN (5),
    SUBPARTITION p4sp4 VALUES LESS THAN (6),
    SUBPARTITION p4sp5 VALUES LESS THAN (7),
    SUBPARTITION p4sp6 VALUES LESS THAN (8),
    SUBPARTITION p4sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p5 VALUES LESS THAN (7) (
    SUBPARTITION p5sp0 VALUES LESS THAN (2),
    SUBPARTITION p5sp1 VALUES LESS THAN (3),
    SUBPARTITION p5sp2 VALUES LESS THAN (4),
    SUBPARTITION p5sp3 VALUES LESS THAN (5),
    SUBPARTITION p5sp4 VALUES LESS THAN (6),
    SUBPARTITION p5sp5 VALUES LESS THAN (7),
    SUBPARTITION p5sp6 VALUES LESS THAN (8),
    SUBPARTITION p5sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p6 VALUES LESS THAN (8) (
    SUBPARTITION p6sp0 VALUES LESS THAN (2),
    SUBPARTITION p6sp1 VALUES LESS THAN (3),
    SUBPARTITION p6sp2 VALUES LESS THAN (4),
    SUBPARTITION p6sp3 VALUES LESS THAN (5),
    SUBPARTITION p6sp4 VALUES LESS THAN (6),
    SUBPARTITION p6sp5 VALUES LESS THAN (7),
    SUBPARTITION p6sp6 VALUES LESS THAN (8),
    SUBPARTITION p6sp7 VALUES LESS THAN (MAXVALUE)
  ),
  PARTITION p7 VALUES LESS THAN (MAXVALUE) (
    SUBPARTITION p7sp0 VALUES LESS THAN (2),
    SUBPARTITION p7sp1 VALUES LESS THAN (3),
    SUBPARTITION p7sp2 VALUES LESS THAN (4),
    SUBPARTITION p7sp3 VALUES LESS THAN (5),
    SUBPARTITION p7sp4 VALUES LESS THAN (6),
    SUBPARTITION p7sp5 VALUES LESS THAN (7),
    SUBPARTITION p7sp6 VALUES LESS THAN (8),
    SUBPARTITION p7sp7 VALUES LESS THAN (MAXVALUE)
  )
);
SET FOREIGN_KEY_CHECKS=1;
