SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t18`;
CREATE TABLE `t18` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(4) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(25,5) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(6) DEFAULT NULL,
  `timestamp_col` timestamp NULL DEFAULT NULL,
  `time_col` time DEFAULT NULL,
  `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(1) DEFAULT NULL,
  `varbinary_col` varbinary(255) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(8) DEFAULT b'10011001',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(10,0) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t18_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t18_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  UNIQUE KEY `uk_t18_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t18_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t18_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t18_int_col` (`int_col`),
  KEY `idx_t18_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t18_year_char` (`year_col`,`char_col`),
  KEY `idx_t18_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t18_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t18_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t18_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t18_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t18_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t18_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t18_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t18_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t18_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t18_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t18_year_func` ((year(`datetime_col`))),
  KEY `idx_t18_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t18_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t18_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t18_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t18_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t18_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t18_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t18_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t18_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t18_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t18_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t18_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t18_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t18_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t18_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t18_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t18_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t18_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t18_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t18_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t18_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t18_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t18_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t18_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t18_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t18_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t18_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t18_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t18_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t18_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t18_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t18_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t18_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t18_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t18_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t18_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t18_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t18_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t18_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t18_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t18_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE (`tenant_id`)
SUBPARTITION BY LIST COLUMNS (`subpart_id`) (
  PARTITION p0 VALUES LESS THAN (2) (
    SUBPARTITION p0sp0 VALUES IN (1),
    SUBPARTITION p0sp1 VALUES IN (2),
    SUBPARTITION p0sp2 VALUES IN (3),
    SUBPARTITION p0sp3 VALUES IN (4),
    SUBPARTITION p0sp4 VALUES IN (5),
    SUBPARTITION p0sp5 VALUES IN (6),
    SUBPARTITION p0sp6 VALUES IN (7),
    SUBPARTITION p0sp7 VALUES IN (8)
  ),
  PARTITION p1 VALUES LESS THAN (3) (
    SUBPARTITION p1sp0 VALUES IN (1),
    SUBPARTITION p1sp1 VALUES IN (2),
    SUBPARTITION p1sp2 VALUES IN (3),
    SUBPARTITION p1sp3 VALUES IN (4),
    SUBPARTITION p1sp4 VALUES IN (5),
    SUBPARTITION p1sp5 VALUES IN (6),
    SUBPARTITION p1sp6 VALUES IN (7),
    SUBPARTITION p1sp7 VALUES IN (8)
  ),
  PARTITION p2 VALUES LESS THAN (4) (
    SUBPARTITION p2sp0 VALUES IN (1),
    SUBPARTITION p2sp1 VALUES IN (2),
    SUBPARTITION p2sp2 VALUES IN (3),
    SUBPARTITION p2sp3 VALUES IN (4),
    SUBPARTITION p2sp4 VALUES IN (5),
    SUBPARTITION p2sp5 VALUES IN (6),
    SUBPARTITION p2sp6 VALUES IN (7),
    SUBPARTITION p2sp7 VALUES IN (8)
  ),
  PARTITION p3 VALUES LESS THAN (5) (
    SUBPARTITION p3sp0 VALUES IN (1),
    SUBPARTITION p3sp1 VALUES IN (2),
    SUBPARTITION p3sp2 VALUES IN (3),
    SUBPARTITION p3sp3 VALUES IN (4),
    SUBPARTITION p3sp4 VALUES IN (5),
    SUBPARTITION p3sp5 VALUES IN (6),
    SUBPARTITION p3sp6 VALUES IN (7),
    SUBPARTITION p3sp7 VALUES IN (8)
  ),
  PARTITION p4 VALUES LESS THAN (6) (
    SUBPARTITION p4sp0 VALUES IN (1),
    SUBPARTITION p4sp1 VALUES IN (2),
    SUBPARTITION p4sp2 VALUES IN (3),
    SUBPARTITION p4sp3 VALUES IN (4),
    SUBPARTITION p4sp4 VALUES IN (5),
    SUBPARTITION p4sp5 VALUES IN (6),
    SUBPARTITION p4sp6 VALUES IN (7),
    SUBPARTITION p4sp7 VALUES IN (8)
  ),
  PARTITION p5 VALUES LESS THAN (7) (
    SUBPARTITION p5sp0 VALUES IN (1),
    SUBPARTITION p5sp1 VALUES IN (2),
    SUBPARTITION p5sp2 VALUES IN (3),
    SUBPARTITION p5sp3 VALUES IN (4),
    SUBPARTITION p5sp4 VALUES IN (5),
    SUBPARTITION p5sp5 VALUES IN (6),
    SUBPARTITION p5sp6 VALUES IN (7),
    SUBPARTITION p5sp7 VALUES IN (8)
  ),
  PARTITION p6 VALUES LESS THAN (8) (
    SUBPARTITION p6sp0 VALUES IN (1),
    SUBPARTITION p6sp1 VALUES IN (2),
    SUBPARTITION p6sp2 VALUES IN (3),
    SUBPARTITION p6sp3 VALUES IN (4),
    SUBPARTITION p6sp4 VALUES IN (5),
    SUBPARTITION p6sp5 VALUES IN (6),
    SUBPARTITION p6sp6 VALUES IN (7),
    SUBPARTITION p6sp7 VALUES IN (8)
  ),
  PARTITION p7 VALUES LESS THAN (MAXVALUE) (
    SUBPARTITION p7sp0 VALUES IN (1),
    SUBPARTITION p7sp1 VALUES IN (2),
    SUBPARTITION p7sp2 VALUES IN (3),
    SUBPARTITION p7sp3 VALUES IN (4),
    SUBPARTITION p7sp4 VALUES IN (5),
    SUBPARTITION p7sp5 VALUES IN (6),
    SUBPARTITION p7sp6 VALUES IN (7),
    SUBPARTITION p7sp7 VALUES IN (8)
  )
);
SET FOREIGN_KEY_CHECKS=1;
