SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t19`;
CREATE TABLE `t19` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(62) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint DEFAULT NULL,
  `decimal_col` decimal(26,6) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(2) DEFAULT NULL,
  `timestamp_col` timestamp(5) NULL DEFAULT NULL,
  `time_col` time(1) DEFAULT NULL,
  `varchar_col` varchar(95) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(66) DEFAULT NULL,
  `varbinary_col` varbinary(127) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(54) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(23,10) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t19_000` json DEFAULT NULL,
  `extra_t19_001` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_002` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_003` mediumblob,
  `extra_t19_004` json DEFAULT NULL,
  `extra_t19_005` decimal(11,3) DEFAULT NULL,
  `extra_t19_006` float unsigned DEFAULT NULL,
  `extra_t19_007` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_008` json DEFAULT NULL,
  `extra_t19_009` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_010` decimal(17,4) DEFAULT NULL,
  `extra_t19_011` blob,
  `extra_t19_012` json DEFAULT NULL,
  `extra_t19_013` float DEFAULT NULL,
  `extra_t19_014` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_015` varbinary(30) DEFAULT NULL,
  `extra_t19_016` blob,
  `extra_t19_017` datetime(6) DEFAULT NULL,
  `extra_t19_018` float unsigned DEFAULT NULL,
  `extra_t19_019` binary(8) DEFAULT NULL,
  `extra_t19_020` blob,
  `extra_t19_021` date DEFAULT NULL,
  `extra_t19_022` json DEFAULT NULL,
  `extra_t19_023` json DEFAULT NULL,
  `extra_t19_024` decimal(18,4) DEFAULT NULL,
  `extra_t19_025` timestamp(1) DEFAULT NULL,
  `extra_t19_026` json DEFAULT NULL,
  `extra_t19_027` bit(53) DEFAULT NULL,
  `extra_t19_028` smallint DEFAULT NULL,
  `extra_t19_029` bit(41) DEFAULT NULL,
  `extra_t19_030` time(5) DEFAULT NULL,
  `extra_t19_031` bit(12) DEFAULT NULL,
  `extra_t19_032` smallint DEFAULT NULL,
  `extra_t19_033` bit(2) DEFAULT NULL,
  `extra_t19_034` year DEFAULT NULL,
  `extra_t19_035` double unsigned DEFAULT NULL,
  `extra_t19_036` set('s6_1','s6_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_037` bit(23) DEFAULT NULL,
  `extra_t19_038` decimal(9,1) DEFAULT NULL,
  `extra_t19_039` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_040` bit(56) DEFAULT NULL,
  `extra_t19_041` bit(33) DEFAULT NULL,
  `extra_t19_042` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_043` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_044` bit(38) DEFAULT NULL,
  `extra_t19_045` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_046` json DEFAULT NULL,
  `extra_t19_047` time(4) DEFAULT NULL,
  `extra_t19_048` tinyblob,
  `extra_t19_049` double DEFAULT NULL,
  `extra_t19_050` bigint DEFAULT NULL,
  `extra_t19_051` json DEFAULT NULL,
  `extra_t19_052` double unsigned DEFAULT NULL,
  `extra_t19_053` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_054` mediumint DEFAULT NULL,
  `extra_t19_055` json DEFAULT NULL,
  `extra_t19_056` varbinary(1) DEFAULT NULL,
  `extra_t19_057` varbinary(28) DEFAULT NULL,
  `extra_t19_058` double DEFAULT NULL,
  `extra_t19_059` enum('e9_1','e9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_060` json DEFAULT NULL,
  `extra_t19_061` tinyint unsigned DEFAULT NULL,
  `extra_t19_062` decimal(19,2) DEFAULT NULL,
  `extra_t19_063` set('s3_1','s3_2','s3_3','s3_4','s3_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_064` decimal(15,8) DEFAULT NULL,
  `extra_t19_065` smallint DEFAULT NULL,
  `extra_t19_066` float unsigned DEFAULT NULL,
  `extra_t19_067` set('s7_1','s7_2','s7_3','s7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_068` year DEFAULT NULL,
  `extra_t19_069` enum('e9_1','e9_2','e9_3','e9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_070` smallint unsigned DEFAULT NULL,
  `extra_t19_071` float unsigned DEFAULT NULL,
  `extra_t19_072` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_073` year DEFAULT NULL,
  `extra_t19_074` bit(6) DEFAULT NULL,
  `extra_t19_075` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_076` decimal(16,3) DEFAULT NULL,
  `extra_t19_077` blob,
  `extra_t19_078` double unsigned DEFAULT NULL,
  `extra_t19_079` decimal(12,2) DEFAULT NULL,
  `extra_t19_080` set('s0_1','s0_2','s0_3','s0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_081` decimal(12,5) DEFAULT NULL,
  `extra_t19_082` date DEFAULT NULL,
  `extra_t19_083` enum('e3_1','e3_2','e3_3','e3_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_084` bit(9) DEFAULT NULL,
  `extra_t19_085` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_086` decimal(20,8) DEFAULT NULL,
  `extra_t19_087` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_088` tinyint unsigned DEFAULT NULL,
  `extra_t19_089` json DEFAULT NULL,
  `extra_t19_090` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_091` double unsigned DEFAULT NULL,
  `extra_t19_092` bit(54) DEFAULT NULL,
  `extra_t19_093` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_094` tinyint unsigned DEFAULT NULL,
  `extra_t19_095` decimal(7,1) DEFAULT NULL,
  `extra_t19_096` decimal(19,2) DEFAULT NULL,
  `extra_t19_097` float DEFAULT NULL,
  `extra_t19_098` float unsigned DEFAULT NULL,
  `extra_t19_099` json DEFAULT NULL,
  `extra_t19_100` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_101` double unsigned DEFAULT NULL,
  `extra_t19_102` double unsigned DEFAULT NULL,
  `extra_t19_103` time(1) DEFAULT NULL,
  `extra_t19_104` decimal(19,6) DEFAULT NULL,
  `extra_t19_105` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_106` year DEFAULT NULL,
  `extra_t19_107` bit(43) DEFAULT NULL,
  `extra_t19_108` set('s8_1','s8_2','s8_3','s8_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_109` time(2) DEFAULT NULL,
  `extra_t19_110` varbinary(32) DEFAULT NULL,
  `extra_t19_111` decimal(18,0) DEFAULT NULL,
  `extra_t19_112` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_113` json DEFAULT NULL,
  `extra_t19_114` decimal(6,2) DEFAULT NULL,
  `extra_t19_115` varbinary(12) DEFAULT NULL,
  `extra_t19_116` tinyblob,
  `extra_t19_117` datetime(5) DEFAULT NULL,
  `extra_t19_118` decimal(22,8) DEFAULT NULL,
  `extra_t19_119` decimal(18,3) DEFAULT NULL,
  `extra_t19_120` decimal(10,1) DEFAULT NULL,
  `extra_t19_121` bit(28) DEFAULT NULL,
  `extra_t19_122` mediumblob,
  `extra_t19_123` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_124` decimal(7,4) DEFAULT NULL,
  `extra_t19_125` json DEFAULT NULL,
  `extra_t19_126` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_127` time(2) DEFAULT NULL,
  `extra_t19_128` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_129` time(5) DEFAULT NULL,
  `extra_t19_130` bigint unsigned DEFAULT NULL,
  `extra_t19_131` binary(6) DEFAULT NULL,
  `extra_t19_132` tinyblob,
  `extra_t19_133` decimal(20,5) DEFAULT NULL,
  `extra_t19_134` longblob,
  `extra_t19_135` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_136` bit(49) DEFAULT NULL,
  `extra_t19_137` year DEFAULT NULL,
  `extra_t19_138` bit(16) DEFAULT NULL,
  `extra_t19_139` longblob,
  `extra_t19_140` json DEFAULT NULL,
  `extra_t19_141` smallint DEFAULT NULL,
  `extra_t19_142` varbinary(32) DEFAULT NULL,
  `extra_t19_143` bit(2) DEFAULT NULL,
  `extra_t19_144` decimal(6,3) DEFAULT NULL,
  `extra_t19_145` set('s5_1','s5_2','s5_3','s5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_146` mediumblob,
  `extra_t19_147` binary(17) DEFAULT NULL,
  `extra_t19_148` set('s8_1','s8_2','s8_3','s8_4','s8_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_149` decimal(17,1) DEFAULT NULL,
  `extra_t19_150` double DEFAULT NULL,
  `extra_t19_151` tinyint DEFAULT NULL,
  `extra_t19_152` bit(39) DEFAULT NULL,
  `extra_t19_153` datetime(4) DEFAULT NULL,
  `extra_t19_154` set('s4_1','s4_2','s4_3','s4_4','s4_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_155` bit(46) DEFAULT NULL,
  `extra_t19_156` enum('e6_1','e6_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_157` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_158` double DEFAULT NULL,
  `extra_t19_159` set('s9_1','s9_2','s9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t19_160` time(3) DEFAULT NULL,
  `extra_t19_161` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_162` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_163` mediumint unsigned DEFAULT NULL,
  `extra_t19_164` tinyblob,
  `extra_t19_165` blob,
  `extra_t19_166` datetime(1) DEFAULT NULL,
  `extra_t19_167` int DEFAULT NULL,
  `extra_t19_168` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_169` tinyint unsigned DEFAULT NULL,
  `extra_t19_170` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_171` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t19_172` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t19_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t19_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t19_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t19_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t19_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t19_int_col` (`int_col`),
  KEY `idx_t19_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t19_year_char` (`year_col`,`char_col`),
  KEY `idx_t19_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t19_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t19_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t19_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t19_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t19_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t19_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t19_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t19_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t19_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t19_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t19_year_func` ((year(`datetime_col`))),
  KEY `idx_t19_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t19_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t19_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t19_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t19_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t19_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t19_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t19_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t19_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t19_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t19_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t19_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t19_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t19_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t19_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t19_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t19_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t19_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t19_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t19_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t19_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t19_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t19_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t19_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t19_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t19_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t19_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t19_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t19_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t19_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t19_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t19_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t19_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t19_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t19_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t19_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t19_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t19_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t19_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t19_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t19_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE (`tenant_id`)
SUBPARTITION BY HASH (`subpart_id`) SUBPARTITIONS 8 (
  PARTITION p0 VALUES LESS THAN (2),
  PARTITION p1 VALUES LESS THAN (3),
  PARTITION p2 VALUES LESS THAN (4),
  PARTITION p3 VALUES LESS THAN (5),
  PARTITION p4 VALUES LESS THAN (6),
  PARTITION p5 VALUES LESS THAN (7),
  PARTITION p6 VALUES LESS THAN (8),
  PARTITION p7 VALUES LESS THAN (MAXVALUE)
);
SET FOREIGN_KEY_CHECKS=1;
