SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TEMPORARY TABLE IF EXISTS `t2`;
CREATE TEMPORARY TABLE `t2` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(101) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(22,6) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(5) DEFAULT NULL,
  `timestamp_col` timestamp(6) NULL DEFAULT NULL,
  `time_col` time(6) DEFAULT NULL,
  `varchar_col` varchar(188) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(130) DEFAULT NULL,
  `varbinary_col` varbinary(50) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(55) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(17,9) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t2_000` year DEFAULT NULL,
  `extra_t2_001` year DEFAULT NULL,
  `extra_t2_002` json DEFAULT NULL,
  `extra_t2_003` json DEFAULT NULL,
  `extra_t2_004` float DEFAULT NULL,
  `extra_t2_005` datetime DEFAULT NULL,
  `extra_t2_006` int unsigned DEFAULT NULL,
  `extra_t2_007` date DEFAULT NULL,
  `extra_t2_008` date DEFAULT NULL,
  `extra_t2_009` tinyblob,
  `extra_t2_010` date DEFAULT NULL,
  `extra_t2_011` decimal(18,4) DEFAULT NULL,
  `extra_t2_012` json DEFAULT NULL,
  `extra_t2_013` bit(23) DEFAULT NULL,
  `extra_t2_014` enum('e4_1','e4_2','e4_3','e4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_015` float unsigned DEFAULT NULL,
  `extra_t2_016` float unsigned DEFAULT NULL,
  `extra_t2_017` time(6) DEFAULT NULL,
  `extra_t2_018` bit(56) DEFAULT NULL,
  `extra_t2_019` smallint unsigned DEFAULT NULL,
  `extra_t2_020` mediumint unsigned DEFAULT NULL,
  `extra_t2_021` varbinary(12) DEFAULT NULL,
  `extra_t2_022` enum('e2_1','e2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_023` set('s3_1','s3_2','s3_3','s3_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_024` json DEFAULT NULL,
  `extra_t2_025` double DEFAULT NULL,
  `extra_t2_026` bigint unsigned DEFAULT NULL,
  `extra_t2_027` decimal(9,4) DEFAULT NULL,
  `extra_t2_028` bit(52) DEFAULT NULL,
  `extra_t2_029` date DEFAULT NULL,
  `extra_t2_030` json DEFAULT NULL,
  `extra_t2_031` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_032` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_033` date DEFAULT NULL,
  `extra_t2_034` decimal(11,5) DEFAULT NULL,
  `extra_t2_035` time DEFAULT NULL,
  `extra_t2_036` mediumint unsigned DEFAULT NULL,
  `extra_t2_037` json DEFAULT NULL,
  `extra_t2_038` time(1) DEFAULT NULL,
  `extra_t2_039` json DEFAULT NULL,
  `extra_t2_040` decimal(10,0) DEFAULT NULL,
  `extra_t2_041` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_042` enum('e2_1','e2_2','e2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_043` mediumblob,
  `extra_t2_044` set('s4_1','s4_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_045` decimal(11,1) DEFAULT NULL,
  `extra_t2_046` date DEFAULT NULL,
  `extra_t2_047` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_048` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_049` bit(58) DEFAULT NULL,
  `extra_t2_050` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_051` bit(3) DEFAULT NULL,
  `extra_t2_052` tinyint unsigned DEFAULT NULL,
  `extra_t2_053` blob,
  `extra_t2_054` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_055` json DEFAULT NULL,
  `extra_t2_056` double DEFAULT NULL,
  `extra_t2_057` smallint DEFAULT NULL,
  `extra_t2_058` decimal(9,1) DEFAULT NULL,
  `extra_t2_059` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_060` bit(40) DEFAULT NULL,
  `extra_t2_061` date DEFAULT NULL,
  `extra_t2_062` int unsigned DEFAULT NULL,
  `extra_t2_063` json DEFAULT NULL,
  `extra_t2_064` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_065` decimal(13,4) DEFAULT NULL,
  `extra_t2_066` float unsigned DEFAULT NULL,
  `extra_t2_067` decimal(8,4) DEFAULT NULL,
  `extra_t2_068` tinyint unsigned DEFAULT NULL,
  `extra_t2_069` set('s9_1','s9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_070` double unsigned DEFAULT NULL,
  `extra_t2_071` json DEFAULT NULL,
  `extra_t2_072` enum('e2_1','e2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_073` varbinary(12) DEFAULT NULL,
  `extra_t2_074` decimal(14,6) DEFAULT NULL,
  `extra_t2_075` date DEFAULT NULL,
  `extra_t2_076` bit(22) DEFAULT NULL,
  `extra_t2_077` datetime(1) DEFAULT NULL,
  `extra_t2_078` mediumblob,
  `extra_t2_079` mediumblob,
  `extra_t2_080` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_081` double DEFAULT NULL,
  `extra_t2_082` datetime(6) DEFAULT NULL,
  `extra_t2_083` decimal(11,1) DEFAULT NULL,
  `extra_t2_084` double unsigned DEFAULT NULL,
  `extra_t2_085` enum('e5_1','e5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_086` bit(3) DEFAULT NULL,
  `extra_t2_087` json DEFAULT NULL,
  `extra_t2_088` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_089` int unsigned DEFAULT NULL,
  `extra_t2_090` datetime(1) DEFAULT NULL,
  `extra_t2_091` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_092` tinyblob,
  `extra_t2_093` mediumint DEFAULT NULL,
  `extra_t2_094` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_095` float DEFAULT NULL,
  `extra_t2_096` bigint unsigned DEFAULT NULL,
  `extra_t2_097` binary(24) DEFAULT NULL,
  `extra_t2_098` decimal(17,3) DEFAULT NULL,
  `extra_t2_099` enum('e9_1','e9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_100` tinyblob,
  `extra_t2_101` float unsigned DEFAULT NULL,
  `extra_t2_102` json DEFAULT NULL,
  `extra_t2_103` set('s3_1','s3_2','s3_3','s3_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_104` float unsigned DEFAULT NULL,
  `extra_t2_105` enum('e5_1','e5_2','e5_3','e5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_106` mediumblob,
  `extra_t2_107` bit(48) DEFAULT NULL,
  `extra_t2_108` smallint DEFAULT NULL,
  `extra_t2_109` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_110` blob,
  `extra_t2_111` enum('e1_1','e1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_112` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_113` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_114` json DEFAULT NULL,
  `extra_t2_115` double DEFAULT NULL,
  `extra_t2_116` decimal(26,8) DEFAULT NULL,
  `extra_t2_117` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_118` longblob,
  `extra_t2_119` decimal(11,5) DEFAULT NULL,
  `extra_t2_120` json DEFAULT NULL,
  `extra_t2_121` float DEFAULT NULL,
  `extra_t2_122` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_123` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_124` time(3) DEFAULT NULL,
  `extra_t2_125` double unsigned DEFAULT NULL,
  `extra_t2_126` enum('e6_1','e6_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_127` json DEFAULT NULL,
  `extra_t2_128` enum('e8_1','e8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_129` bit(18) DEFAULT NULL,
  `extra_t2_130` double unsigned DEFAULT NULL,
  `extra_t2_131` enum('e1_1','e1_2','e1_3','e1_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_132` blob,
  `extra_t2_133` tinyint DEFAULT NULL,
  `extra_t2_134` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_135` date DEFAULT NULL,
  `extra_t2_136` decimal(12,5) DEFAULT NULL,
  `extra_t2_137` date DEFAULT NULL,
  `extra_t2_138` json DEFAULT NULL,
  `extra_t2_139` bit(54) DEFAULT NULL,
  `extra_t2_140` bit(14) DEFAULT NULL,
  `extra_t2_141` bit(42) DEFAULT NULL,
  `extra_t2_142` double unsigned DEFAULT NULL,
  `extra_t2_143` double unsigned DEFAULT NULL,
  `extra_t2_144` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_145` double unsigned DEFAULT NULL,
  `extra_t2_146` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_147` decimal(13,0) DEFAULT NULL,
  `extra_t2_148` double unsigned DEFAULT NULL,
  `extra_t2_149` json DEFAULT NULL,
  `extra_t2_150` double unsigned DEFAULT NULL,
  `extra_t2_151` float unsigned DEFAULT NULL,
  `extra_t2_152` varbinary(9) DEFAULT NULL,
  `extra_t2_153` mediumint DEFAULT NULL,
  `extra_t2_154` json DEFAULT NULL,
  `extra_t2_155` double DEFAULT NULL,
  `extra_t2_156` set('s6_1','s6_2','s6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_157` date DEFAULT NULL,
  `extra_t2_158` tinyblob,
  `extra_t2_159` decimal(10,1) DEFAULT NULL,
  `extra_t2_160` enum('e0_1','e0_2','e0_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_161` datetime(5) DEFAULT NULL,
  `extra_t2_162` smallint unsigned DEFAULT NULL,
  `extra_t2_163` bit(42) DEFAULT NULL,
  `extra_t2_164` mediumblob,
  `extra_t2_165` decimal(10,5) DEFAULT NULL,
  `extra_t2_166` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_167` date DEFAULT NULL,
  `extra_t2_168` mediumblob,
  `extra_t2_169` binary(20) DEFAULT NULL,
  `extra_t2_170` bit(53) DEFAULT NULL,
  `extra_t2_171` tinyblob,
  `extra_t2_172` enum('e2_1','e2_2','e2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_173` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_174` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_175` double unsigned DEFAULT NULL,
  `extra_t2_176` mediumblob,
  `extra_t2_177` bit(21) DEFAULT NULL,
  `extra_t2_178` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_179` bit(55) DEFAULT NULL,
  `extra_t2_180` bit(26) DEFAULT NULL,
  `extra_t2_181` mediumint DEFAULT NULL,
  `extra_t2_182` float unsigned DEFAULT NULL,
  `extra_t2_183` set('s3_1','s3_2','s3_3','s3_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_184` mediumblob,
  `extra_t2_185` json DEFAULT NULL,
  `extra_t2_186` binary(3) DEFAULT NULL,
  `extra_t2_187` json DEFAULT NULL,
  `extra_t2_188` enum('e8_1','e8_2','e8_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_189` decimal(20,5) DEFAULT NULL,
  `extra_t2_190` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_191` int unsigned DEFAULT NULL,
  `extra_t2_192` decimal(20,7) DEFAULT NULL,
  `extra_t2_193` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_194` bit(60) DEFAULT NULL,
  `extra_t2_195` bigint unsigned DEFAULT NULL,
  `extra_t2_196` mediumint unsigned DEFAULT NULL,
  `extra_t2_197` blob,
  `extra_t2_198` bit(8) DEFAULT NULL,
  `extra_t2_199` bigint unsigned DEFAULT NULL,
  `extra_t2_200` mediumint DEFAULT NULL,
  `extra_t2_201` bit(5) DEFAULT NULL,
  `extra_t2_202` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_203` year DEFAULT NULL,
  `extra_t2_204` enum('e4_1','e4_2','e4_3','e4_4','e4_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_205` set('s5_1','s5_2','s5_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_206` json DEFAULT NULL,
  `extra_t2_207` json DEFAULT NULL,
  `extra_t2_208` tinyblob,
  `extra_t2_209` double DEFAULT NULL,
  `extra_t2_210` float DEFAULT NULL,
  `extra_t2_211` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_212` json DEFAULT NULL,
  `extra_t2_213` decimal(14,2) DEFAULT NULL,
  `extra_t2_214` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_215` enum('e5_1','e5_2','e5_3','e5_4','e5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_216` json DEFAULT NULL,
  `extra_t2_217` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_218` varbinary(30) DEFAULT NULL,
  `extra_t2_219` bit(1) DEFAULT NULL,
  `extra_t2_220` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_221` enum('e1_1','e1_2','e1_3','e1_4','e1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_222` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_223` tinyblob,
  `extra_t2_224` smallint unsigned DEFAULT NULL,
  `extra_t2_225` json DEFAULT NULL,
  `extra_t2_226` longblob,
  `extra_t2_227` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_228` year DEFAULT NULL,
  `extra_t2_229` json DEFAULT NULL,
  `extra_t2_230` varbinary(22) DEFAULT NULL,
  `extra_t2_231` datetime(1) DEFAULT NULL,
  `extra_t2_232` set('s2_1','s2_2','s2_3','s2_4','s2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_233` varbinary(11) DEFAULT NULL,
  `extra_t2_234` varbinary(29) DEFAULT NULL,
  `extra_t2_235` varbinary(18) DEFAULT NULL,
  `extra_t2_236` mediumint DEFAULT NULL,
  `extra_t2_237` json DEFAULT NULL,
  `extra_t2_238` varbinary(26) DEFAULT NULL,
  `extra_t2_239` json DEFAULT NULL,
  `extra_t2_240` set('s0_1','s0_2','s0_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_241` longblob,
  `extra_t2_242` bit(57) DEFAULT NULL,
  `extra_t2_243` double unsigned DEFAULT NULL,
  `extra_t2_244` datetime(4) DEFAULT NULL,
  `extra_t2_245` varbinary(19) DEFAULT NULL,
  `extra_t2_246` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_247` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_248` smallint DEFAULT NULL,
  `extra_t2_249` decimal(16,3) DEFAULT NULL,
  `extra_t2_250` year DEFAULT NULL,
  `extra_t2_251` enum('e1_1','e1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_252` set('s2_1','s2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_253` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_254` datetime(2) DEFAULT NULL,
  `extra_t2_255` longblob,
  `extra_t2_256` decimal(7,0) DEFAULT NULL,
  `extra_t2_257` tinyblob,
  `extra_t2_258` decimal(12,8) DEFAULT NULL,
  `extra_t2_259` decimal(13,6) DEFAULT NULL,
  `extra_t2_260` json DEFAULT NULL,
  `extra_t2_261` mediumblob,
  `extra_t2_262` bit(22) DEFAULT NULL,
  `extra_t2_263` bit(46) DEFAULT NULL,
  `extra_t2_264` float DEFAULT NULL,
  `extra_t2_265` json DEFAULT NULL,
  `extra_t2_266` bit(39) DEFAULT NULL,
  `extra_t2_267` json DEFAULT NULL,
  `extra_t2_268` decimal(8,6) DEFAULT NULL,
  `extra_t2_269` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_270` varbinary(13) DEFAULT NULL,
  `extra_t2_271` decimal(9,7) DEFAULT NULL,
  `extra_t2_272` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_273` int unsigned DEFAULT NULL,
  `extra_t2_274` year DEFAULT NULL,
  `extra_t2_275` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_276` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_277` binary(21) DEFAULT NULL,
  `extra_t2_278` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_279` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_280` varbinary(22) DEFAULT NULL,
  `extra_t2_281` json DEFAULT NULL,
  `extra_t2_282` bit(27) DEFAULT NULL,
  `extra_t2_283` decimal(8,0) DEFAULT NULL,
  `extra_t2_284` tinyint DEFAULT NULL,
  `extra_t2_285` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_286` time(6) DEFAULT NULL,
  `extra_t2_287` mediumblob,
  `extra_t2_288` longblob,
  `extra_t2_289` enum('e9_1','e9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_290` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_291` bit(27) DEFAULT NULL,
  `extra_t2_292` set('s2_1','s2_2','s2_3','s2_4','s2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_293` bit(38) DEFAULT NULL,
  `extra_t2_294` enum('e4_1','e4_2','e4_3','e4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_295` decimal(14,3) DEFAULT NULL,
  `extra_t2_296` longblob,
  `extra_t2_297` binary(1) DEFAULT NULL,
  `extra_t2_298` double DEFAULT NULL,
  `extra_t2_299` double unsigned DEFAULT NULL,
  `extra_t2_300` bit(45) DEFAULT NULL,
  `extra_t2_301` date DEFAULT NULL,
  `extra_t2_302` set('s2_1','s2_2','s2_3','s2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_303` enum('e3_1','e3_2','e3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_304` enum('e4_1','e4_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_305` float DEFAULT NULL,
  `extra_t2_306` decimal(10,2) DEFAULT NULL,
  `extra_t2_307` enum('e7_1','e7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_308` decimal(18,3) DEFAULT NULL,
  `extra_t2_309` smallint DEFAULT NULL,
  `extra_t2_310` double unsigned DEFAULT NULL,
  `extra_t2_311` bit(51) DEFAULT NULL,
  `extra_t2_312` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_313` bit(46) DEFAULT NULL,
  `extra_t2_314` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_315` bigint DEFAULT NULL,
  `extra_t2_316` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_317` enum('e7_1','e7_2','e7_3','e7_4','e7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_318` float DEFAULT NULL,
  `extra_t2_319` bit(49) DEFAULT NULL,
  `extra_t2_320` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_321` double DEFAULT NULL,
  `extra_t2_322` bigint DEFAULT NULL,
  `extra_t2_323` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_324` json DEFAULT NULL,
  `extra_t2_325` bigint unsigned DEFAULT NULL,
  `extra_t2_326` decimal(17,5) DEFAULT NULL,
  `extra_t2_327` json DEFAULT NULL,
  `extra_t2_328` mediumblob,
  `extra_t2_329` decimal(12,2) DEFAULT NULL,
  `extra_t2_330` double unsigned DEFAULT NULL,
  `extra_t2_331` json DEFAULT NULL,
  `extra_t2_332` decimal(12,1) DEFAULT NULL,
  `extra_t2_333` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t2_334` double DEFAULT NULL,
  `extra_t2_335` decimal(15,1) DEFAULT NULL,
  `extra_t2_336` datetime(5) DEFAULT NULL,
  `extra_t2_337` decimal(9,7) DEFAULT NULL,
  `extra_t2_338` date DEFAULT NULL,
  `extra_t2_339` time(1) DEFAULT NULL,
  `extra_t2_340` datetime(6) DEFAULT NULL,
  `extra_t2_341` decimal(8,0) DEFAULT NULL,
  `extra_t2_342` double unsigned DEFAULT NULL,
  `extra_t2_343` timestamp(6) DEFAULT NULL,
  `extra_t2_344` enum('e4_1','e4_2','e4_3','e4_4','e4_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t2_345` json DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t2_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t2_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t2_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t2_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t2_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t2_int_col` (`int_col`),
  UNIQUE KEY `idx_t2_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t2_year_char` (`year_col`,`char_col`),
  UNIQUE KEY `idx_t2_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  UNIQUE KEY `idx_t2_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  UNIQUE KEY `idx_t2_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t2_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t2_binary_combo` (`binary_col`,`varbinary_col`),
  UNIQUE KEY `idx_t2_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  UNIQUE KEY `idx_t2_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t2_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  UNIQUE KEY `idx_t2_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t2_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t2_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t2_year_func` ((year(`datetime_col`))),
  UNIQUE KEY `idx_t2_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  UNIQUE KEY `idx_t2_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t2_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t2_extra_abs_smallint` ((abs(`smallint_col`))),
  UNIQUE KEY `idx_t2_extra_time_to_sec` ((time_to_sec(`time_col`))),
  UNIQUE KEY `idx_t2_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t2_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t2_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `idx_t2_extra_mediumblob` (`mediumblob_col`(16)),
  UNIQUE KEY `idx_t2_extra_double_ceiling` ((ceiling(`double_col`))),
  UNIQUE KEY `idx_t2_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t2_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t2_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  UNIQUE KEY `idx_t2_extra_longblob` (`longblob_col`(16)),
  UNIQUE KEY `idx_t2_extra_decimal_round` ((round(`decimal_col`,2))),
  UNIQUE KEY `idx_t2_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t2_extra_text_set` (`text_col`(12),`set_col`),
  UNIQUE KEY `idx_t2_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t2_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  UNIQUE KEY `idx_t2_extra_tinyblob` (`tinyblob_col`(8)),
  UNIQUE KEY `idx_t2_extra_subpart_big` (`subpart_id`,`bigint_col`),
  UNIQUE KEY `idx_t2_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  UNIQUE KEY `idx_t2_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t2_extra_month_datetime` ((month(`datetime_col`))),
  UNIQUE KEY `idx_t2_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  UNIQUE KEY `idx_t2_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t2_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t2_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t2_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  UNIQUE KEY `idx_t2_extra_decimal_desc` (`decimal_col` DESC),
  UNIQUE KEY `idx_t2_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t2_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t2_extra_time_timestamp` (`time_col`,`timestamp_col`),
  UNIQUE KEY `idx_t2_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  UNIQUE KEY `idx_t2_extra_date_days` ((to_days(`date_col`))),
  UNIQUE KEY `idx_t2_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t2_extra_dayofweek` ((dayofweek(`date_col`))),
  UNIQUE KEY `idx_t2_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t2_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  UNIQUE KEY `idx_t2_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t2_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
