SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t26`;
CREATE TABLE `t26` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(190) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint DEFAULT NULL,
  `decimal_col` decimal(20,3) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(1) DEFAULT NULL,
  `timestamp_col` timestamp(1) NULL DEFAULT NULL,
  `time_col` time(1) DEFAULT NULL,
  `varchar_col` varchar(244) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(248) DEFAULT NULL,
  `varbinary_col` varbinary(3) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(22) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(22,3) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t26_000` smallint DEFAULT NULL,
  `extra_t26_001` json DEFAULT NULL,
  `extra_t26_002` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_003` char(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_004` mediumint DEFAULT NULL,
  `extra_t26_005` bigint unsigned DEFAULT NULL,
  `extra_t26_006` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_007` decimal(13,1) DEFAULT NULL,
  `extra_t26_008` year DEFAULT NULL,
  `extra_t26_009` varbinary(22) DEFAULT NULL,
  `extra_t26_010` bit(64) DEFAULT NULL,
  `extra_t26_011` enum('e1_1','e1_2','e1_3','e1_4','e1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_012` json DEFAULT NULL,
  `extra_t26_013` decimal(22,8) DEFAULT NULL,
  `extra_t26_014` decimal(21,3) DEFAULT NULL,
  `extra_t26_015` year DEFAULT NULL,
  `extra_t26_016` bit(29) DEFAULT NULL,
  `extra_t26_017` set('s7_1','s7_2','s7_3','s7_4','s7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_018` enum('e8_1','e8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_019` double DEFAULT NULL,
  `extra_t26_020` decimal(16,4) DEFAULT NULL,
  `extra_t26_021` blob,
  `extra_t26_022` int unsigned DEFAULT NULL,
  `extra_t26_023` decimal(9,1) DEFAULT NULL,
  `extra_t26_024` timestamp(2) DEFAULT NULL,
  `extra_t26_025` mediumblob,
  `extra_t26_026` bit(38) DEFAULT NULL,
  `extra_t26_027` json DEFAULT NULL,
  `extra_t26_028` decimal(12,0) DEFAULT NULL,
  `extra_t26_029` date DEFAULT NULL,
  `extra_t26_030` double DEFAULT NULL,
  `extra_t26_031` varbinary(1) DEFAULT NULL,
  `extra_t26_032` enum('e2_1','e2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_033` timestamp DEFAULT NULL,
  `extra_t26_034` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_035` json DEFAULT NULL,
  `extra_t26_036` smallint unsigned DEFAULT NULL,
  `extra_t26_037` decimal(9,4) DEFAULT NULL,
  `extra_t26_038` mediumblob,
  `extra_t26_039` char(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_040` decimal(18,0) DEFAULT NULL,
  `extra_t26_041` double DEFAULT NULL,
  `extra_t26_042` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_043` json DEFAULT NULL,
  `extra_t26_044` double DEFAULT NULL,
  `extra_t26_045` decimal(25,7) DEFAULT NULL,
  `extra_t26_046` bit(39) DEFAULT NULL,
  `extra_t26_047` enum('e7_1','e7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_048` float DEFAULT NULL,
  `extra_t26_049` float DEFAULT NULL,
  `extra_t26_050` smallint unsigned DEFAULT NULL,
  `extra_t26_051` set('s1_1','s1_2','s1_3','s1_4','s1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_052` double unsigned DEFAULT NULL,
  `extra_t26_053` bit(36) DEFAULT NULL,
  `extra_t26_054` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_055` float DEFAULT NULL,
  `extra_t26_056` time(1) DEFAULT NULL,
  `extra_t26_057` double unsigned DEFAULT NULL,
  `extra_t26_058` tinyint unsigned DEFAULT NULL,
  `extra_t26_059` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_060` bigint DEFAULT NULL,
  `extra_t26_061` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_062` json DEFAULT NULL,
  `extra_t26_063` datetime(3) DEFAULT NULL,
  `extra_t26_064` bit(40) DEFAULT NULL,
  `extra_t26_065` set('s5_1','s5_2','s5_3','s5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_066` json DEFAULT NULL,
  `extra_t26_067` decimal(6,5) DEFAULT NULL,
  `extra_t26_068` json DEFAULT NULL,
  `extra_t26_069` timestamp(4) DEFAULT NULL,
  `extra_t26_070` int DEFAULT NULL,
  `extra_t26_071` tinyint unsigned DEFAULT NULL,
  `extra_t26_072` enum('e2_1','e2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_073` time DEFAULT NULL,
  `extra_t26_074` bit(19) DEFAULT NULL,
  `extra_t26_075` year DEFAULT NULL,
  `extra_t26_076` decimal(21,7) DEFAULT NULL,
  `extra_t26_077` year DEFAULT NULL,
  `extra_t26_078` mediumint DEFAULT NULL,
  `extra_t26_079` json DEFAULT NULL,
  `extra_t26_080` float DEFAULT NULL,
  `extra_t26_081` json DEFAULT NULL,
  `extra_t26_082` decimal(13,6) DEFAULT NULL,
  `extra_t26_083` mediumblob,
  `extra_t26_084` datetime(3) DEFAULT NULL,
  `extra_t26_085` mediumblob,
  `extra_t26_086` smallint DEFAULT NULL,
  `extra_t26_087` smallint DEFAULT NULL,
  `extra_t26_088` enum('e8_1','e8_2','e8_3','e8_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_089` decimal(13,1) DEFAULT NULL,
  `extra_t26_090` json DEFAULT NULL,
  `extra_t26_091` bit(19) DEFAULT NULL,
  `extra_t26_092` bit(20) DEFAULT NULL,
  `extra_t26_093` json DEFAULT NULL,
  `extra_t26_094` double DEFAULT NULL,
  `extra_t26_095` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_096` enum('e6_1','e6_2','e6_3','e6_4','e6_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_097` double DEFAULT NULL,
  `extra_t26_098` blob,
  `extra_t26_099` double DEFAULT NULL,
  `extra_t26_100` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_101` decimal(8,7) DEFAULT NULL,
  `extra_t26_102` int unsigned DEFAULT NULL,
  `extra_t26_103` mediumint unsigned DEFAULT NULL,
  `extra_t26_104` json DEFAULT NULL,
  `extra_t26_105` bigint unsigned DEFAULT NULL,
  `extra_t26_106` json DEFAULT NULL,
  `extra_t26_107` json DEFAULT NULL,
  `extra_t26_108` int DEFAULT NULL,
  `extra_t26_109` int unsigned DEFAULT NULL,
  `extra_t26_110` mediumblob,
  `extra_t26_111` float DEFAULT NULL,
  `extra_t26_112` json DEFAULT NULL,
  `extra_t26_113` bit(21) DEFAULT NULL,
  `extra_t26_114` year DEFAULT NULL,
  `extra_t26_115` enum('e5_1','e5_2','e5_3','e5_4','e5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_116` enum('e6_1','e6_2','e6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_117` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_118` datetime(2) DEFAULT NULL,
  `extra_t26_119` decimal(8,0) DEFAULT NULL,
  `extra_t26_120` timestamp DEFAULT NULL,
  `extra_t26_121` json DEFAULT NULL,
  `extra_t26_122` datetime(6) DEFAULT NULL,
  `extra_t26_123` enum('e3_1','e3_2','e3_3','e3_4','e3_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_124` json DEFAULT NULL,
  `extra_t26_125` enum('e5_1','e5_2','e5_3','e5_4','e5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_126` mediumblob,
  `extra_t26_127` decimal(11,3) DEFAULT NULL,
  `extra_t26_128` timestamp(4) DEFAULT NULL,
  `extra_t26_129` blob,
  `extra_t26_130` float DEFAULT NULL,
  `extra_t26_131` datetime(4) DEFAULT NULL,
  `extra_t26_132` timestamp(2) DEFAULT NULL,
  `extra_t26_133` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_134` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_135` decimal(19,5) DEFAULT NULL,
  `extra_t26_136` decimal(17,5) DEFAULT NULL,
  `extra_t26_137` json DEFAULT NULL,
  `extra_t26_138` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_139` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_140` decimal(19,8) DEFAULT NULL,
  `extra_t26_141` enum('e1_1','e1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_142` float DEFAULT NULL,
  `extra_t26_143` tinyint unsigned DEFAULT NULL,
  `extra_t26_144` json DEFAULT NULL,
  `extra_t26_145` int unsigned DEFAULT NULL,
  `extra_t26_146` tinyblob,
  `extra_t26_147` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_148` time DEFAULT NULL,
  `extra_t26_149` bit(25) DEFAULT NULL,
  `extra_t26_150` decimal(15,5) DEFAULT NULL,
  `extra_t26_151` float DEFAULT NULL,
  `extra_t26_152` float DEFAULT NULL,
  `extra_t26_153` bit(40) DEFAULT NULL,
  `extra_t26_154` decimal(16,1) DEFAULT NULL,
  `extra_t26_155` json DEFAULT NULL,
  `extra_t26_156` bit(8) DEFAULT NULL,
  `extra_t26_157` decimal(24,7) DEFAULT NULL,
  `extra_t26_158` datetime(6) DEFAULT NULL,
  `extra_t26_159` datetime(4) DEFAULT NULL,
  `extra_t26_160` bigint unsigned DEFAULT NULL,
  `extra_t26_161` smallint DEFAULT NULL,
  `extra_t26_162` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_163` float unsigned DEFAULT NULL,
  `extra_t26_164` double unsigned DEFAULT NULL,
  `extra_t26_165` float unsigned DEFAULT NULL,
  `extra_t26_166` decimal(13,4) DEFAULT NULL,
  `extra_t26_167` bit(59) DEFAULT NULL,
  `extra_t26_168` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t26_169` bigint unsigned DEFAULT NULL,
  `extra_t26_170` set('s0_1','s0_2','s0_3','s0_4','s0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t26_171` date DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t26_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t26_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t26_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t26_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t26_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t26_int_col` (`int_col`),
  KEY `idx_t26_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t26_year_char` (`year_col`,`char_col`),
  KEY `idx_t26_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t26_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t26_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t26_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t26_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t26_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t26_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t26_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t26_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t26_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t26_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t26_year_func` ((year(`datetime_col`))),
  KEY `idx_t26_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t26_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t26_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t26_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t26_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t26_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t26_extra_varbinary_binary` (`varbinary_col`(3),`binary_col`),
  KEY `idx_t26_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t26_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t26_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t26_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t26_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t26_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t26_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t26_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t26_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t26_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t26_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t26_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t26_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t26_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t26_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t26_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t26_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t26_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t26_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t26_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t26_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t26_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t26_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t26_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t26_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t26_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t26_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t26_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t26_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t26_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t26_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t26_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t26_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t26_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE COLUMNS (`tenant_id`)
SUBPARTITION BY LIST COLUMNS (`subpart_id`) (
  PARTITION p0 VALUES LESS THAN (2) (
    SUBPARTITION p0sp0 VALUES IN (1),
    SUBPARTITION p0sp1 VALUES IN (2),
    SUBPARTITION p0sp2 VALUES IN (3),
    SUBPARTITION p0sp3 VALUES IN (4),
    SUBPARTITION p0sp4 VALUES IN (5),
    SUBPARTITION p0sp5 VALUES IN (6),
    SUBPARTITION p0sp6 VALUES IN (7),
    SUBPARTITION p0sp7 VALUES IN (8)
  ),
  PARTITION p1 VALUES LESS THAN (3) (
    SUBPARTITION p1sp0 VALUES IN (1),
    SUBPARTITION p1sp1 VALUES IN (2),
    SUBPARTITION p1sp2 VALUES IN (3),
    SUBPARTITION p1sp3 VALUES IN (4),
    SUBPARTITION p1sp4 VALUES IN (5),
    SUBPARTITION p1sp5 VALUES IN (6),
    SUBPARTITION p1sp6 VALUES IN (7),
    SUBPARTITION p1sp7 VALUES IN (8)
  ),
  PARTITION p2 VALUES LESS THAN (4) (
    SUBPARTITION p2sp0 VALUES IN (1),
    SUBPARTITION p2sp1 VALUES IN (2),
    SUBPARTITION p2sp2 VALUES IN (3),
    SUBPARTITION p2sp3 VALUES IN (4),
    SUBPARTITION p2sp4 VALUES IN (5),
    SUBPARTITION p2sp5 VALUES IN (6),
    SUBPARTITION p2sp6 VALUES IN (7),
    SUBPARTITION p2sp7 VALUES IN (8)
  ),
  PARTITION p3 VALUES LESS THAN (5) (
    SUBPARTITION p3sp0 VALUES IN (1),
    SUBPARTITION p3sp1 VALUES IN (2),
    SUBPARTITION p3sp2 VALUES IN (3),
    SUBPARTITION p3sp3 VALUES IN (4),
    SUBPARTITION p3sp4 VALUES IN (5),
    SUBPARTITION p3sp5 VALUES IN (6),
    SUBPARTITION p3sp6 VALUES IN (7),
    SUBPARTITION p3sp7 VALUES IN (8)
  ),
  PARTITION p4 VALUES LESS THAN (6) (
    SUBPARTITION p4sp0 VALUES IN (1),
    SUBPARTITION p4sp1 VALUES IN (2),
    SUBPARTITION p4sp2 VALUES IN (3),
    SUBPARTITION p4sp3 VALUES IN (4),
    SUBPARTITION p4sp4 VALUES IN (5),
    SUBPARTITION p4sp5 VALUES IN (6),
    SUBPARTITION p4sp6 VALUES IN (7),
    SUBPARTITION p4sp7 VALUES IN (8)
  ),
  PARTITION p5 VALUES LESS THAN (7) (
    SUBPARTITION p5sp0 VALUES IN (1),
    SUBPARTITION p5sp1 VALUES IN (2),
    SUBPARTITION p5sp2 VALUES IN (3),
    SUBPARTITION p5sp3 VALUES IN (4),
    SUBPARTITION p5sp4 VALUES IN (5),
    SUBPARTITION p5sp5 VALUES IN (6),
    SUBPARTITION p5sp6 VALUES IN (7),
    SUBPARTITION p5sp7 VALUES IN (8)
  ),
  PARTITION p6 VALUES LESS THAN (8) (
    SUBPARTITION p6sp0 VALUES IN (1),
    SUBPARTITION p6sp1 VALUES IN (2),
    SUBPARTITION p6sp2 VALUES IN (3),
    SUBPARTITION p6sp3 VALUES IN (4),
    SUBPARTITION p6sp4 VALUES IN (5),
    SUBPARTITION p6sp5 VALUES IN (6),
    SUBPARTITION p6sp6 VALUES IN (7),
    SUBPARTITION p6sp7 VALUES IN (8)
  ),
  PARTITION p7 VALUES LESS THAN (MAXVALUE) (
    SUBPARTITION p7sp0 VALUES IN (1),
    SUBPARTITION p7sp1 VALUES IN (2),
    SUBPARTITION p7sp2 VALUES IN (3),
    SUBPARTITION p7sp3 VALUES IN (4),
    SUBPARTITION p7sp4 VALUES IN (5),
    SUBPARTITION p7sp5 VALUES IN (6),
    SUBPARTITION p7sp6 VALUES IN (7),
    SUBPARTITION p7sp7 VALUES IN (8)
  )
);
SET FOREIGN_KEY_CHECKS=1;
