SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TEMPORARY TABLE IF EXISTS `t3`;
CREATE TEMPORARY TABLE `t3` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(106) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(18,6) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(2) DEFAULT NULL,
  `timestamp_col` timestamp(3) NULL DEFAULT NULL,
  `time_col` time(4) DEFAULT NULL,
  `varchar_col` varchar(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(218) DEFAULT NULL,
  `varbinary_col` varbinary(16) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(3) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(25,7) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t3_000` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_001` bit(3) DEFAULT NULL,
  `extra_t3_002` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_003` bigint DEFAULT NULL,
  `extra_t3_004` date DEFAULT NULL,
  `extra_t3_005` set('s5_1','s5_2','s5_3','s5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_006` double DEFAULT NULL,
  `extra_t3_007` mediumblob,
  `extra_t3_008` binary(20) DEFAULT NULL,
  `extra_t3_009` date DEFAULT NULL,
  `extra_t3_010` int unsigned DEFAULT NULL,
  `extra_t3_011` bit(64) DEFAULT NULL,
  `extra_t3_012` time DEFAULT NULL,
  `extra_t3_013` mediumblob,
  `extra_t3_014` bigint unsigned DEFAULT NULL,
  `extra_t3_015` time(2) DEFAULT NULL,
  `extra_t3_016` decimal(9,4) DEFAULT NULL,
  `extra_t3_017` enum('e7_1','e7_2','e7_3','e7_4','e7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_018` bit(19) DEFAULT NULL,
  `extra_t3_019` set('s9_1','s9_2','s9_3','s9_4','s9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_020` enum('e0_1','e0_2','e0_3','e0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_021` int unsigned DEFAULT NULL,
  `extra_t3_022` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_023` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_024` float unsigned DEFAULT NULL,
  `extra_t3_025` json DEFAULT NULL,
  `extra_t3_026` bit(29) DEFAULT NULL,
  `extra_t3_027` time DEFAULT NULL,
  `extra_t3_028` float DEFAULT NULL,
  `extra_t3_029` bigint unsigned DEFAULT NULL,
  `extra_t3_030` smallint unsigned DEFAULT NULL,
  `extra_t3_031` mediumint unsigned DEFAULT NULL,
  `extra_t3_032` mediumblob,
  `extra_t3_033` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_034` decimal(11,3) DEFAULT NULL,
  `extra_t3_035` enum('e5_1','e5_2','e5_3','e5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_036` smallint DEFAULT NULL,
  `extra_t3_037` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_038` double unsigned DEFAULT NULL,
  `extra_t3_039` tinyint unsigned DEFAULT NULL,
  `extra_t3_040` tinyblob,
  `extra_t3_041` longblob,
  `extra_t3_042` json DEFAULT NULL,
  `extra_t3_043` enum('e3_1','e3_2','e3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_044` smallint unsigned DEFAULT NULL,
  `extra_t3_045` json DEFAULT NULL,
  `extra_t3_046` enum('e6_1','e6_2','e6_3','e6_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_047` double unsigned DEFAULT NULL,
  `extra_t3_048` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_049` tinyblob,
  `extra_t3_050` decimal(8,1) DEFAULT NULL,
  `extra_t3_051` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_052` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_053` set('s3_1','s3_2','s3_3','s3_4','s3_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_054` json DEFAULT NULL,
  `extra_t3_055` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_056` timestamp(5) DEFAULT NULL,
  `extra_t3_057` year DEFAULT NULL,
  `extra_t3_058` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_059` json DEFAULT NULL,
  `extra_t3_060` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_061` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_062` json DEFAULT NULL,
  `extra_t3_063` bit(25) DEFAULT NULL,
  `extra_t3_064` date DEFAULT NULL,
  `extra_t3_065` timestamp DEFAULT NULL,
  `extra_t3_066` varbinary(8) DEFAULT NULL,
  `extra_t3_067` decimal(13,4) DEFAULT NULL,
  `extra_t3_068` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_069` enum('e9_1','e9_2','e9_3','e9_4','e9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_070` json DEFAULT NULL,
  `extra_t3_071` timestamp(5) DEFAULT NULL,
  `extra_t3_072` json DEFAULT NULL,
  `extra_t3_073` bigint unsigned DEFAULT NULL,
  `extra_t3_074` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_075` json DEFAULT NULL,
  `extra_t3_076` decimal(20,7) DEFAULT NULL,
  `extra_t3_077` set('s7_1','s7_2','s7_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_078` decimal(24,8) DEFAULT NULL,
  `extra_t3_079` timestamp(6) DEFAULT NULL,
  `extra_t3_080` bit(8) DEFAULT NULL,
  `extra_t3_081` decimal(11,2) DEFAULT NULL,
  `extra_t3_082` mediumint DEFAULT NULL,
  `extra_t3_083` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_084` time(2) DEFAULT NULL,
  `extra_t3_085` decimal(16,8) DEFAULT NULL,
  `extra_t3_086` json DEFAULT NULL,
  `extra_t3_087` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_088` mediumint unsigned DEFAULT NULL,
  `extra_t3_089` blob,
  `extra_t3_090` json DEFAULT NULL,
  `extra_t3_091` date DEFAULT NULL,
  `extra_t3_092` varbinary(5) DEFAULT NULL,
  `extra_t3_093` longblob,
  `extra_t3_094` json DEFAULT NULL,
  `extra_t3_095` double unsigned DEFAULT NULL,
  `extra_t3_096` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_097` bit(54) DEFAULT NULL,
  `extra_t3_098` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_099` datetime DEFAULT NULL,
  `extra_t3_100` json DEFAULT NULL,
  `extra_t3_101` int DEFAULT NULL,
  `extra_t3_102` varbinary(18) DEFAULT NULL,
  `extra_t3_103` double unsigned DEFAULT NULL,
  `extra_t3_104` timestamp(6) DEFAULT NULL,
  `extra_t3_105` float unsigned DEFAULT NULL,
  `extra_t3_106` bit(33) DEFAULT NULL,
  `extra_t3_107` json DEFAULT NULL,
  `extra_t3_108` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_109` enum('e9_1','e9_2','e9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_110` binary(22) DEFAULT NULL,
  `extra_t3_111` varchar(13) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_112` datetime DEFAULT NULL,
  `extra_t3_113` datetime(1) DEFAULT NULL,
  `extra_t3_114` double unsigned DEFAULT NULL,
  `extra_t3_115` bit(57) DEFAULT NULL,
  `extra_t3_116` json DEFAULT NULL,
  `extra_t3_117` date DEFAULT NULL,
  `extra_t3_118` varbinary(3) DEFAULT NULL,
  `extra_t3_119` json DEFAULT NULL,
  `extra_t3_120` varbinary(26) DEFAULT NULL,
  `extra_t3_121` json DEFAULT NULL,
  `extra_t3_122` bit(17) DEFAULT NULL,
  `extra_t3_123` tinyint unsigned DEFAULT NULL,
  `extra_t3_124` bit(7) DEFAULT NULL,
  `extra_t3_125` decimal(21,7) DEFAULT NULL,
  `extra_t3_126` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_127` longblob,
  `extra_t3_128` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_129` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_130` decimal(17,5) DEFAULT NULL,
  `extra_t3_131` json DEFAULT NULL,
  `extra_t3_132` tinyint DEFAULT NULL,
  `extra_t3_133` enum('e3_1','e3_2','e3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_134` double DEFAULT NULL,
  `extra_t3_135` time(5) DEFAULT NULL,
  `extra_t3_136` float DEFAULT NULL,
  `extra_t3_137` decimal(21,6) DEFAULT NULL,
  `extra_t3_138` bigint DEFAULT NULL,
  `extra_t3_139` json DEFAULT NULL,
  `extra_t3_140` bit(26) DEFAULT NULL,
  `extra_t3_141` bigint DEFAULT NULL,
  `extra_t3_142` decimal(19,7) DEFAULT NULL,
  `extra_t3_143` bit(44) DEFAULT NULL,
  `extra_t3_144` blob,
  `extra_t3_145` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_146` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_147` varbinary(13) DEFAULT NULL,
  `extra_t3_148` enum('e8_1','e8_2','e8_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_149` datetime(5) DEFAULT NULL,
  `extra_t3_150` json DEFAULT NULL,
  `extra_t3_151` json DEFAULT NULL,
  `extra_t3_152` int DEFAULT NULL,
  `extra_t3_153` longblob,
  `extra_t3_154` double unsigned DEFAULT NULL,
  `extra_t3_155` json DEFAULT NULL,
  `extra_t3_156` tinyblob,
  `extra_t3_157` float unsigned DEFAULT NULL,
  `extra_t3_158` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_159` enum('e9_1','e9_2','e9_3','e9_4','e9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_160` json DEFAULT NULL,
  `extra_t3_161` bigint DEFAULT NULL,
  `extra_t3_162` longblob,
  `extra_t3_163` float DEFAULT NULL,
  `extra_t3_164` json DEFAULT NULL,
  `extra_t3_165` time(1) DEFAULT NULL,
  `extra_t3_166` decimal(14,0) DEFAULT NULL,
  `extra_t3_167` decimal(6,1) DEFAULT NULL,
  `extra_t3_168` decimal(10,1) DEFAULT NULL,
  `extra_t3_169` datetime(5) DEFAULT NULL,
  `extra_t3_170` tinyblob,
  `extra_t3_171` time(6) DEFAULT NULL,
  `extra_t3_172` decimal(14,1) DEFAULT NULL,
  `extra_t3_173` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_174` json DEFAULT NULL,
  `extra_t3_175` decimal(20,2) DEFAULT NULL,
  `extra_t3_176` json DEFAULT NULL,
  `extra_t3_177` set('s7_1','s7_2','s7_3','s7_4','s7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_178` enum('e8_1','e8_2','e8_3','e8_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_179` double unsigned DEFAULT NULL,
  `extra_t3_180` float DEFAULT NULL,
  `extra_t3_181` bit(21) DEFAULT NULL,
  `extra_t3_182` tinyint unsigned DEFAULT NULL,
  `extra_t3_183` bit(54) DEFAULT NULL,
  `extra_t3_184` bit(35) DEFAULT NULL,
  `extra_t3_185` json DEFAULT NULL,
  `extra_t3_186` time DEFAULT NULL,
  `extra_t3_187` timestamp(3) DEFAULT NULL,
  `extra_t3_188` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_189` char(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_190` bit(51) DEFAULT NULL,
  `extra_t3_191` int unsigned DEFAULT NULL,
  `extra_t3_192` year DEFAULT NULL,
  `extra_t3_193` json DEFAULT NULL,
  `extra_t3_194` enum('e4_1','e4_2','e4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_195` double unsigned DEFAULT NULL,
  `extra_t3_196` decimal(24,6) DEFAULT NULL,
  `extra_t3_197` mediumint DEFAULT NULL,
  `extra_t3_198` json DEFAULT NULL,
  `extra_t3_199` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_200` json DEFAULT NULL,
  `extra_t3_201` tinyint DEFAULT NULL,
  `extra_t3_202` json DEFAULT NULL,
  `extra_t3_203` date DEFAULT NULL,
  `extra_t3_204` bit(6) DEFAULT NULL,
  `extra_t3_205` double DEFAULT NULL,
  `extra_t3_206` json DEFAULT NULL,
  `extra_t3_207` double unsigned DEFAULT NULL,
  `extra_t3_208` decimal(7,6) DEFAULT NULL,
  `extra_t3_209` enum('e9_1','e9_2','e9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_210` json DEFAULT NULL,
  `extra_t3_211` set('s1_1','s1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_212` bit(48) DEFAULT NULL,
  `extra_t3_213` tinyint DEFAULT NULL,
  `extra_t3_214` bit(37) DEFAULT NULL,
  `extra_t3_215` bit(31) DEFAULT NULL,
  `extra_t3_216` tinyint unsigned DEFAULT NULL,
  `extra_t3_217` mediumblob,
  `extra_t3_218` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_219` bigint DEFAULT NULL,
  `extra_t3_220` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_221` json DEFAULT NULL,
  `extra_t3_222` binary(28) DEFAULT NULL,
  `extra_t3_223` mediumint DEFAULT NULL,
  `extra_t3_224` smallint unsigned DEFAULT NULL,
  `extra_t3_225` bit(38) DEFAULT NULL,
  `extra_t3_226` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_227` bit(53) DEFAULT NULL,
  `extra_t3_228` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_229` time(1) DEFAULT NULL,
  `extra_t3_230` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_231` smallint unsigned DEFAULT NULL,
  `extra_t3_232` longblob,
  `extra_t3_233` bit(63) DEFAULT NULL,
  `extra_t3_234` timestamp(4) DEFAULT NULL,
  `extra_t3_235` double DEFAULT NULL,
  `extra_t3_236` float DEFAULT NULL,
  `extra_t3_237` json DEFAULT NULL,
  `extra_t3_238` float unsigned DEFAULT NULL,
  `extra_t3_239` json DEFAULT NULL,
  `extra_t3_240` time(2) DEFAULT NULL,
  `extra_t3_241` bit(38) DEFAULT NULL,
  `extra_t3_242` int unsigned DEFAULT NULL,
  `extra_t3_243` bit(11) DEFAULT NULL,
  `extra_t3_244` time(4) DEFAULT NULL,
  `extra_t3_245` int unsigned DEFAULT NULL,
  `extra_t3_246` json DEFAULT NULL,
  `extra_t3_247` time DEFAULT NULL,
  `extra_t3_248` tinyblob,
  `extra_t3_249` bigint DEFAULT NULL,
  `extra_t3_250` float unsigned DEFAULT NULL,
  `extra_t3_251` enum('e1_1','e1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_252` timestamp(2) DEFAULT NULL,
  `extra_t3_253` int DEFAULT NULL,
  `extra_t3_254` smallint unsigned DEFAULT NULL,
  `extra_t3_255` longblob,
  `extra_t3_256` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_257` date DEFAULT NULL,
  `extra_t3_258` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_259` json DEFAULT NULL,
  `extra_t3_260` bit(32) DEFAULT NULL,
  `extra_t3_261` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_262` json DEFAULT NULL,
  `extra_t3_263` blob,
  `extra_t3_264` enum('e4_1','e4_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_265` double DEFAULT NULL,
  `extra_t3_266` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_267` date DEFAULT NULL,
  `extra_t3_268` decimal(17,1) DEFAULT NULL,
  `extra_t3_269` tinyblob,
  `extra_t3_270` double unsigned DEFAULT NULL,
  `extra_t3_271` time(5) DEFAULT NULL,
  `extra_t3_272` bit(24) DEFAULT NULL,
  `extra_t3_273` bit(19) DEFAULT NULL,
  `extra_t3_274` json DEFAULT NULL,
  `extra_t3_275` decimal(16,3) DEFAULT NULL,
  `extra_t3_276` smallint unsigned DEFAULT NULL,
  `extra_t3_277` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_278` decimal(14,5) DEFAULT NULL,
  `extra_t3_279` double unsigned DEFAULT NULL,
  `extra_t3_280` decimal(9,5) DEFAULT NULL,
  `extra_t3_281` year DEFAULT NULL,
  `extra_t3_282` year DEFAULT NULL,
  `extra_t3_283` time DEFAULT NULL,
  `extra_t3_284` tinyint DEFAULT NULL,
  `extra_t3_285` decimal(10,0) DEFAULT NULL,
  `extra_t3_286` json DEFAULT NULL,
  `extra_t3_287` enum('e7_1','e7_2','e7_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_288` float unsigned DEFAULT NULL,
  `extra_t3_289` tinyint DEFAULT NULL,
  `extra_t3_290` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_291` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_292` bit(19) DEFAULT NULL,
  `extra_t3_293` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t3_294` char(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_295` decimal(16,0) DEFAULT NULL,
  `extra_t3_296` int unsigned DEFAULT NULL,
  `extra_t3_297` decimal(11,3) DEFAULT NULL,
  `extra_t3_298` bit(13) DEFAULT NULL,
  `extra_t3_299` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t3_300` longblob,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t3_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t3_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t3_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t3_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t3_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t3_int_col` (`int_col`),
  UNIQUE KEY `idx_t3_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t3_year_char` (`year_col`,`char_col`),
  UNIQUE KEY `idx_t3_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  UNIQUE KEY `idx_t3_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  UNIQUE KEY `idx_t3_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t3_varchar_prefix` (`varchar_col`(63)),
  KEY `idx_t3_binary_combo` (`binary_col`,`varbinary_col`),
  UNIQUE KEY `idx_t3_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  UNIQUE KEY `idx_t3_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t3_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  UNIQUE KEY `idx_t3_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t3_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t3_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t3_year_func` ((year(`datetime_col`))),
  UNIQUE KEY `idx_t3_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  UNIQUE KEY `idx_t3_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  UNIQUE KEY `idx_t3_extra_mediumblob` (`mediumblob_col`(16)),
  UNIQUE KEY `idx_t3_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  UNIQUE KEY `idx_t3_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t3_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t3_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  UNIQUE KEY `idx_t3_extra_date_days` ((to_days(`date_col`))),
  UNIQUE KEY `idx_t3_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t3_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t3_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  UNIQUE KEY `idx_t3_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  UNIQUE KEY `idx_t3_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t3_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  UNIQUE KEY `idx_t3_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t3_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t3_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  UNIQUE KEY `idx_t3_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t3_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t3_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t3_extra_varbinary_binary` (`varbinary_col`(16),`binary_col`),
  UNIQUE KEY `idx_t3_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  UNIQUE KEY `idx_t3_extra_time_timestamp` (`time_col`,`timestamp_col`),
  UNIQUE KEY `idx_t3_extra_decimal_round` ((round(`decimal_col`,2))),
  UNIQUE KEY `idx_t3_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t3_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t3_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t3_extra_abs_smallint` ((abs(`smallint_col`))),
  UNIQUE KEY `idx_t3_extra_float_floor` ((floor(`float_col`))),
  UNIQUE KEY `idx_t3_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  UNIQUE KEY `idx_t3_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  UNIQUE KEY `idx_t3_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t3_extra_dayofweek` ((dayofweek(`date_col`))),
  UNIQUE KEY `idx_t3_extra_tenant_int` (`tenant_id`,`int_col`),
  UNIQUE KEY `idx_t3_extra_longblob` (`longblob_col`(16)),
  UNIQUE KEY `idx_t3_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t3_extra_month_datetime` ((month(`datetime_col`))),
  UNIQUE KEY `idx_t3_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t3_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `idx_t3_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t3_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
