SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TEMPORARY TABLE IF EXISTS `t4`;
CREATE TEMPORARY TABLE `t4` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(206) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(20,2) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(4) DEFAULT NULL,
  `timestamp_col` timestamp(3) NULL DEFAULT NULL,
  `time_col` time(1) DEFAULT NULL,
  `varchar_col` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(140) DEFAULT NULL,
  `varbinary_col` varbinary(129) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(36) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(21,8) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t4_000` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_001` int DEFAULT NULL,
  `extra_t4_002` json DEFAULT NULL,
  `extra_t4_003` datetime DEFAULT NULL,
  `extra_t4_004` datetime(5) DEFAULT NULL,
  `extra_t4_005` date DEFAULT NULL,
  `extra_t4_006` enum('e6_1','e6_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_007` json DEFAULT NULL,
  `extra_t4_008` enum('e8_1','e8_2','e8_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_009` enum('e9_1','e9_2','e9_3','e9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_010` tinyblob,
  `extra_t4_011` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_012` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_013` set('s3_1','s3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_014` double DEFAULT NULL,
  `extra_t4_015` set('s5_1','s5_2','s5_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_016` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_017` smallint unsigned DEFAULT NULL,
  `extra_t4_018` decimal(24,7) DEFAULT NULL,
  `extra_t4_019` float DEFAULT NULL,
  `extra_t4_020` date DEFAULT NULL,
  `extra_t4_021` set('s1_1','s1_2','s1_3','s1_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_022` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_023` time(6) DEFAULT NULL,
  `extra_t4_024` bit(39) DEFAULT NULL,
  `extra_t4_025` bit(38) DEFAULT NULL,
  `extra_t4_026` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_027` tinyint DEFAULT NULL,
  `extra_t4_028` json DEFAULT NULL,
  `extra_t4_029` mediumint DEFAULT NULL,
  `extra_t4_030` varbinary(22) DEFAULT NULL,
  `extra_t4_031` enum('e1_1','e1_2','e1_3','e1_4','e1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_032` bigint unsigned DEFAULT NULL,
  `extra_t4_033` decimal(6,1) DEFAULT NULL,
  `extra_t4_034` bit(10) DEFAULT NULL,
  `extra_t4_035` json DEFAULT NULL,
  `extra_t4_036` blob,
  `extra_t4_037` json DEFAULT NULL,
  `extra_t4_038` timestamp(2) DEFAULT NULL,
  `extra_t4_039` float DEFAULT NULL,
  `extra_t4_040` decimal(23,6) DEFAULT NULL,
  `extra_t4_041` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_042` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_043` double unsigned DEFAULT NULL,
  `extra_t4_044` json DEFAULT NULL,
  `extra_t4_045` decimal(11,0) DEFAULT NULL,
  `extra_t4_046` varbinary(20) DEFAULT NULL,
  `extra_t4_047` decimal(25,7) DEFAULT NULL,
  `extra_t4_048` bigint DEFAULT NULL,
  `extra_t4_049` enum('e9_1','e9_2','e9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_050` json DEFAULT NULL,
  `extra_t4_051` double unsigned DEFAULT NULL,
  `extra_t4_052` decimal(23,6) DEFAULT NULL,
  `extra_t4_053` bit(35) DEFAULT NULL,
  `extra_t4_054` datetime(6) DEFAULT NULL,
  `extra_t4_055` time(1) DEFAULT NULL,
  `extra_t4_056` date DEFAULT NULL,
  `extra_t4_057` binary(24) DEFAULT NULL,
  `extra_t4_058` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_059` double DEFAULT NULL,
  `extra_t4_060` bit(58) DEFAULT NULL,
  `extra_t4_061` json DEFAULT NULL,
  `extra_t4_062` decimal(10,5) DEFAULT NULL,
  `extra_t4_063` enum('e3_1','e3_2','e3_3','e3_4','e3_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_064` bit(47) DEFAULT NULL,
  `extra_t4_065` float unsigned DEFAULT NULL,
  `extra_t4_066` double unsigned DEFAULT NULL,
  `extra_t4_067` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_068` json DEFAULT NULL,
  `extra_t4_069` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_070` decimal(6,0) DEFAULT NULL,
  `extra_t4_071` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_072` double DEFAULT NULL,
  `extra_t4_073` decimal(17,7) DEFAULT NULL,
  `extra_t4_074` year DEFAULT NULL,
  `extra_t4_075` decimal(17,5) DEFAULT NULL,
  `extra_t4_076` int DEFAULT NULL,
  `extra_t4_077` float unsigned DEFAULT NULL,
  `extra_t4_078` tinyblob,
  `extra_t4_079` json DEFAULT NULL,
  `extra_t4_080` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_081` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_082` int unsigned DEFAULT NULL,
  `extra_t4_083` float unsigned DEFAULT NULL,
  `extra_t4_084` double unsigned DEFAULT NULL,
  `extra_t4_085` int DEFAULT NULL,
  `extra_t4_086` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_087` bigint DEFAULT NULL,
  `extra_t4_088` json DEFAULT NULL,
  `extra_t4_089` float DEFAULT NULL,
  `extra_t4_090` longblob,
  `extra_t4_091` bit(8) DEFAULT NULL,
  `extra_t4_092` bit(6) DEFAULT NULL,
  `extra_t4_093` mediumblob,
  `extra_t4_094` tinyblob,
  `extra_t4_095` bigint unsigned DEFAULT NULL,
  `extra_t4_096` float DEFAULT NULL,
  `extra_t4_097` decimal(18,1) DEFAULT NULL,
  `extra_t4_098` decimal(11,6) DEFAULT NULL,
  `extra_t4_099` set('s9_1','s9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_100` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_101` json DEFAULT NULL,
  `extra_t4_102` json DEFAULT NULL,
  `extra_t4_103` float unsigned DEFAULT NULL,
  `extra_t4_104` binary(20) DEFAULT NULL,
  `extra_t4_105` float DEFAULT NULL,
  `extra_t4_106` float unsigned DEFAULT NULL,
  `extra_t4_107` datetime(3) DEFAULT NULL,
  `extra_t4_108` bit(32) DEFAULT NULL,
  `extra_t4_109` decimal(11,2) DEFAULT NULL,
  `extra_t4_110` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_111` decimal(10,8) DEFAULT NULL,
  `extra_t4_112` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_113` tinyblob,
  `extra_t4_114` mediumblob,
  `extra_t4_115` decimal(11,0) DEFAULT NULL,
  `extra_t4_116` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_117` decimal(13,8) DEFAULT NULL,
  `extra_t4_118` int unsigned DEFAULT NULL,
  `extra_t4_119` year DEFAULT NULL,
  `extra_t4_120` mediumint DEFAULT NULL,
  `extra_t4_121` longblob,
  `extra_t4_122` float DEFAULT NULL,
  `extra_t4_123` longblob,
  `extra_t4_124` bit(3) DEFAULT NULL,
  `extra_t4_125` tinyblob,
  `extra_t4_126` mediumint unsigned DEFAULT NULL,
  `extra_t4_127` decimal(15,4) DEFAULT NULL,
  `extra_t4_128` blob,
  `extra_t4_129` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_130` timestamp DEFAULT NULL,
  `extra_t4_131` bit(48) DEFAULT NULL,
  `extra_t4_132` decimal(22,8) DEFAULT NULL,
  `extra_t4_133` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_134` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_135` int DEFAULT NULL,
  `extra_t4_136` smallint unsigned DEFAULT NULL,
  `extra_t4_137` decimal(12,3) DEFAULT NULL,
  `extra_t4_138` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_139` time(4) DEFAULT NULL,
  `extra_t4_140` date DEFAULT NULL,
  `extra_t4_141` double DEFAULT NULL,
  `extra_t4_142` tinyint unsigned DEFAULT NULL,
  `extra_t4_143` decimal(10,2) DEFAULT NULL,
  `extra_t4_144` decimal(11,8) DEFAULT NULL,
  `extra_t4_145` set('s5_1','s5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_146` timestamp DEFAULT NULL,
  `extra_t4_147` set('s7_1','s7_2','s7_3','s7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_148` float DEFAULT NULL,
  `extra_t4_149` int DEFAULT NULL,
  `extra_t4_150` longblob,
  `extra_t4_151` bigint unsigned DEFAULT NULL,
  `extra_t4_152` json DEFAULT NULL,
  `extra_t4_153` decimal(19,4) DEFAULT NULL,
  `extra_t4_154` smallint unsigned DEFAULT NULL,
  `extra_t4_155` enum('e5_1','e5_2','e5_3','e5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_156` bit(15) DEFAULT NULL,
  `extra_t4_157` json DEFAULT NULL,
  `extra_t4_158` float unsigned DEFAULT NULL,
  `extra_t4_159` tinyblob,
  `extra_t4_160` bit(11) DEFAULT NULL,
  `extra_t4_161` datetime(2) DEFAULT NULL,
  `extra_t4_162` set('s2_1','s2_2','s2_3','s2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_163` decimal(14,5) DEFAULT NULL,
  `extra_t4_164` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_165` longblob,
  `extra_t4_166` double unsigned DEFAULT NULL,
  `extra_t4_167` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_168` varbinary(18) DEFAULT NULL,
  `extra_t4_169` decimal(6,3) DEFAULT NULL,
  `extra_t4_170` enum('e0_1','e0_2','e0_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_171` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_172` double DEFAULT NULL,
  `extra_t4_173` date DEFAULT NULL,
  `extra_t4_174` bigint DEFAULT NULL,
  `extra_t4_175` bit(57) DEFAULT NULL,
  `extra_t4_176` json DEFAULT NULL,
  `extra_t4_177` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_178` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_179` int DEFAULT NULL,
  `extra_t4_180` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_181` time(4) DEFAULT NULL,
  `extra_t4_182` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_183` smallint unsigned DEFAULT NULL,
  `extra_t4_184` json DEFAULT NULL,
  `extra_t4_185` json DEFAULT NULL,
  `extra_t4_186` mediumblob,
  `extra_t4_187` blob,
  `extra_t4_188` bit(11) DEFAULT NULL,
  `extra_t4_189` double unsigned DEFAULT NULL,
  `extra_t4_190` bigint unsigned DEFAULT NULL,
  `extra_t4_191` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_192` double unsigned DEFAULT NULL,
  `extra_t4_193` json DEFAULT NULL,
  `extra_t4_194` double unsigned DEFAULT NULL,
  `extra_t4_195` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_196` varbinary(5) DEFAULT NULL,
  `extra_t4_197` decimal(12,1) DEFAULT NULL,
  `extra_t4_198` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t4_199` varbinary(14) DEFAULT NULL,
  `extra_t4_200` datetime(5) DEFAULT NULL,
  `extra_t4_201` bit(46) DEFAULT NULL,
  `extra_t4_202` float unsigned DEFAULT NULL,
  `extra_t4_203` decimal(10,2) DEFAULT NULL,
  `extra_t4_204` bit(27) DEFAULT NULL,
  `extra_t4_205` enum('e5_1','e5_2','e5_3','e5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_206` year DEFAULT NULL,
  `extra_t4_207` enum('e7_1','e7_2','e7_3','e7_4','e7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t4_208` decimal(21,6) DEFAULT NULL,
  `extra_t4_209` time(2) DEFAULT NULL,
  `extra_t4_210` longblob,
  `extra_t4_211` float DEFAULT NULL,
  `extra_t4_212` mediumblob,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t4_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t4_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t4_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t4_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t4_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t4_int_col` (`int_col`),
  UNIQUE KEY `idx_t4_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t4_year_char` (`year_col`,`char_col`),
  UNIQUE KEY `idx_t4_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  UNIQUE KEY `idx_t4_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  UNIQUE KEY `idx_t4_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t4_varchar_prefix` (`varchar_col`(45)),
  KEY `idx_t4_binary_combo` (`binary_col`,`varbinary_col`),
  UNIQUE KEY `idx_t4_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  UNIQUE KEY `idx_t4_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t4_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  UNIQUE KEY `idx_t4_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t4_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t4_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t4_year_func` ((year(`datetime_col`))),
  UNIQUE KEY `idx_t4_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  UNIQUE KEY `idx_t4_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  UNIQUE KEY `idx_t4_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  UNIQUE KEY `idx_t4_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  UNIQUE KEY `idx_t4_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  UNIQUE KEY `idx_t4_extra_decimal_desc` (`decimal_col` DESC),
  UNIQUE KEY `idx_t4_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t4_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  UNIQUE KEY `idx_t4_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  UNIQUE KEY `idx_t4_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t4_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t4_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t4_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t4_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t4_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t4_extra_mediumblob` (`mediumblob_col`(16)),
  UNIQUE KEY `idx_t4_extra_date_days` ((to_days(`date_col`))),
  UNIQUE KEY `idx_t4_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  UNIQUE KEY `idx_t4_extra_float_floor` ((floor(`float_col`))),
  UNIQUE KEY `idx_t4_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t4_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t4_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  UNIQUE KEY `idx_t4_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t4_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t4_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  UNIQUE KEY `idx_t4_extra_float_double_desc` (`float_col`,`double_col` DESC),
  UNIQUE KEY `idx_t4_extra_double_ceiling` ((ceiling(`double_col`))),
  UNIQUE KEY `idx_t4_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  UNIQUE KEY `idx_t4_extra_abs_smallint` ((abs(`smallint_col`))),
  UNIQUE KEY `idx_t4_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t4_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t4_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t4_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t4_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  UNIQUE KEY `idx_t4_extra_tenant_int` (`tenant_id`,`int_col`),
  UNIQUE KEY `idx_t4_extra_time_timestamp` (`time_col`,`timestamp_col`),
  UNIQUE KEY `idx_t4_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  UNIQUE KEY `idx_t4_extra_longblob` (`longblob_col`(16)),
  UNIQUE KEY `idx_t4_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t4_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t4_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
