SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TEMPORARY TABLE IF EXISTS `t4`;
CREATE TEMPORARY TABLE `t4` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(4) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(25,5) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(6) DEFAULT NULL,
  `timestamp_col` timestamp NULL DEFAULT NULL,
  `time_col` time DEFAULT NULL,
  `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(1) DEFAULT NULL,
  `varbinary_col` varbinary(255) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(8) DEFAULT b'10011001',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(10,0) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t4_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t4_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  UNIQUE KEY `uk_t4_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t4_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t4_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t4_int_col` (`int_col`),
  UNIQUE KEY `idx_t4_bigint_desc` (`bigint_col` DESC),
  UNIQUE KEY `idx_t4_year_char` (`year_col`,`char_col`),
  UNIQUE KEY `idx_t4_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  UNIQUE KEY `idx_t4_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  UNIQUE KEY `idx_t4_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  UNIQUE KEY `idx_t4_varchar_prefix` (`varchar_col`(64)),
  UNIQUE KEY `idx_t4_binary_combo` (`binary_col`,`varbinary_col`),
  UNIQUE KEY `idx_t4_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  UNIQUE KEY `idx_t4_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t4_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  UNIQUE KEY `idx_t4_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t4_bool_invisible` (`bool_col`) INVISIBLE,
  UNIQUE KEY `idx_t4_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t4_year_func` ((year(`datetime_col`))),
  UNIQUE KEY `idx_t4_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  UNIQUE KEY `idx_t4_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  UNIQUE KEY `idx_t4_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  UNIQUE KEY `idx_t4_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  UNIQUE KEY `idx_t4_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  UNIQUE KEY `idx_t4_extra_decimal_desc` (`decimal_col` DESC),
  UNIQUE KEY `idx_t4_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t4_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  UNIQUE KEY `idx_t4_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  UNIQUE KEY `idx_t4_extra_subpart_big` (`subpart_id`,`bigint_col`),
  UNIQUE KEY `idx_t4_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  UNIQUE KEY `idx_t4_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  UNIQUE KEY `idx_t4_extra_text_set` (`text_col`(12),`set_col`),
  UNIQUE KEY `idx_t4_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t4_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t4_extra_mediumblob` (`mediumblob_col`(16)),
  UNIQUE KEY `idx_t4_extra_date_days` ((to_days(`date_col`))),
  UNIQUE KEY `idx_t4_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  UNIQUE KEY `idx_t4_extra_float_floor` ((floor(`float_col`))),
  UNIQUE KEY `idx_t4_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  UNIQUE KEY `idx_t4_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t4_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  UNIQUE KEY `idx_t4_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t4_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t4_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  UNIQUE KEY `idx_t4_extra_float_double_desc` (`float_col`,`double_col` DESC),
  UNIQUE KEY `idx_t4_extra_double_ceiling` ((ceiling(`double_col`))),
  UNIQUE KEY `idx_t4_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  UNIQUE KEY `idx_t4_extra_abs_smallint` ((abs(`smallint_col`))),
  UNIQUE KEY `idx_t4_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t4_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t4_extra_month_datetime` ((month(`datetime_col`))),
  UNIQUE KEY `idx_t4_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t4_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  UNIQUE KEY `idx_t4_extra_tenant_int` (`tenant_id`,`int_col`),
  UNIQUE KEY `idx_t4_extra_time_timestamp` (`time_col`,`timestamp_col`),
  UNIQUE KEY `idx_t4_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  UNIQUE KEY `idx_t4_extra_longblob` (`longblob_col`(16)),
  UNIQUE KEY `idx_t4_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t4_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t4_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
