SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t46`;
CREATE TABLE `t46` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(148) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint DEFAULT NULL,
  `decimal_col` decimal(29,9) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(6) DEFAULT NULL,
  `timestamp_col` timestamp(2) NULL DEFAULT NULL,
  `time_col` time DEFAULT NULL,
  `varchar_col` varchar(225) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(243) DEFAULT NULL,
  `varbinary_col` varbinary(220) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(59) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(20,0) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t46_000` json DEFAULT NULL,
  `extra_t46_001` bit(3) DEFAULT NULL,
  `extra_t46_002` json DEFAULT NULL,
  `extra_t46_003` bigint unsigned DEFAULT NULL,
  `extra_t46_004` mediumint unsigned DEFAULT NULL,
  `extra_t46_005` set('s5_1','s5_2','s5_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_006` decimal(16,7) DEFAULT NULL,
  `extra_t46_007` bit(34) DEFAULT NULL,
  `extra_t46_008` decimal(6,0) DEFAULT NULL,
  `extra_t46_009` decimal(24,8) DEFAULT NULL,
  `extra_t46_010` bigint DEFAULT NULL,
  `extra_t46_011` bigint DEFAULT NULL,
  `extra_t46_012` smallint DEFAULT NULL,
  `extra_t46_013` tinyint DEFAULT NULL,
  `extra_t46_014` json DEFAULT NULL,
  `extra_t46_015` int unsigned DEFAULT NULL,
  `extra_t46_016` bit(59) DEFAULT NULL,
  `extra_t46_017` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_018` binary(7) DEFAULT NULL,
  `extra_t46_019` json DEFAULT NULL,
  `extra_t46_020` set('s0_1','s0_2','s0_3','s0_4','s0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_021` decimal(22,8) DEFAULT NULL,
  `extra_t46_022` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_023` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_024` bit(33) DEFAULT NULL,
  `extra_t46_025` datetime DEFAULT NULL,
  `extra_t46_026` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_027` timestamp(1) DEFAULT NULL,
  `extra_t46_028` year DEFAULT NULL,
  `extra_t46_029` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_030` date DEFAULT NULL,
  `extra_t46_031` set('s1_1','s1_2','s1_3','s1_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_032` decimal(17,0) DEFAULT NULL,
  `extra_t46_033` longblob,
  `extra_t46_034` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_035` smallint DEFAULT NULL,
  `extra_t46_036` bit(49) DEFAULT NULL,
  `extra_t46_037` time(6) DEFAULT NULL,
  `extra_t46_038` int DEFAULT NULL,
  `extra_t46_039` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_040` decimal(16,2) DEFAULT NULL,
  `extra_t46_041` float unsigned DEFAULT NULL,
  `extra_t46_042` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_043` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_044` decimal(26,8) DEFAULT NULL,
  `extra_t46_045` longblob,
  `extra_t46_046` mediumblob,
  `extra_t46_047` decimal(10,2) DEFAULT NULL,
  `extra_t46_048` blob,
  `extra_t46_049` double unsigned DEFAULT NULL,
  `extra_t46_050` double unsigned DEFAULT NULL,
  `extra_t46_051` json DEFAULT NULL,
  `extra_t46_052` json DEFAULT NULL,
  `extra_t46_053` bit(11) DEFAULT NULL,
  `extra_t46_054` json DEFAULT NULL,
  `extra_t46_055` decimal(11,2) DEFAULT NULL,
  `extra_t46_056` json DEFAULT NULL,
  `extra_t46_057` time(6) DEFAULT NULL,
  `extra_t46_058` year DEFAULT NULL,
  `extra_t46_059` datetime(3) DEFAULT NULL,
  `extra_t46_060` year DEFAULT NULL,
  `extra_t46_061` set('s1_1','s1_2','s1_3','s1_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_062` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_063` json DEFAULT NULL,
  `extra_t46_064` bigint unsigned DEFAULT NULL,
  `extra_t46_065` time(1) DEFAULT NULL,
  `extra_t46_066` decimal(12,7) DEFAULT NULL,
  `extra_t46_067` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_068` float unsigned DEFAULT NULL,
  `extra_t46_069` longblob,
  `extra_t46_070` float DEFAULT NULL,
  `extra_t46_071` tinyblob,
  `extra_t46_072` bit(14) DEFAULT NULL,
  `extra_t46_073` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_074` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_075` json DEFAULT NULL,
  `extra_t46_076` enum('e6_1','e6_2','e6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_077` decimal(8,2) DEFAULT NULL,
  `extra_t46_078` mediumblob,
  `extra_t46_079` set('s9_1','s9_2','s9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_080` varbinary(12) DEFAULT NULL,
  `extra_t46_081` int unsigned DEFAULT NULL,
  `extra_t46_082` json DEFAULT NULL,
  `extra_t46_083` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_084` int unsigned DEFAULT NULL,
  `extra_t46_085` smallint DEFAULT NULL,
  `extra_t46_086` mediumblob,
  `extra_t46_087` json DEFAULT NULL,
  `extra_t46_088` decimal(15,7) DEFAULT NULL,
  `extra_t46_089` time(1) DEFAULT NULL,
  `extra_t46_090` decimal(15,6) DEFAULT NULL,
  `extra_t46_091` json DEFAULT NULL,
  `extra_t46_092` enum('e2_1','e2_2','e2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_093` timestamp(4) DEFAULT NULL,
  `extra_t46_094` bit(2) DEFAULT NULL,
  `extra_t46_095` timestamp(4) DEFAULT NULL,
  `extra_t46_096` datetime(6) DEFAULT NULL,
  `extra_t46_097` year DEFAULT NULL,
  `extra_t46_098` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_099` bit(29) DEFAULT NULL,
  `extra_t46_100` set('s0_1','s0_2','s0_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_101` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_102` bit(18) DEFAULT NULL,
  `extra_t46_103` double unsigned DEFAULT NULL,
  `extra_t46_104` json DEFAULT NULL,
  `extra_t46_105` bigint unsigned DEFAULT NULL,
  `extra_t46_106` year DEFAULT NULL,
  `extra_t46_107` varbinary(3) DEFAULT NULL,
  `extra_t46_108` double unsigned DEFAULT NULL,
  `extra_t46_109` decimal(7,2) DEFAULT NULL,
  `extra_t46_110` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_111` float DEFAULT NULL,
  `extra_t46_112` set('s2_1','s2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_113` json DEFAULT NULL,
  `extra_t46_114` json DEFAULT NULL,
  `extra_t46_115` double DEFAULT NULL,
  `extra_t46_116` longblob,
  `extra_t46_117` mediumblob,
  `extra_t46_118` binary(30) DEFAULT NULL,
  `extra_t46_119` double DEFAULT NULL,
  `extra_t46_120` time DEFAULT NULL,
  `extra_t46_121` set('s1_1','s1_2','s1_3','s1_4','s1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_122` bigint DEFAULT NULL,
  `extra_t46_123` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_124` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_125` time DEFAULT NULL,
  `extra_t46_126` datetime(3) DEFAULT NULL,
  `extra_t46_127` int DEFAULT NULL,
  `extra_t46_128` double DEFAULT NULL,
  `extra_t46_129` set('s9_1','s9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_130` mediumint unsigned DEFAULT NULL,
  `extra_t46_131` json DEFAULT NULL,
  `extra_t46_132` year DEFAULT NULL,
  `extra_t46_133` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_134` json DEFAULT NULL,
  `extra_t46_135` mediumblob,
  `extra_t46_136` json DEFAULT NULL,
  `extra_t46_137` datetime(5) DEFAULT NULL,
  `extra_t46_138` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_139` tinyint unsigned DEFAULT NULL,
  `extra_t46_140` bit(22) DEFAULT NULL,
  `extra_t46_141` enum('e1_1','e1_2','e1_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_142` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_143` json DEFAULT NULL,
  `extra_t46_144` varbinary(10) DEFAULT NULL,
  `extra_t46_145` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t46_146` double unsigned DEFAULT NULL,
  `extra_t46_147` date DEFAULT NULL,
  `extra_t46_148` year DEFAULT NULL,
  `extra_t46_149` json DEFAULT NULL,
  `extra_t46_150` bit(61) DEFAULT NULL,
  `extra_t46_151` decimal(8,4) DEFAULT NULL,
  `extra_t46_152` decimal(21,4) DEFAULT NULL,
  `extra_t46_153` double DEFAULT NULL,
  `extra_t46_154` blob,
  `extra_t46_155` bit(23) DEFAULT NULL,
  `extra_t46_156` set('s6_1','s6_2','s6_3','s6_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_157` enum('e7_1','e7_2','e7_3','e7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_158` bigint DEFAULT NULL,
  `extra_t46_159` decimal(23,6) DEFAULT NULL,
  `extra_t46_160` enum('e0_1','e0_2','e0_3','e0_4','e0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_161` json DEFAULT NULL,
  `extra_t46_162` int DEFAULT NULL,
  `extra_t46_163` enum('e3_1','e3_2','e3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_164` json DEFAULT NULL,
  `extra_t46_165` enum('e5_1','e5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t46_166` json DEFAULT NULL,
  `extra_t46_167` blob,
  `extra_t46_168` longblob,
  `extra_t46_169` bit(18) DEFAULT NULL,
  `extra_t46_170` time(5) DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t46_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t46_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t46_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t46_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t46_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t46_int_col` (`int_col`),
  KEY `idx_t46_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t46_year_char` (`year_col`,`char_col`),
  KEY `idx_t46_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t46_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t46_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t46_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t46_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t46_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t46_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t46_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t46_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t46_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t46_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t46_year_func` ((year(`datetime_col`))),
  KEY `idx_t46_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t46_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t46_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t46_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t46_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t46_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t46_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t46_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t46_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t46_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t46_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t46_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t46_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t46_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t46_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t46_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t46_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t46_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t46_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t46_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t46_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t46_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t46_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t46_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t46_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t46_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t46_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t46_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t46_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t46_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t46_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t46_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t46_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t46_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t46_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t46_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t46_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t46_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t46_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t46_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t46_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY LIST COLUMNS (`tenant_id`)
SUBPARTITION BY LINEAR KEY (`subpart_id`) SUBPARTITIONS 8 (
  PARTITION p0 VALUES IN (1),
  PARTITION p1 VALUES IN (2),
  PARTITION p2 VALUES IN (3),
  PARTITION p3 VALUES IN (4),
  PARTITION p4 VALUES IN (5),
  PARTITION p5 VALUES IN (6),
  PARTITION p6 VALUES IN (7),
  PARTITION p7 VALUES IN (8)
);
SET FOREIGN_KEY_CHECKS=1;
