SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t49`;
CREATE TABLE `t49` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(94) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(22,5) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(5) DEFAULT NULL,
  `timestamp_col` timestamp NULL DEFAULT NULL,
  `time_col` time(2) DEFAULT NULL,
  `varchar_col` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(136) DEFAULT NULL,
  `varbinary_col` varbinary(86) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(34) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(24,7) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t49_000` bigint unsigned DEFAULT NULL,
  `extra_t49_001` json DEFAULT NULL,
  `extra_t49_002` bit(43) DEFAULT NULL,
  `extra_t49_003` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_004` tinyblob,
  `extra_t49_005` bit(24) DEFAULT NULL,
  `extra_t49_006` datetime(2) DEFAULT NULL,
  `extra_t49_007` bit(14) DEFAULT NULL,
  `extra_t49_008` enum('e8_1','e8_2','e8_3','e8_4','e8_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_009` bigint unsigned DEFAULT NULL,
  `extra_t49_010` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_011` bit(29) DEFAULT NULL,
  `extra_t49_012` decimal(22,6) DEFAULT NULL,
  `extra_t49_013` bit(60) DEFAULT NULL,
  `extra_t49_014` bigint DEFAULT NULL,
  `extra_t49_015` decimal(9,6) DEFAULT NULL,
  `extra_t49_016` int DEFAULT NULL,
  `extra_t49_017` datetime(1) DEFAULT NULL,
  `extra_t49_018` json DEFAULT NULL,
  `extra_t49_019` json DEFAULT NULL,
  `extra_t49_020` bit(4) DEFAULT NULL,
  `extra_t49_021` longblob,
  `extra_t49_022` bit(45) DEFAULT NULL,
  `extra_t49_023` json DEFAULT NULL,
  `extra_t49_024` year DEFAULT NULL,
  `extra_t49_025` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_026` decimal(13,5) DEFAULT NULL,
  `extra_t49_027` bit(62) DEFAULT NULL,
  `extra_t49_028` bit(32) DEFAULT NULL,
  `extra_t49_029` set('s9_1','s9_2','s9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_030` set('s0_1','s0_2','s0_3','s0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_031` double DEFAULT NULL,
  `extra_t49_032` json DEFAULT NULL,
  `extra_t49_033` bit(22) DEFAULT NULL,
  `extra_t49_034` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_035` varbinary(18) DEFAULT NULL,
  `extra_t49_036` year DEFAULT NULL,
  `extra_t49_037` int unsigned DEFAULT NULL,
  `extra_t49_038` decimal(21,5) DEFAULT NULL,
  `extra_t49_039` bit(21) DEFAULT NULL,
  `extra_t49_040` decimal(16,2) DEFAULT NULL,
  `extra_t49_041` set('s1_1','s1_2','s1_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_042` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_043` year DEFAULT NULL,
  `extra_t49_044` decimal(6,5) DEFAULT NULL,
  `extra_t49_045` float unsigned DEFAULT NULL,
  `extra_t49_046` binary(10) DEFAULT NULL,
  `extra_t49_047` set('s7_1','s7_2','s7_3','s7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_048` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_049` json DEFAULT NULL,
  `extra_t49_050` json DEFAULT NULL,
  `extra_t49_051` enum('e1_1','e1_2','e1_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_052` bigint unsigned DEFAULT NULL,
  `extra_t49_053` timestamp(4) DEFAULT NULL,
  `extra_t49_054` int unsigned DEFAULT NULL,
  `extra_t49_055` tinyint DEFAULT NULL,
  `extra_t49_056` timestamp(1) DEFAULT NULL,
  `extra_t49_057` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_058` enum('e8_1','e8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_059` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_060` float unsigned DEFAULT NULL,
  `extra_t49_061` double DEFAULT NULL,
  `extra_t49_062` json DEFAULT NULL,
  `extra_t49_063` json DEFAULT NULL,
  `extra_t49_064` float DEFAULT NULL,
  `extra_t49_065` set('s5_1','s5_2','s5_3','s5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_066` json DEFAULT NULL,
  `extra_t49_067` enum('e7_1','e7_2','e7_3','e7_4','e7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_068` mediumblob,
  `extra_t49_069` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_070` json DEFAULT NULL,
  `extra_t49_071` json DEFAULT NULL,
  `extra_t49_072` tinyblob,
  `extra_t49_073` varbinary(26) DEFAULT NULL,
  `extra_t49_074` date DEFAULT NULL,
  `extra_t49_075` json DEFAULT NULL,
  `extra_t49_076` enum('e6_1','e6_2','e6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_077` smallint unsigned DEFAULT NULL,
  `extra_t49_078` float DEFAULT NULL,
  `extra_t49_079` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_080` smallint unsigned DEFAULT NULL,
  `extra_t49_081` json DEFAULT NULL,
  `extra_t49_082` longblob,
  `extra_t49_083` timestamp(3) DEFAULT NULL,
  `extra_t49_084` decimal(15,5) DEFAULT NULL,
  `extra_t49_085` binary(6) DEFAULT NULL,
  `extra_t49_086` float DEFAULT NULL,
  `extra_t49_087` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_088` float DEFAULT NULL,
  `extra_t49_089` decimal(14,7) DEFAULT NULL,
  `extra_t49_090` bit(44) DEFAULT NULL,
  `extra_t49_091` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_092` json DEFAULT NULL,
  `extra_t49_093` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_094` bit(26) DEFAULT NULL,
  `extra_t49_095` json DEFAULT NULL,
  `extra_t49_096` timestamp(4) DEFAULT NULL,
  `extra_t49_097` bit(36) DEFAULT NULL,
  `extra_t49_098` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_099` bigint DEFAULT NULL,
  `extra_t49_100` time(3) DEFAULT NULL,
  `extra_t49_101` decimal(13,2) DEFAULT NULL,
  `extra_t49_102` enum('e2_1','e2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_103` json DEFAULT NULL,
  `extra_t49_104` int unsigned DEFAULT NULL,
  `extra_t49_105` json DEFAULT NULL,
  `extra_t49_106` bit(52) DEFAULT NULL,
  `extra_t49_107` int unsigned DEFAULT NULL,
  `extra_t49_108` bit(59) DEFAULT NULL,
  `extra_t49_109` decimal(15,7) DEFAULT NULL,
  `extra_t49_110` bit(39) DEFAULT NULL,
  `extra_t49_111` bit(15) DEFAULT NULL,
  `extra_t49_112` bit(44) DEFAULT NULL,
  `extra_t49_113` year DEFAULT NULL,
  `extra_t49_114` float unsigned DEFAULT NULL,
  `extra_t49_115` year DEFAULT NULL,
  `extra_t49_116` json DEFAULT NULL,
  `extra_t49_117` bit(19) DEFAULT NULL,
  `extra_t49_118` decimal(18,1) DEFAULT NULL,
  `extra_t49_119` bit(22) DEFAULT NULL,
  `extra_t49_120` json DEFAULT NULL,
  `extra_t49_121` bit(56) DEFAULT NULL,
  `extra_t49_122` varbinary(14) DEFAULT NULL,
  `extra_t49_123` bit(39) DEFAULT NULL,
  `extra_t49_124` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_125` decimal(15,2) DEFAULT NULL,
  `extra_t49_126` bit(62) DEFAULT NULL,
  `extra_t49_127` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_128` smallint unsigned DEFAULT NULL,
  `extra_t49_129` bit(14) DEFAULT NULL,
  `extra_t49_130` bit(57) DEFAULT NULL,
  `extra_t49_131` timestamp(3) DEFAULT NULL,
  `extra_t49_132` int unsigned DEFAULT NULL,
  `extra_t49_133` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_134` set('s4_1','s4_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_135` set('s5_1','s5_2','s5_3','s5_4','s5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_136` mediumblob,
  `extra_t49_137` smallint DEFAULT NULL,
  `extra_t49_138` bigint unsigned DEFAULT NULL,
  `extra_t49_139` date DEFAULT NULL,
  `extra_t49_140` decimal(6,0) DEFAULT NULL,
  `extra_t49_141` decimal(11,5) DEFAULT NULL,
  `extra_t49_142` enum('e2_1','e2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_143` mediumint unsigned DEFAULT NULL,
  `extra_t49_144` json DEFAULT NULL,
  `extra_t49_145` blob,
  `extra_t49_146` blob,
  `extra_t49_147` bigint DEFAULT NULL,
  `extra_t49_148` double DEFAULT NULL,
  `extra_t49_149` json DEFAULT NULL,
  `extra_t49_150` enum('e0_1','e0_2','e0_3','e0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_151` tinyblob,
  `extra_t49_152` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_153` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_154` json DEFAULT NULL,
  `extra_t49_155` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_156` enum('e6_1','e6_2','e6_3','e6_4','e6_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_157` mediumint DEFAULT NULL,
  `extra_t49_158` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_159` varbinary(1) DEFAULT NULL,
  `extra_t49_160` bit(9) DEFAULT NULL,
  `extra_t49_161` float DEFAULT NULL,
  `extra_t49_162` json DEFAULT NULL,
  `extra_t49_163` varbinary(16) DEFAULT NULL,
  `extra_t49_164` decimal(6,0) DEFAULT NULL,
  `extra_t49_165` bit(7) DEFAULT NULL,
  `extra_t49_166` double DEFAULT NULL,
  `extra_t49_167` int unsigned DEFAULT NULL,
  `extra_t49_168` binary(18) DEFAULT NULL,
  `extra_t49_169` json DEFAULT NULL,
  `extra_t49_170` bit(61) DEFAULT NULL,
  `extra_t49_171` mediumblob,
  `extra_t49_172` decimal(10,4) DEFAULT NULL,
  `extra_t49_173` decimal(25,7) DEFAULT NULL,
  `extra_t49_174` decimal(9,2) DEFAULT NULL,
  `extra_t49_175` bit(30) DEFAULT NULL,
  `extra_t49_176` longblob,
  `extra_t49_177` bit(61) DEFAULT NULL,
  `extra_t49_178` binary(6) DEFAULT NULL,
  `extra_t49_179` enum('e9_1','e9_2','e9_3','e9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_180` json DEFAULT NULL,
  `extra_t49_181` double unsigned DEFAULT NULL,
  `extra_t49_182` mediumint DEFAULT NULL,
  `extra_t49_183` decimal(18,5) DEFAULT NULL,
  `extra_t49_184` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_185` blob,
  `extra_t49_186` json DEFAULT NULL,
  `extra_t49_187` tinyint DEFAULT NULL,
  `extra_t49_188` json DEFAULT NULL,
  `extra_t49_189` double DEFAULT NULL,
  `extra_t49_190` set('s0_1','s0_2','s0_3','s0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t49_191` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t49_192` year DEFAULT NULL,
  `extra_t49_193` json DEFAULT NULL,
  `extra_t49_194` float unsigned DEFAULT NULL,
  `extra_t49_195` bit(24) DEFAULT NULL,
  `extra_t49_196` set('s6_1','s6_2','s6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t49_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t49_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t49_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t49_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t49_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t49_int_col` (`int_col`),
  KEY `idx_t49_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t49_year_char` (`year_col`,`char_col`),
  KEY `idx_t49_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t49_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t49_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t49_varchar_prefix` (`varchar_col`(4)),
  KEY `idx_t49_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t49_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t49_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t49_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t49_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t49_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t49_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t49_year_func` ((year(`datetime_col`))),
  KEY `idx_t49_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t49_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t49_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t49_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t49_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t49_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t49_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t49_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t49_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t49_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t49_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t49_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t49_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t49_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t49_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t49_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t49_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t49_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t49_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t49_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t49_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t49_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t49_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t49_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t49_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t49_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t49_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t49_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t49_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t49_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t49_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t49_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t49_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t49_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t49_extra_char_varchar` (`char_col`,`varchar_col`(4)),
  KEY `idx_t49_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t49_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t49_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t49_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t49_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t49_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY HASH (`tenant_id`)
SUBPARTITION BY LIST (`subpart_id`) (
  PARTITION p0 (
    SUBPARTITION p0sp0 VALUES IN (1),
    SUBPARTITION p0sp1 VALUES IN (2),
    SUBPARTITION p0sp2 VALUES IN (3),
    SUBPARTITION p0sp3 VALUES IN (4),
    SUBPARTITION p0sp4 VALUES IN (5),
    SUBPARTITION p0sp5 VALUES IN (6),
    SUBPARTITION p0sp6 VALUES IN (7),
    SUBPARTITION p0sp7 VALUES IN (8)
  ),
  PARTITION p1 (
    SUBPARTITION p1sp0 VALUES IN (1),
    SUBPARTITION p1sp1 VALUES IN (2),
    SUBPARTITION p1sp2 VALUES IN (3),
    SUBPARTITION p1sp3 VALUES IN (4),
    SUBPARTITION p1sp4 VALUES IN (5),
    SUBPARTITION p1sp5 VALUES IN (6),
    SUBPARTITION p1sp6 VALUES IN (7),
    SUBPARTITION p1sp7 VALUES IN (8)
  ),
  PARTITION p2 (
    SUBPARTITION p2sp0 VALUES IN (1),
    SUBPARTITION p2sp1 VALUES IN (2),
    SUBPARTITION p2sp2 VALUES IN (3),
    SUBPARTITION p2sp3 VALUES IN (4),
    SUBPARTITION p2sp4 VALUES IN (5),
    SUBPARTITION p2sp5 VALUES IN (6),
    SUBPARTITION p2sp6 VALUES IN (7),
    SUBPARTITION p2sp7 VALUES IN (8)
  ),
  PARTITION p3 (
    SUBPARTITION p3sp0 VALUES IN (1),
    SUBPARTITION p3sp1 VALUES IN (2),
    SUBPARTITION p3sp2 VALUES IN (3),
    SUBPARTITION p3sp3 VALUES IN (4),
    SUBPARTITION p3sp4 VALUES IN (5),
    SUBPARTITION p3sp5 VALUES IN (6),
    SUBPARTITION p3sp6 VALUES IN (7),
    SUBPARTITION p3sp7 VALUES IN (8)
  ),
  PARTITION p4 (
    SUBPARTITION p4sp0 VALUES IN (1),
    SUBPARTITION p4sp1 VALUES IN (2),
    SUBPARTITION p4sp2 VALUES IN (3),
    SUBPARTITION p4sp3 VALUES IN (4),
    SUBPARTITION p4sp4 VALUES IN (5),
    SUBPARTITION p4sp5 VALUES IN (6),
    SUBPARTITION p4sp6 VALUES IN (7),
    SUBPARTITION p4sp7 VALUES IN (8)
  ),
  PARTITION p5 (
    SUBPARTITION p5sp0 VALUES IN (1),
    SUBPARTITION p5sp1 VALUES IN (2),
    SUBPARTITION p5sp2 VALUES IN (3),
    SUBPARTITION p5sp3 VALUES IN (4),
    SUBPARTITION p5sp4 VALUES IN (5),
    SUBPARTITION p5sp5 VALUES IN (6),
    SUBPARTITION p5sp6 VALUES IN (7),
    SUBPARTITION p5sp7 VALUES IN (8)
  ),
  PARTITION p6 (
    SUBPARTITION p6sp0 VALUES IN (1),
    SUBPARTITION p6sp1 VALUES IN (2),
    SUBPARTITION p6sp2 VALUES IN (3),
    SUBPARTITION p6sp3 VALUES IN (4),
    SUBPARTITION p6sp4 VALUES IN (5),
    SUBPARTITION p6sp5 VALUES IN (6),
    SUBPARTITION p6sp6 VALUES IN (7),
    SUBPARTITION p6sp7 VALUES IN (8)
  ),
  PARTITION p7 (
    SUBPARTITION p7sp0 VALUES IN (1),
    SUBPARTITION p7sp1 VALUES IN (2),
    SUBPARTITION p7sp2 VALUES IN (3),
    SUBPARTITION p7sp3 VALUES IN (4),
    SUBPARTITION p7sp4 VALUES IN (5),
    SUBPARTITION p7sp5 VALUES IN (6),
    SUBPARTITION p7sp6 VALUES IN (7),
    SUBPARTITION p7sp7 VALUES IN (8)
  )
);
SET FOREIGN_KEY_CHECKS=1;
