SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TEMPORARY TABLE IF EXISTS `t5`;
CREATE TEMPORARY TABLE `t5` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(176) DEFAULT NULL,
  `tinyint_col` tinyint DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(27,9) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(3) DEFAULT NULL,
  `timestamp_col` timestamp(1) NULL DEFAULT NULL,
  `time_col` time(3) DEFAULT NULL,
  `varchar_col` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(201) DEFAULT NULL,
  `varbinary_col` varbinary(2) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(57) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(16,7) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t5_000` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_001` enum('e1_1','e1_2','e1_3','e1_4','e1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_002` bit(58) DEFAULT NULL,
  `extra_t5_003` bit(34) DEFAULT NULL,
  `extra_t5_004` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_005` time(2) DEFAULT NULL,
  `extra_t5_006` date DEFAULT NULL,
  `extra_t5_007` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_008` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_009` year DEFAULT NULL,
  `extra_t5_010` double unsigned DEFAULT NULL,
  `extra_t5_011` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_012` decimal(13,4) DEFAULT NULL,
  `extra_t5_013` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_014` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_015` tinyint unsigned DEFAULT NULL,
  `extra_t5_016` mediumint DEFAULT NULL,
  `extra_t5_017` json DEFAULT NULL,
  `extra_t5_018` date DEFAULT NULL,
  `extra_t5_019` json DEFAULT NULL,
  `extra_t5_020` double unsigned DEFAULT NULL,
  `extra_t5_021` timestamp(4) DEFAULT NULL,
  `extra_t5_022` int DEFAULT NULL,
  `extra_t5_023` decimal(12,0) DEFAULT NULL,
  `extra_t5_024` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_025` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_026` enum('e6_1','e6_2','e6_3','e6_4','e6_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_027` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_028` mediumint DEFAULT NULL,
  `extra_t5_029` tinyblob,
  `extra_t5_030` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_031` decimal(9,1) DEFAULT NULL,
  `extra_t5_032` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_033` decimal(22,6) DEFAULT NULL,
  `extra_t5_034` set('s4_1','s4_2','s4_3','s4_4','s4_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_035` time(5) DEFAULT NULL,
  `extra_t5_036` longblob,
  `extra_t5_037` datetime(4) DEFAULT NULL,
  `extra_t5_038` bigint unsigned DEFAULT NULL,
  `extra_t5_039` datetime(6) DEFAULT NULL,
  `extra_t5_040` mediumint unsigned DEFAULT NULL,
  `extra_t5_041` bit(23) DEFAULT NULL,
  `extra_t5_042` bit(63) DEFAULT NULL,
  `extra_t5_043` decimal(16,5) DEFAULT NULL,
  `extra_t5_044` tinyint DEFAULT NULL,
  `extra_t5_045` double DEFAULT NULL,
  `extra_t5_046` decimal(11,0) DEFAULT NULL,
  `extra_t5_047` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_048` time(5) DEFAULT NULL,
  `extra_t5_049` timestamp(4) DEFAULT NULL,
  `extra_t5_050` json DEFAULT NULL,
  `extra_t5_051` binary(2) DEFAULT NULL,
  `extra_t5_052` decimal(9,4) DEFAULT NULL,
  `extra_t5_053` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_054` tinyblob,
  `extra_t5_055` bit(33) DEFAULT NULL,
  `extra_t5_056` set('s6_1','s6_2','s6_3','s6_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_057` mediumblob,
  `extra_t5_058` json DEFAULT NULL,
  `extra_t5_059` decimal(18,3) DEFAULT NULL,
  `extra_t5_060` varbinary(26) DEFAULT NULL,
  `extra_t5_061` decimal(11,2) DEFAULT NULL,
  `extra_t5_062` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_063` float DEFAULT NULL,
  `extra_t5_064` decimal(12,5) DEFAULT NULL,
  `extra_t5_065` tinyblob,
  `extra_t5_066` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_067` set('s7_1','s7_2','s7_3','s7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_068` smallint unsigned DEFAULT NULL,
  `extra_t5_069` float DEFAULT NULL,
  `extra_t5_070` decimal(8,3) DEFAULT NULL,
  `extra_t5_071` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_072` set('s2_1','s2_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_073` decimal(13,7) DEFAULT NULL,
  `extra_t5_074` bit(22) DEFAULT NULL,
  `extra_t5_075` bit(3) DEFAULT NULL,
  `extra_t5_076` set('s6_1','s6_2','s6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_077` json DEFAULT NULL,
  `extra_t5_078` bigint DEFAULT NULL,
  `extra_t5_079` json DEFAULT NULL,
  `extra_t5_080` double DEFAULT NULL,
  `extra_t5_081` int unsigned DEFAULT NULL,
  `extra_t5_082` bit(16) DEFAULT NULL,
  `extra_t5_083` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_084` binary(20) DEFAULT NULL,
  `extra_t5_085` int unsigned DEFAULT NULL,
  `extra_t5_086` tinyint DEFAULT NULL,
  `extra_t5_087` bit(11) DEFAULT NULL,
  `extra_t5_088` bit(61) DEFAULT NULL,
  `extra_t5_089` int DEFAULT NULL,
  `extra_t5_090` decimal(12,2) DEFAULT NULL,
  `extra_t5_091` char(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_092` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_093` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_094` json DEFAULT NULL,
  `extra_t5_095` blob,
  `extra_t5_096` bit(23) DEFAULT NULL,
  `extra_t5_097` enum('e7_1','e7_2','e7_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_098` json DEFAULT NULL,
  `extra_t5_099` mediumint DEFAULT NULL,
  `extra_t5_100` float unsigned DEFAULT NULL,
  `extra_t5_101` float unsigned DEFAULT NULL,
  `extra_t5_102` decimal(16,5) DEFAULT NULL,
  `extra_t5_103` bit(45) DEFAULT NULL,
  `extra_t5_104` enum('e4_1','e4_2','e4_3','e4_4','e4_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_105` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_106` datetime(4) DEFAULT NULL,
  `extra_t5_107` enum('e7_1','e7_2','e7_3','e7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_108` decimal(9,7) DEFAULT NULL,
  `extra_t5_109` year DEFAULT NULL,
  `extra_t5_110` json DEFAULT NULL,
  `extra_t5_111` double unsigned DEFAULT NULL,
  `extra_t5_112` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_113` json DEFAULT NULL,
  `extra_t5_114` time(1) DEFAULT NULL,
  `extra_t5_115` set('s5_1','s5_2','s5_3','s5_4','s5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_116` datetime DEFAULT NULL,
  `extra_t5_117` longblob,
  `extra_t5_118` json DEFAULT NULL,
  `extra_t5_119` decimal(12,6) DEFAULT NULL,
  `extra_t5_120` set('s0_1','s0_2','s0_3','s0_4','s0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_121` mediumint unsigned DEFAULT NULL,
  `extra_t5_122` enum('e2_1','e2_2','e2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_123` set('s3_1','s3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_124` datetime(3) DEFAULT NULL,
  `extra_t5_125` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_126` bit(26) DEFAULT NULL,
  `extra_t5_127` smallint unsigned DEFAULT NULL,
  `extra_t5_128` tinyblob,
  `extra_t5_129` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_130` float unsigned DEFAULT NULL,
  `extra_t5_131` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_132` bit(19) DEFAULT NULL,
  `extra_t5_133` double unsigned DEFAULT NULL,
  `extra_t5_134` varbinary(14) DEFAULT NULL,
  `extra_t5_135` bit(6) DEFAULT NULL,
  `extra_t5_136` set('s6_1','s6_2','s6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_137` bit(53) DEFAULT NULL,
  `extra_t5_138` decimal(12,2) DEFAULT NULL,
  `extra_t5_139` json DEFAULT NULL,
  `extra_t5_140` year DEFAULT NULL,
  `extra_t5_141` blob,
  `extra_t5_142` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_143` mediumint DEFAULT NULL,
  `extra_t5_144` json DEFAULT NULL,
  `extra_t5_145` json DEFAULT NULL,
  `extra_t5_146` json DEFAULT NULL,
  `extra_t5_147` json DEFAULT NULL,
  `extra_t5_148` json DEFAULT NULL,
  `extra_t5_149` date DEFAULT NULL,
  `extra_t5_150` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_151` json DEFAULT NULL,
  `extra_t5_152` set('s2_1','s2_2','s2_3','s2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_153` decimal(10,1) DEFAULT NULL,
  `extra_t5_154` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_155` float unsigned DEFAULT NULL,
  `extra_t5_156` bit(64) DEFAULT NULL,
  `extra_t5_157` decimal(10,8) DEFAULT NULL,
  `extra_t5_158` bit(50) DEFAULT NULL,
  `extra_t5_159` year DEFAULT NULL,
  `extra_t5_160` bigint DEFAULT NULL,
  `extra_t5_161` enum('e1_1','e1_2','e1_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_162` float DEFAULT NULL,
  `extra_t5_163` decimal(19,6) DEFAULT NULL,
  `extra_t5_164` decimal(15,8) DEFAULT NULL,
  `extra_t5_165` bit(4) DEFAULT NULL,
  `extra_t5_166` decimal(18,1) DEFAULT NULL,
  `extra_t5_167` smallint DEFAULT NULL,
  `extra_t5_168` tinyint unsigned DEFAULT NULL,
  `extra_t5_169` bit(12) DEFAULT NULL,
  `extra_t5_170` decimal(16,5) DEFAULT NULL,
  `extra_t5_171` double DEFAULT NULL,
  `extra_t5_172` bit(39) DEFAULT NULL,
  `extra_t5_173` enum('e3_1','e3_2','e3_3','e3_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_174` set('s4_1','s4_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_175` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_176` double DEFAULT NULL,
  `extra_t5_177` bit(34) DEFAULT NULL,
  `extra_t5_178` json DEFAULT NULL,
  `extra_t5_179` enum('e9_1','e9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_180` bigint unsigned DEFAULT NULL,
  `extra_t5_181` float DEFAULT NULL,
  `extra_t5_182` bit(41) DEFAULT NULL,
  `extra_t5_183` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_184` decimal(20,2) DEFAULT NULL,
  `extra_t5_185` enum('e5_1','e5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_186` longblob,
  `extra_t5_187` decimal(6,1) DEFAULT NULL,
  `extra_t5_188` enum('e8_1','e8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_189` decimal(17,7) DEFAULT NULL,
  `extra_t5_190` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_191` bit(56) DEFAULT NULL,
  `extra_t5_192` json DEFAULT NULL,
  `extra_t5_193` double DEFAULT NULL,
  `extra_t5_194` bit(37) DEFAULT NULL,
  `extra_t5_195` json DEFAULT NULL,
  `extra_t5_196` tinyblob,
  `extra_t5_197` double unsigned DEFAULT NULL,
  `extra_t5_198` bigint DEFAULT NULL,
  `extra_t5_199` datetime DEFAULT NULL,
  `extra_t5_200` bit(4) DEFAULT NULL,
  `extra_t5_201` json DEFAULT NULL,
  `extra_t5_202` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_203` date DEFAULT NULL,
  `extra_t5_204` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_205` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_206` blob,
  `extra_t5_207` bigint DEFAULT NULL,
  `extra_t5_208` longblob,
  `extra_t5_209` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_210` float DEFAULT NULL,
  `extra_t5_211` bit(39) DEFAULT NULL,
  `extra_t5_212` tinyblob,
  `extra_t5_213` bigint DEFAULT NULL,
  `extra_t5_214` enum('e4_1','e4_2','e4_3','e4_4','e4_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_215` enum('e5_1','e5_2','e5_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_216` binary(6) DEFAULT NULL,
  `extra_t5_217` bit(45) DEFAULT NULL,
  `extra_t5_218` bit(58) DEFAULT NULL,
  `extra_t5_219` double unsigned DEFAULT NULL,
  `extra_t5_220` float unsigned DEFAULT NULL,
  `extra_t5_221` set('s1_1','s1_2','s1_3','s1_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_222` json DEFAULT NULL,
  `extra_t5_223` decimal(14,5) DEFAULT NULL,
  `extra_t5_224` decimal(17,4) DEFAULT NULL,
  `extra_t5_225` bit(61) DEFAULT NULL,
  `extra_t5_226` decimal(15,5) DEFAULT NULL,
  `extra_t5_227` double DEFAULT NULL,
  `extra_t5_228` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_229` enum('e9_1','e9_2','e9_3','e9_4','e9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_230` bit(64) DEFAULT NULL,
  `extra_t5_231` decimal(7,4) DEFAULT NULL,
  `extra_t5_232` decimal(16,7) DEFAULT NULL,
  `extra_t5_233` bit(35) DEFAULT NULL,
  `extra_t5_234` decimal(22,5) DEFAULT NULL,
  `extra_t5_235` year DEFAULT NULL,
  `extra_t5_236` set('s6_1','s6_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_237` tinyblob,
  `extra_t5_238` bigint unsigned DEFAULT NULL,
  `extra_t5_239` bit(52) DEFAULT NULL,
  `extra_t5_240` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_241` longblob,
  `extra_t5_242` datetime(1) DEFAULT NULL,
  `extra_t5_243` bit(38) DEFAULT NULL,
  `extra_t5_244` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_245` json DEFAULT NULL,
  `extra_t5_246` year DEFAULT NULL,
  `extra_t5_247` int unsigned DEFAULT NULL,
  `extra_t5_248` double DEFAULT NULL,
  `extra_t5_249` int DEFAULT NULL,
  `extra_t5_250` bit(43) DEFAULT NULL,
  `extra_t5_251` json DEFAULT NULL,
  `extra_t5_252` timestamp(1) DEFAULT NULL,
  `extra_t5_253` varbinary(25) DEFAULT NULL,
  `extra_t5_254` bit(46) DEFAULT NULL,
  `extra_t5_255` bit(40) DEFAULT NULL,
  `extra_t5_256` binary(11) DEFAULT NULL,
  `extra_t5_257` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_258` time(6) DEFAULT NULL,
  `extra_t5_259` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_260` enum('e0_1','e0_2','e0_3','e0_4','e0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_261` bit(57) DEFAULT NULL,
  `extra_t5_262` float unsigned DEFAULT NULL,
  `extra_t5_263` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_264` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_265` decimal(10,1) DEFAULT NULL,
  `extra_t5_266` double unsigned DEFAULT NULL,
  `extra_t5_267` set('s7_1','s7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_268` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t5_269` decimal(15,5) DEFAULT NULL,
  `extra_t5_270` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_271` tinyblob,
  `extra_t5_272` set('s2_1','s2_2','s2_3','s2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t5_273` json DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t5_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t5_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t5_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t5_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t5_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  UNIQUE KEY `idx_t5_int_col` (`int_col`),
  UNIQUE KEY `idx_t5_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t5_year_char` (`year_col`,`char_col`),
  UNIQUE KEY `idx_t5_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  UNIQUE KEY `idx_t5_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  UNIQUE KEY `idx_t5_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t5_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t5_binary_combo` (`binary_col`,`varbinary_col`),
  UNIQUE KEY `idx_t5_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  UNIQUE KEY `idx_t5_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t5_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  UNIQUE KEY `idx_t5_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t5_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t5_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t5_year_func` ((year(`datetime_col`))),
  UNIQUE KEY `idx_t5_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  UNIQUE KEY `idx_t5_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  UNIQUE KEY `idx_t5_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t5_extra_text_set` (`text_col`(12),`set_col`),
  UNIQUE KEY `idx_t5_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t5_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  UNIQUE KEY `idx_t5_extra_decimal_round` ((round(`decimal_col`,2))),
  UNIQUE KEY `idx_t5_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  UNIQUE KEY `idx_t5_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t5_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  UNIQUE KEY `idx_t5_extra_decimal_desc` (`decimal_col` DESC),
  UNIQUE KEY `idx_t5_extra_tenant_int` (`tenant_id`,`int_col`),
  UNIQUE KEY `idx_t5_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t5_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  UNIQUE KEY `idx_t5_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  UNIQUE KEY `idx_t5_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t5_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  UNIQUE KEY `idx_t5_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t5_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  UNIQUE KEY `idx_t5_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  UNIQUE KEY `idx_t5_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  UNIQUE KEY `idx_t5_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t5_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  UNIQUE KEY `idx_t5_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t5_extra_month_datetime` ((month(`datetime_col`))),
  UNIQUE KEY `idx_t5_extra_date_days` ((to_days(`date_col`))),
  UNIQUE KEY `idx_t5_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t5_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t5_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t5_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  UNIQUE KEY `idx_t5_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  UNIQUE KEY `idx_t5_extra_float_double_desc` (`float_col`,`double_col` DESC),
  UNIQUE KEY `idx_t5_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t5_extra_varbinary_binary` (`varbinary_col`(2),`binary_col`),
  UNIQUE KEY `idx_t5_extra_mediumblob` (`mediumblob_col`(16)),
  UNIQUE KEY `idx_t5_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t5_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t5_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  UNIQUE KEY `idx_t5_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t5_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t5_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
