SET FOREIGN_KEY_CHECKS=0;
DROP TEMPORARY TABLE IF EXISTS `t5`;
CREATE TEMPORARY TABLE `t5` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(4) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(25,5) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(6) DEFAULT NULL,
  `timestamp_col` timestamp NULL DEFAULT NULL,
  `time_col` time DEFAULT NULL,
  `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(1) DEFAULT NULL,
  `varbinary_col` varbinary(255) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(8) DEFAULT b'10011001',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(10,0) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `point_col` point NOT NULL SRID 4326,
  `vector_col` vector(4) COMMENT 'imci_vector_index=FAISS_HNSW_FLAT(metric=COSINE,max_degree=32,ef_construction=300)',
  `vector_aux_col` vector(8) COMMENT 'imci_vector_index=HNSW(metric=COSINE,max_degree=32,ef_construction=400)',
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t5_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t5_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  UNIQUE KEY `uk_t5_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t5_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t5_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t5_int_col` (`int_col`),
  KEY `idx_t5_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t5_year_char` (`year_col`,`char_col`),
  KEY `idx_t5_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t5_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t5_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t5_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t5_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t5_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t5_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t5_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t5_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t5_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t5_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t5_year_func` ((year(`datetime_col`))),
  KEY `idx_t5_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t5_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  FULLTEXT KEY `ft_t5_text_cols` (`tinytext_col`,`text_col`,`mediumtext_col`,`longtext_col`),
  SPATIAL KEY `sp_t5_point_col` (`point_col`),
  CONSTRAINT `fk_t5_parent_id` FOREIGN KEY (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`) REFERENCES `t1` (`tenant_id`,`subpart_id`,`id_col`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_t5_parent_metric` FOREIGN KEY (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`) REFERENCES `t1` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='COLUMNAR=1';
SET FOREIGN_KEY_CHECKS=1;
