SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t62`;
CREATE TABLE `t62` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(137) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(18,8) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime DEFAULT NULL,
  `timestamp_col` timestamp(1) NULL DEFAULT NULL,
  `time_col` time DEFAULT NULL,
  `varchar_col` varchar(215) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(219) DEFAULT NULL,
  `varbinary_col` varbinary(156) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(64) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(17,4) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t62_000` datetime(1) DEFAULT NULL,
  `extra_t62_001` varbinary(23) DEFAULT NULL,
  `extra_t62_002` json DEFAULT NULL,
  `extra_t62_003` json DEFAULT NULL,
  `extra_t62_004` decimal(13,7) DEFAULT NULL,
  `extra_t62_005` mediumblob,
  `extra_t62_006` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_007` int DEFAULT NULL,
  `extra_t62_008` bit(42) DEFAULT NULL,
  `extra_t62_009` json DEFAULT NULL,
  `extra_t62_010` date DEFAULT NULL,
  `extra_t62_011` varbinary(12) DEFAULT NULL,
  `extra_t62_012` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_013` decimal(24,6) DEFAULT NULL,
  `extra_t62_014` float DEFAULT NULL,
  `extra_t62_015` bit(44) DEFAULT NULL,
  `extra_t62_016` smallint unsigned DEFAULT NULL,
  `extra_t62_017` varbinary(1) DEFAULT NULL,
  `extra_t62_018` longblob,
  `extra_t62_019` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_020` enum('e0_1','e0_2','e0_3','e0_4','e0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_021` json DEFAULT NULL,
  `extra_t62_022` decimal(6,1) DEFAULT NULL,
  `extra_t62_023` float unsigned DEFAULT NULL,
  `extra_t62_024` time DEFAULT NULL,
  `extra_t62_025` json DEFAULT NULL,
  `extra_t62_026` enum('e6_1','e6_2','e6_3','e6_4','e6_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_027` date DEFAULT NULL,
  `extra_t62_028` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_029` bit(60) DEFAULT NULL,
  `extra_t62_030` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_031` float DEFAULT NULL,
  `extra_t62_032` json DEFAULT NULL,
  `extra_t62_033` mediumint unsigned DEFAULT NULL,
  `extra_t62_034` tinyblob,
  `extra_t62_035` decimal(11,1) DEFAULT NULL,
  `extra_t62_036` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_037` longblob,
  `extra_t62_038` date DEFAULT NULL,
  `extra_t62_039` bit(5) DEFAULT NULL,
  `extra_t62_040` smallint DEFAULT NULL,
  `extra_t62_041` time(3) DEFAULT NULL,
  `extra_t62_042` float unsigned DEFAULT NULL,
  `extra_t62_043` binary(17) DEFAULT NULL,
  `extra_t62_044` float unsigned DEFAULT NULL,
  `extra_t62_045` bigint unsigned DEFAULT NULL,
  `extra_t62_046` decimal(6,5) DEFAULT NULL,
  `extra_t62_047` timestamp DEFAULT NULL,
  `extra_t62_048` json DEFAULT NULL,
  `extra_t62_049` tinyblob,
  `extra_t62_050` timestamp(5) DEFAULT NULL,
  `extra_t62_051` date DEFAULT NULL,
  `extra_t62_052` date DEFAULT NULL,
  `extra_t62_053` float unsigned DEFAULT NULL,
  `extra_t62_054` bit(57) DEFAULT NULL,
  `extra_t62_055` decimal(13,3) DEFAULT NULL,
  `extra_t62_056` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_057` blob,
  `extra_t62_058` datetime DEFAULT NULL,
  `extra_t62_059` bit(35) DEFAULT NULL,
  `extra_t62_060` set('s0_1','s0_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_061` mediumint DEFAULT NULL,
  `extra_t62_062` float unsigned DEFAULT NULL,
  `extra_t62_063` tinyblob,
  `extra_t62_064` decimal(12,3) DEFAULT NULL,
  `extra_t62_065` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_066` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_067` bit(15) DEFAULT NULL,
  `extra_t62_068` smallint unsigned DEFAULT NULL,
  `extra_t62_069` datetime DEFAULT NULL,
  `extra_t62_070` json DEFAULT NULL,
  `extra_t62_071` smallint unsigned DEFAULT NULL,
  `extra_t62_072` time(2) DEFAULT NULL,
  `extra_t62_073` binary(21) DEFAULT NULL,
  `extra_t62_074` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_075` mediumint unsigned DEFAULT NULL,
  `extra_t62_076` time(5) DEFAULT NULL,
  `extra_t62_077` json DEFAULT NULL,
  `extra_t62_078` enum('e8_1','e8_2','e8_3','e8_4','e8_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_079` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_080` varbinary(20) DEFAULT NULL,
  `extra_t62_081` bigint unsigned DEFAULT NULL,
  `extra_t62_082` timestamp(2) DEFAULT NULL,
  `extra_t62_083` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_084` bit(51) DEFAULT NULL,
  `extra_t62_085` double unsigned DEFAULT NULL,
  `extra_t62_086` enum('e6_1','e6_2','e6_3','e6_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_087` binary(3) DEFAULT NULL,
  `extra_t62_088` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_089` date DEFAULT NULL,
  `extra_t62_090` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_091` tinyint DEFAULT NULL,
  `extra_t62_092` float unsigned DEFAULT NULL,
  `extra_t62_093` tinyblob,
  `extra_t62_094` tinyblob,
  `extra_t62_095` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_096` bigint DEFAULT NULL,
  `extra_t62_097` set('s7_1','s7_2','s7_3','s7_4','s7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_098` json DEFAULT NULL,
  `extra_t62_099` double unsigned DEFAULT NULL,
  `extra_t62_100` int DEFAULT NULL,
  `extra_t62_101` mediumint unsigned DEFAULT NULL,
  `extra_t62_102` bit(40) DEFAULT NULL,
  `extra_t62_103` json DEFAULT NULL,
  `extra_t62_104` bit(64) DEFAULT NULL,
  `extra_t62_105` float unsigned DEFAULT NULL,
  `extra_t62_106` bit(21) DEFAULT NULL,
  `extra_t62_107` date DEFAULT NULL,
  `extra_t62_108` double unsigned DEFAULT NULL,
  `extra_t62_109` decimal(18,5) DEFAULT NULL,
  `extra_t62_110` year DEFAULT NULL,
  `extra_t62_111` double DEFAULT NULL,
  `extra_t62_112` decimal(15,6) DEFAULT NULL,
  `extra_t62_113` varbinary(13) DEFAULT NULL,
  `extra_t62_114` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_115` decimal(14,8) DEFAULT NULL,
  `extra_t62_116` longblob,
  `extra_t62_117` bigint DEFAULT NULL,
  `extra_t62_118` float DEFAULT NULL,
  `extra_t62_119` bit(21) DEFAULT NULL,
  `extra_t62_120` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_121` datetime(2) DEFAULT NULL,
  `extra_t62_122` decimal(6,0) DEFAULT NULL,
  `extra_t62_123` time(6) DEFAULT NULL,
  `extra_t62_124` json DEFAULT NULL,
  `extra_t62_125` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_126` time(3) DEFAULT NULL,
  `extra_t62_127` datetime(4) DEFAULT NULL,
  `extra_t62_128` float DEFAULT NULL,
  `extra_t62_129` enum('e9_1','e9_2','e9_3','e9_4','e9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_130` float unsigned DEFAULT NULL,
  `extra_t62_131` json DEFAULT NULL,
  `extra_t62_132` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_133` float unsigned DEFAULT NULL,
  `extra_t62_134` longblob,
  `extra_t62_135` float DEFAULT NULL,
  `extra_t62_136` decimal(10,2) DEFAULT NULL,
  `extra_t62_137` char(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_138` date DEFAULT NULL,
  `extra_t62_139` decimal(15,6) DEFAULT NULL,
  `extra_t62_140` json DEFAULT NULL,
  `extra_t62_141` bit(20) DEFAULT NULL,
  `extra_t62_142` decimal(18,1) DEFAULT NULL,
  `extra_t62_143` enum('e3_1','e3_2','e3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_144` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_145` double DEFAULT NULL,
  `extra_t62_146` decimal(11,1) DEFAULT NULL,
  `extra_t62_147` enum('e7_1','e7_2','e7_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_148` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_149` json DEFAULT NULL,
  `extra_t62_150` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t62_151` blob,
  `extra_t62_152` decimal(18,4) DEFAULT NULL,
  `extra_t62_153` time(3) DEFAULT NULL,
  `extra_t62_154` set('s4_1','s4_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_155` time(3) DEFAULT NULL,
  `extra_t62_156` decimal(18,8) DEFAULT NULL,
  `extra_t62_157` double DEFAULT NULL,
  `extra_t62_158` enum('e8_1','e8_2','e8_3','e8_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_159` mediumblob,
  `extra_t62_160` time DEFAULT NULL,
  `extra_t62_161` float DEFAULT NULL,
  `extra_t62_162` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t62_163` tinyint unsigned DEFAULT NULL,
  `extra_t62_164` date DEFAULT NULL,
  `extra_t62_165` int DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t62_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t62_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t62_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t62_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t62_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t62_int_col` (`int_col`),
  KEY `idx_t62_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t62_year_char` (`year_col`,`char_col`),
  KEY `idx_t62_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t62_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t62_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t62_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t62_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t62_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t62_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t62_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t62_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t62_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t62_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t62_year_func` ((year(`datetime_col`))),
  KEY `idx_t62_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t62_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t62_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t62_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t62_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t62_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t62_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t62_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t62_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t62_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t62_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t62_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t62_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t62_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t62_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t62_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t62_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t62_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t62_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t62_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t62_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t62_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t62_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t62_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t62_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t62_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t62_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t62_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t62_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t62_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t62_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t62_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t62_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t62_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t62_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t62_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t62_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t62_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t62_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t62_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t62_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY LINEAR HASH (`tenant_id`)
SUBPARTITION BY LINEAR KEY (`subpart_id`) SUBPARTITIONS 8 (
  PARTITION p0,
  PARTITION p1,
  PARTITION p2,
  PARTITION p3,
  PARTITION p4,
  PARTITION p5,
  PARTITION p6,
  PARTITION p7
);
SET FOREIGN_KEY_CHECKS=1;
