SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t8`;
CREATE TABLE `t8` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(229) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint unsigned DEFAULT NULL,
  `decimal_col` decimal(19,6) unsigned DEFAULT NULL,
  `float_col` float unsigned DEFAULT NULL,
  `double_col` double unsigned DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(1) DEFAULT NULL,
  `timestamp_col` timestamp(3) NULL DEFAULT NULL,
  `time_col` time(3) DEFAULT NULL,
  `varchar_col` varchar(168) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(134) DEFAULT NULL,
  `varbinary_col` varbinary(27) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(57) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(12,2) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t8_000` decimal(21,8) DEFAULT NULL,
  `extra_t8_001` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_002` decimal(15,0) DEFAULT NULL,
  `extra_t8_003` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_004` json DEFAULT NULL,
  `extra_t8_005` mediumint DEFAULT NULL,
  `extra_t8_006` longblob,
  `extra_t8_007` char(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_008` enum('e8_1','e8_2','e8_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_009` bit(56) DEFAULT NULL,
  `extra_t8_010` enum('e0_1','e0_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_011` decimal(19,6) DEFAULT NULL,
  `extra_t8_012` bit(33) DEFAULT NULL,
  `extra_t8_013` enum('e3_1','e3_2','e3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_014` json DEFAULT NULL,
  `extra_t8_015` timestamp(5) DEFAULT NULL,
  `extra_t8_016` decimal(12,0) DEFAULT NULL,
  `extra_t8_017` bit(38) DEFAULT NULL,
  `extra_t8_018` double DEFAULT NULL,
  `extra_t8_019` float DEFAULT NULL,
  `extra_t8_020` bit(54) DEFAULT NULL,
  `extra_t8_021` double unsigned DEFAULT NULL,
  `extra_t8_022` date DEFAULT NULL,
  `extra_t8_023` enum('e3_1','e3_2','e3_3','e3_4','e3_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_024` smallint unsigned DEFAULT NULL,
  `extra_t8_025` decimal(22,5) DEFAULT NULL,
  `extra_t8_026` double DEFAULT NULL,
  `extra_t8_027` int unsigned DEFAULT NULL,
  `extra_t8_028` json DEFAULT NULL,
  `extra_t8_029` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_030` smallint unsigned DEFAULT NULL,
  `extra_t8_031` varchar(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_032` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_033` tinyint DEFAULT NULL,
  `extra_t8_034` time(1) DEFAULT NULL,
  `extra_t8_035` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_036` json DEFAULT NULL,
  `extra_t8_037` set('s7_1','s7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_038` longblob,
  `extra_t8_039` set('s9_1','s9_2','s9_3','s9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_040` json DEFAULT NULL,
  `extra_t8_041` bit(40) DEFAULT NULL,
  `extra_t8_042` enum('e2_1','e2_2','e2_3','e2_4','e2_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_043` json DEFAULT NULL,
  `extra_t8_044` bit(56) DEFAULT NULL,
  `extra_t8_045` date DEFAULT NULL,
  `extra_t8_046` decimal(14,0) DEFAULT NULL,
  `extra_t8_047` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_048` tinyint unsigned DEFAULT NULL,
  `extra_t8_049` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_050` double DEFAULT NULL,
  `extra_t8_051` mediumint DEFAULT NULL,
  `extra_t8_052` bit(23) DEFAULT NULL,
  `extra_t8_053` decimal(17,6) DEFAULT NULL,
  `extra_t8_054` json DEFAULT NULL,
  `extra_t8_055` float DEFAULT NULL,
  `extra_t8_056` bigint unsigned DEFAULT NULL,
  `extra_t8_057` float DEFAULT NULL,
  `extra_t8_058` timestamp(6) DEFAULT NULL,
  `extra_t8_059` decimal(15,2) DEFAULT NULL,
  `extra_t8_060` binary(29) DEFAULT NULL,
  `extra_t8_061` date DEFAULT NULL,
  `extra_t8_062` float unsigned DEFAULT NULL,
  `extra_t8_063` set('s3_1','s3_2','s3_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_064` mediumint DEFAULT NULL,
  `extra_t8_065` datetime(1) DEFAULT NULL,
  `extra_t8_066` time(1) DEFAULT NULL,
  `extra_t8_067` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_068` set('s8_1','s8_2','s8_3','s8_4','s8_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_069` bit(8) DEFAULT NULL,
  `extra_t8_070` tinyblob,
  `extra_t8_071` smallint DEFAULT NULL,
  `extra_t8_072` bit(54) DEFAULT NULL,
  `extra_t8_073` bit(25) DEFAULT NULL,
  `extra_t8_074` decimal(13,6) DEFAULT NULL,
  `extra_t8_075` json DEFAULT NULL,
  `extra_t8_076` blob,
  `extra_t8_077` json DEFAULT NULL,
  `extra_t8_078` set('s8_1','s8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_079` bit(25) DEFAULT NULL,
  `extra_t8_080` bit(15) DEFAULT NULL,
  `extra_t8_081` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_082` varbinary(22) DEFAULT NULL,
  `extra_t8_083` binary(9) DEFAULT NULL,
  `extra_t8_084` bit(50) DEFAULT NULL,
  `extra_t8_085` set('s5_1','s5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_086` tinyint unsigned DEFAULT NULL,
  `extra_t8_087` set('s7_1','s7_2','s7_3','s7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_088` bigint unsigned DEFAULT NULL,
  `extra_t8_089` set('s9_1','s9_2','s9_3','s9_4','s9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_090` decimal(25,8) DEFAULT NULL,
  `extra_t8_091` double unsigned DEFAULT NULL,
  `extra_t8_092` json DEFAULT NULL,
  `extra_t8_093` double unsigned DEFAULT NULL,
  `extra_t8_094` decimal(17,3) DEFAULT NULL,
  `extra_t8_095` decimal(14,2) DEFAULT NULL,
  `extra_t8_096` time(4) DEFAULT NULL,
  `extra_t8_097` bigint DEFAULT NULL,
  `extra_t8_098` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_099` binary(5) DEFAULT NULL,
  `extra_t8_100` bit(52) DEFAULT NULL,
  `extra_t8_101` mediumblob,
  `extra_t8_102` enum('e2_1','e2_2','e2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_103` decimal(14,2) DEFAULT NULL,
  `extra_t8_104` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_105` float DEFAULT NULL,
  `extra_t8_106` json DEFAULT NULL,
  `extra_t8_107` float DEFAULT NULL,
  `extra_t8_108` set('s8_1','s8_2','s8_3','s8_4','s8_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_109` year DEFAULT NULL,
  `extra_t8_110` json DEFAULT NULL,
  `extra_t8_111` bit(9) DEFAULT NULL,
  `extra_t8_112` tinyint DEFAULT NULL,
  `extra_t8_113` float unsigned DEFAULT NULL,
  `extra_t8_114` time(6) DEFAULT NULL,
  `extra_t8_115` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_116` set('s6_1','s6_2','s6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_117` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_118` bit(28) DEFAULT NULL,
  `extra_t8_119` blob,
  `extra_t8_120` varbinary(19) DEFAULT NULL,
  `extra_t8_121` float unsigned DEFAULT NULL,
  `extra_t8_122` float unsigned DEFAULT NULL,
  `extra_t8_123` decimal(17,7) DEFAULT NULL,
  `extra_t8_124` year DEFAULT NULL,
  `extra_t8_125` bit(32) DEFAULT NULL,
  `extra_t8_126` json DEFAULT NULL,
  `extra_t8_127` enum('e7_1','e7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_128` double DEFAULT NULL,
  `extra_t8_129` decimal(9,0) DEFAULT NULL,
  `extra_t8_130` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_131` json DEFAULT NULL,
  `extra_t8_132` year DEFAULT NULL,
  `extra_t8_133` tinyblob,
  `extra_t8_134` bigint DEFAULT NULL,
  `extra_t8_135` float DEFAULT NULL,
  `extra_t8_136` decimal(19,5) DEFAULT NULL,
  `extra_t8_137` double DEFAULT NULL,
  `extra_t8_138` double unsigned DEFAULT NULL,
  `extra_t8_139` set('s9_1','s9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_140` datetime(5) DEFAULT NULL,
  `extra_t8_141` double DEFAULT NULL,
  `extra_t8_142` time(4) DEFAULT NULL,
  `extra_t8_143` double unsigned DEFAULT NULL,
  `extra_t8_144` date DEFAULT NULL,
  `extra_t8_145` enum('e5_1','e5_2','e5_3','e5_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_146` year DEFAULT NULL,
  `extra_t8_147` set('s7_1','s7_2','s7_3','s7_4','s7_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_148` blob,
  `extra_t8_149` enum('e9_1','e9_2','e9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_150` json DEFAULT NULL,
  `extra_t8_151` mediumblob,
  `extra_t8_152` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_153` mediumint unsigned DEFAULT NULL,
  `extra_t8_154` float DEFAULT NULL,
  `extra_t8_155` bit(17) DEFAULT NULL,
  `extra_t8_156` bit(18) DEFAULT NULL,
  `extra_t8_157` bit(64) DEFAULT NULL,
  `extra_t8_158` int unsigned DEFAULT NULL,
  `extra_t8_159` bit(54) DEFAULT NULL,
  `extra_t8_160` set('s0_1','s0_2','s0_3','s0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_161` bit(48) DEFAULT NULL,
  `extra_t8_162` float unsigned DEFAULT NULL,
  `extra_t8_163` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_164` int unsigned DEFAULT NULL,
  `extra_t8_165` bigint DEFAULT NULL,
  `extra_t8_166` bit(40) DEFAULT NULL,
  `extra_t8_167` double DEFAULT NULL,
  `extra_t8_168` tinyint unsigned DEFAULT NULL,
  `extra_t8_169` decimal(7,2) DEFAULT NULL,
  `extra_t8_170` tinyblob,
  `extra_t8_171` binary(11) DEFAULT NULL,
  `extra_t8_172` year DEFAULT NULL,
  `extra_t8_173` date DEFAULT NULL,
  `extra_t8_174` json DEFAULT NULL,
  `extra_t8_175` binary(10) DEFAULT NULL,
  `extra_t8_176` tinyint unsigned DEFAULT NULL,
  `extra_t8_177` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_178` double DEFAULT NULL,
  `extra_t8_179` double unsigned DEFAULT NULL,
  `extra_t8_180` bit(13) DEFAULT NULL,
  `extra_t8_181` bit(23) DEFAULT NULL,
  `extra_t8_182` year DEFAULT NULL,
  `extra_t8_183` date DEFAULT NULL,
  `extra_t8_184` tinyint DEFAULT NULL,
  `extra_t8_185` bit(59) DEFAULT NULL,
  `extra_t8_186` timestamp(3) DEFAULT NULL,
  `extra_t8_187` bigint DEFAULT NULL,
  `extra_t8_188` time DEFAULT NULL,
  `extra_t8_189` datetime(6) DEFAULT NULL,
  `extra_t8_190` decimal(22,6) DEFAULT NULL,
  `extra_t8_191` enum('e1_1','e1_2','e1_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_192` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_193` decimal(18,0) DEFAULT NULL,
  `extra_t8_194` double unsigned DEFAULT NULL,
  `extra_t8_195` enum('e5_1','e5_2','e5_3','e5_4','e5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_196` enum('e6_1','e6_2','e6_3','e6_4','e6_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_197` varbinary(18) DEFAULT NULL,
  `extra_t8_198` tinyblob,
  `extra_t8_199` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_200` json DEFAULT NULL,
  `extra_t8_201` decimal(17,1) DEFAULT NULL,
  `extra_t8_202` bit(36) DEFAULT NULL,
  `extra_t8_203` tinyblob,
  `extra_t8_204` json DEFAULT NULL,
  `extra_t8_205` json DEFAULT NULL,
  `extra_t8_206` tinyblob,
  `extra_t8_207` date DEFAULT NULL,
  `extra_t8_208` mediumint unsigned DEFAULT NULL,
  `extra_t8_209` date DEFAULT NULL,
  `extra_t8_210` float DEFAULT NULL,
  `extra_t8_211` json DEFAULT NULL,
  `extra_t8_212` datetime(2) DEFAULT NULL,
  `extra_t8_213` bigint unsigned DEFAULT NULL,
  `extra_t8_214` double DEFAULT NULL,
  `extra_t8_215` bit(49) DEFAULT NULL,
  `extra_t8_216` decimal(12,2) DEFAULT NULL,
  `extra_t8_217` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_218` double unsigned DEFAULT NULL,
  `extra_t8_219` enum('e9_1','e9_2','e9_3','e9_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_220` bit(64) DEFAULT NULL,
  `extra_t8_221` bigint unsigned DEFAULT NULL,
  `extra_t8_222` year DEFAULT NULL,
  `extra_t8_223` bit(27) DEFAULT NULL,
  `extra_t8_224` mediumblob,
  `extra_t8_225` json DEFAULT NULL,
  `extra_t8_226` bit(28) DEFAULT NULL,
  `extra_t8_227` mediumblob,
  `extra_t8_228` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_229` date DEFAULT NULL,
  `extra_t8_230` int DEFAULT NULL,
  `extra_t8_231` json DEFAULT NULL,
  `extra_t8_232` decimal(14,7) DEFAULT NULL,
  `extra_t8_233` json DEFAULT NULL,
  `extra_t8_234` tinyblob,
  `extra_t8_235` int unsigned DEFAULT NULL,
  `extra_t8_236` decimal(6,2) DEFAULT NULL,
  `extra_t8_237` int unsigned DEFAULT NULL,
  `extra_t8_238` date DEFAULT NULL,
  `extra_t8_239` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_240` time(6) DEFAULT NULL,
  `extra_t8_241` float unsigned DEFAULT NULL,
  `extra_t8_242` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t8_243` bit(54) DEFAULT NULL,
  `extra_t8_244` bit(60) DEFAULT NULL,
  `extra_t8_245` json DEFAULT NULL,
  `extra_t8_246` json DEFAULT NULL,
  `extra_t8_247` decimal(11,7) DEFAULT NULL,
  `extra_t8_248` decimal(15,7) DEFAULT NULL,
  `extra_t8_249` enum('e9_1','e9_2','e9_3','e9_4','e9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_250` tinyint unsigned DEFAULT NULL,
  `extra_t8_251` json DEFAULT NULL,
  `extra_t8_252` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_253` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_254` binary(1) DEFAULT NULL,
  `extra_t8_255` timestamp(5) DEFAULT NULL,
  `extra_t8_256` decimal(17,4) DEFAULT NULL,
  `extra_t8_257` int DEFAULT NULL,
  `extra_t8_258` decimal(6,3) DEFAULT NULL,
  `extra_t8_259` enum('e9_1','e9_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_260` timestamp DEFAULT NULL,
  `extra_t8_261` bit(60) DEFAULT NULL,
  `extra_t8_262` bit(45) DEFAULT NULL,
  `extra_t8_263` set('s3_1','s3_2','s3_3','s3_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_264` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_265` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t8_266` time(6) DEFAULT NULL,
  `extra_t8_267` decimal(13,7) DEFAULT NULL,
  `extra_t8_268` double DEFAULT NULL,
  `extra_t8_269` bigint unsigned DEFAULT NULL,
  `extra_t8_270` double unsigned DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t8_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t8_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t8_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t8_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t8_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t8_int_col` (`int_col`),
  KEY `idx_t8_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t8_year_char` (`year_col`,`char_col`),
  KEY `idx_t8_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t8_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t8_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t8_varchar_prefix` (`varchar_col`(64)),
  KEY `idx_t8_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t8_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t8_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t8_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t8_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t8_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t8_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t8_year_func` ((year(`datetime_col`))),
  KEY `idx_t8_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t8_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t8_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t8_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t8_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t8_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t8_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t8_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t8_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t8_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t8_extra_dayofweek` ((dayofweek(`date_col`))),
  UNIQUE KEY `idx_t8_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t8_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t8_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  UNIQUE KEY `idx_t8_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t8_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t8_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t8_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t8_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t8_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t8_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t8_extra_varbinary_binary` (`varbinary_col`(27),`binary_col`),
  KEY `idx_t8_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t8_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t8_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t8_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t8_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t8_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t8_extra_crc32_varchar` ((crc32(`varchar_col`))),
  UNIQUE KEY `idx_t8_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t8_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t8_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t8_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t8_extra_float_floor` ((floor(`float_col`))),
  KEY `idx_t8_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t8_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  KEY `idx_t8_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t8_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t8_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t8_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  KEY `idx_t8_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY RANGE COLUMNS (`tenant_id`) (
  PARTITION p0 VALUES LESS THAN (2),
  PARTITION p1 VALUES LESS THAN (3),
  PARTITION p2 VALUES LESS THAN (4),
  PARTITION p3 VALUES LESS THAN (5),
  PARTITION p4 VALUES LESS THAN (6),
  PARTITION p5 VALUES LESS THAN (7),
  PARTITION p6 VALUES LESS THAN (8),
  PARTITION p7 VALUES LESS THAN (MAXVALUE)
);
SET FOREIGN_KEY_CHECKS=1;
