SET transaction_isolation = 'READ-COMMITTED';
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `t9`;
CREATE TABLE `t9` (
  `id_col` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL DEFAULT 1,
  `subpart_id` int NOT NULL DEFAULT 1,
  `parent_id_col` int DEFAULT NULL,
  `parent_tenant_id` int DEFAULT NULL,
  `parent_subpart_id` int DEFAULT NULL,
  `metric_parent_tenant_id` int DEFAULT NULL,
  `metric_parent_subpart_id` int DEFAULT NULL,
  `parent_int_col` mediumint DEFAULT NULL,
  `parent_bigint_col` bigint DEFAULT NULL,
  `int_col` mediumint DEFAULT NULL,
  `bigint_col` bigint DEFAULT NULL,
  `year_col` year DEFAULT NULL,
  `char_col` char(201) DEFAULT NULL,
  `tinyint_col` tinyint unsigned DEFAULT NULL,
  `bool_col` tinyint(1) DEFAULT NULL,
  `smallint_col` smallint DEFAULT NULL,
  `mediumint_col` mediumint DEFAULT NULL,
  `decimal_col` decimal(11,1) unsigned DEFAULT NULL,
  `float_col` float DEFAULT NULL,
  `double_col` double DEFAULT NULL,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(2) DEFAULT NULL,
  `timestamp_col` timestamp(6) NULL DEFAULT NULL,
  `time_col` time(4) DEFAULT NULL,
  `varchar_col` varchar(39) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `binary_col` binary(232) DEFAULT NULL,
  `varbinary_col` varbinary(90) DEFAULT NULL,
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `bit_col` bit(55) DEFAULT b'1',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(16,5) unsigned DEFAULT NULL,
  `json_col` json DEFAULT NULL,
  `extra_t9_000` enum('e0_1','e0_2','e0_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_001` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_002` decimal(7,2) DEFAULT NULL,
  `extra_t9_003` int DEFAULT NULL,
  `extra_t9_004` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_005` json DEFAULT NULL,
  `extra_t9_006` json DEFAULT NULL,
  `extra_t9_007` json DEFAULT NULL,
  `extra_t9_008` decimal(24,6) DEFAULT NULL,
  `extra_t9_009` tinyint unsigned DEFAULT NULL,
  `extra_t9_010` year DEFAULT NULL,
  `extra_t9_011` decimal(21,3) DEFAULT NULL,
  `extra_t9_012` decimal(12,4) DEFAULT NULL,
  `extra_t9_013` timestamp(4) DEFAULT NULL,
  `extra_t9_014` double DEFAULT NULL,
  `extra_t9_015` decimal(16,7) DEFAULT NULL,
  `extra_t9_016` mediumblob,
  `extra_t9_017` float DEFAULT NULL,
  `extra_t9_018` json DEFAULT NULL,
  `extra_t9_019` decimal(7,1) DEFAULT NULL,
  `extra_t9_020` decimal(9,6) DEFAULT NULL,
  `extra_t9_021` year DEFAULT NULL,
  `extra_t9_022` tinyblob,
  `extra_t9_023` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_024` double DEFAULT NULL,
  `extra_t9_025` float DEFAULT NULL,
  `extra_t9_026` char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_027` double DEFAULT NULL,
  `extra_t9_028` varbinary(27) DEFAULT NULL,
  `extra_t9_029` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_030` mediumint DEFAULT NULL,
  `extra_t9_031` time(6) DEFAULT NULL,
  `extra_t9_032` json DEFAULT NULL,
  `extra_t9_033` decimal(7,0) DEFAULT NULL,
  `extra_t9_034` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_035` smallint DEFAULT NULL,
  `extra_t9_036` enum('e6_1','e6_2','e6_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_037` decimal(15,7) DEFAULT NULL,
  `extra_t9_038` enum('e8_1','e8_2','e8_3','e8_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_039` mediumblob,
  `extra_t9_040` double DEFAULT NULL,
  `extra_t9_041` enum('e1_1','e1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_042` year DEFAULT NULL,
  `extra_t9_043` json DEFAULT NULL,
  `extra_t9_044` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_045` tinyblob,
  `extra_t9_046` tinyint DEFAULT NULL,
  `extra_t9_047` binary(30) DEFAULT NULL,
  `extra_t9_048` double unsigned DEFAULT NULL,
  `extra_t9_049` bit(13) DEFAULT NULL,
  `extra_t9_050` json DEFAULT NULL,
  `extra_t9_051` double DEFAULT NULL,
  `extra_t9_052` json DEFAULT NULL,
  `extra_t9_053` decimal(9,3) DEFAULT NULL,
  `extra_t9_054` date DEFAULT NULL,
  `extra_t9_055` enum('e5_1','e5_2','e5_3','e5_4','e5_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_056` tinyint unsigned DEFAULT NULL,
  `extra_t9_057` double unsigned DEFAULT NULL,
  `extra_t9_058` binary(32) DEFAULT NULL,
  `extra_t9_059` double unsigned DEFAULT NULL,
  `extra_t9_060` year DEFAULT NULL,
  `extra_t9_061` bit(57) DEFAULT NULL,
  `extra_t9_062` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_063` mediumblob,
  `extra_t9_064` time(5) DEFAULT NULL,
  `extra_t9_065` float DEFAULT NULL,
  `extra_t9_066` int DEFAULT NULL,
  `extra_t9_067` bit(8) DEFAULT NULL,
  `extra_t9_068` bigint DEFAULT NULL,
  `extra_t9_069` enum('e9_1','e9_2','e9_3','e9_4','e9_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_070` year DEFAULT NULL,
  `extra_t9_071` year DEFAULT NULL,
  `extra_t9_072` double DEFAULT NULL,
  `extra_t9_073` json DEFAULT NULL,
  `extra_t9_074` enum('e4_1','e4_2','e4_3','e4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_075` enum('e5_1','e5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_076` year DEFAULT NULL,
  `extra_t9_077` float DEFAULT NULL,
  `extra_t9_078` smallint DEFAULT NULL,
  `extra_t9_079` double unsigned DEFAULT NULL,
  `extra_t9_080` enum('e0_1','e0_2','e0_3','e0_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_081` float DEFAULT NULL,
  `extra_t9_082` double unsigned DEFAULT NULL,
  `extra_t9_083` bit(45) DEFAULT NULL,
  `extra_t9_084` timestamp(2) DEFAULT NULL,
  `extra_t9_085` decimal(9,2) DEFAULT NULL,
  `extra_t9_086` json DEFAULT NULL,
  `extra_t9_087` enum('e7_1','e7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_088` bit(6) DEFAULT NULL,
  `extra_t9_089` tinyblob,
  `extra_t9_090` decimal(11,0) DEFAULT NULL,
  `extra_t9_091` set('s1_1','s1_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_092` float unsigned DEFAULT NULL,
  `extra_t9_093` bit(23) DEFAULT NULL,
  `extra_t9_094` time(2) DEFAULT NULL,
  `extra_t9_095` float DEFAULT NULL,
  `extra_t9_096` json DEFAULT NULL,
  `extra_t9_097` bit(14) DEFAULT NULL,
  `extra_t9_098` enum('e8_1','e8_2','e8_3','e8_4','e8_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_099` tinyint unsigned DEFAULT NULL,
  `extra_t9_100` decimal(14,3) DEFAULT NULL,
  `extra_t9_101` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_102` bit(1) DEFAULT NULL,
  `extra_t9_103` binary(25) DEFAULT NULL,
  `extra_t9_104` mediumblob,
  `extra_t9_105` bit(24) DEFAULT NULL,
  `extra_t9_106` mediumblob,
  `extra_t9_107` decimal(23,6) DEFAULT NULL,
  `extra_t9_108` varbinary(24) DEFAULT NULL,
  `extra_t9_109` float unsigned DEFAULT NULL,
  `extra_t9_110` bit(36) DEFAULT NULL,
  `extra_t9_111` json DEFAULT NULL,
  `extra_t9_112` decimal(18,0) DEFAULT NULL,
  `extra_t9_113` enum('e3_1','e3_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_114` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_115` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_116` tinyint unsigned DEFAULT NULL,
  `extra_t9_117` json DEFAULT NULL,
  `extra_t9_118` double unsigned DEFAULT NULL,
  `extra_t9_119` json DEFAULT NULL,
  `extra_t9_120` blob,
  `extra_t9_121` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_122` char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_123` bit(20) DEFAULT NULL,
  `extra_t9_124` bit(12) DEFAULT NULL,
  `extra_t9_125` enum('e5_1','e5_2','e5_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_126` timestamp(6) DEFAULT NULL,
  `extra_t9_127` bit(54) DEFAULT NULL,
  `extra_t9_128` int unsigned DEFAULT NULL,
  `extra_t9_129` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_130` decimal(21,3) DEFAULT NULL,
  `extra_t9_131` float unsigned DEFAULT NULL,
  `extra_t9_132` enum('e2_1','e2_2','e2_3','e2_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_133` bit(14) DEFAULT NULL,
  `extra_t9_134` time(6) DEFAULT NULL,
  `extra_t9_135` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_136` mediumblob,
  `extra_t9_137` float DEFAULT NULL,
  `extra_t9_138` enum('e8_1','e8_2','e8_3','e8_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_139` json DEFAULT NULL,
  `extra_t9_140` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_141` double DEFAULT NULL,
  `extra_t9_142` longblob,
  `extra_t9_143` tinyblob,
  `extra_t9_144` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_145` longblob,
  `extra_t9_146` mediumblob,
  `extra_t9_147` timestamp DEFAULT NULL,
  `extra_t9_148` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_149` json DEFAULT NULL,
  `extra_t9_150` bit(60) DEFAULT NULL,
  `extra_t9_151` tinyblob,
  `extra_t9_152` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_153` date DEFAULT NULL,
  `extra_t9_154` json DEFAULT NULL,
  `extra_t9_155` date DEFAULT NULL,
  `extra_t9_156` bit(61) DEFAULT NULL,
  `extra_t9_157` bit(62) DEFAULT NULL,
  `extra_t9_158` double DEFAULT NULL,
  `extra_t9_159` decimal(25,8) DEFAULT NULL,
  `extra_t9_160` int unsigned DEFAULT NULL,
  `extra_t9_161` enum('e1_1','e1_2','e1_3','e1_4','e1_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_162` set('s2_1','s2_2','s2_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_163` json DEFAULT NULL,
  `extra_t9_164` decimal(12,8) DEFAULT NULL,
  `extra_t9_165` decimal(20,7) DEFAULT NULL,
  `extra_t9_166` json DEFAULT NULL,
  `extra_t9_167` float DEFAULT NULL,
  `extra_t9_168` year DEFAULT NULL,
  `extra_t9_169` enum('e9_1','e9_2','e9_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_170` json DEFAULT NULL,
  `extra_t9_171` time(1) DEFAULT NULL,
  `extra_t9_172` time(4) DEFAULT NULL,
  `extra_t9_173` smallint DEFAULT NULL,
  `extra_t9_174` set('s4_1','s4_2','s4_3') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_175` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_176` json DEFAULT NULL,
  `extra_t9_177` json DEFAULT NULL,
  `extra_t9_178` bit(29) DEFAULT NULL,
  `extra_t9_179` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_180` decimal(22,8) DEFAULT NULL,
  `extra_t9_181` decimal(12,1) DEFAULT NULL,
  `extra_t9_182` json DEFAULT NULL,
  `extra_t9_183` tinyblob,
  `extra_t9_184` float unsigned DEFAULT NULL,
  `extra_t9_185` bigint unsigned DEFAULT NULL,
  `extra_t9_186` float DEFAULT NULL,
  `extra_t9_187` decimal(9,3) DEFAULT NULL,
  `extra_t9_188` bit(10) DEFAULT NULL,
  `extra_t9_189` bigint unsigned DEFAULT NULL,
  `extra_t9_190` bit(27) DEFAULT NULL,
  `extra_t9_191` varbinary(28) DEFAULT NULL,
  `extra_t9_192` bit(63) DEFAULT NULL,
  `extra_t9_193` bit(37) DEFAULT NULL,
  `extra_t9_194` set('s4_1','s4_2','s4_3','s4_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_195` set('s5_1','s5_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_196` timestamp(4) DEFAULT NULL,
  `extra_t9_197` set('s7_1','s7_2','s7_3','s7_4') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_198` json DEFAULT NULL,
  `extra_t9_199` double unsigned DEFAULT NULL,
  `extra_t9_200` bit(8) DEFAULT NULL,
  `extra_t9_201` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_202` mediumint unsigned DEFAULT NULL,
  `extra_t9_203` json DEFAULT NULL,
  `extra_t9_204` timestamp(1) DEFAULT NULL,
  `extra_t9_205` binary(10) DEFAULT NULL,
  `extra_t9_206` float DEFAULT NULL,
  `extra_t9_207` bit(43) DEFAULT NULL,
  `extra_t9_208` float DEFAULT NULL,
  `extra_t9_209` mediumblob,
  `extra_t9_210` bit(17) DEFAULT NULL,
  `extra_t9_211` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_212` decimal(20,2) DEFAULT NULL,
  `extra_t9_213` blob,
  `extra_t9_214` char(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_215` json DEFAULT NULL,
  `extra_t9_216` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `extra_t9_217` set('s7_1','s7_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_218` enum('e8_1','e8_2') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_219` mediumblob,
  `extra_t9_220` enum('e0_1','e0_2','e0_3','e0_4','e0_5') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `extra_t9_221` bigint unsigned DEFAULT NULL,
  `extra_t9_222` int unsigned DEFAULT NULL,
  `extra_t9_223` json DEFAULT NULL,
  `extra_t9_224` decimal(10,0) DEFAULT NULL,
  `extra_t9_225` date DEFAULT NULL,
  `extra_t9_226` bit(60) DEFAULT NULL,
  PRIMARY KEY (`id_col`,`tenant_id`,`subpart_id`),
  UNIQUE KEY `uk_t9_ref_id` (`tenant_id`,`subpart_id`,`id_col`),
  UNIQUE KEY `uk_t9_metric_ref` (`tenant_id`,`subpart_id`,`int_col`,`bigint_col`),
  KEY `idx_t9_char_scope` (`tenant_id`,`subpart_id`,`char_col`),
  KEY `idx_t9_parent_id` (`parent_tenant_id`,`parent_subpart_id`,`parent_id_col`),
  KEY `idx_t9_parent_metric` (`metric_parent_tenant_id`,`metric_parent_subpart_id`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t9_int_col` (`int_col`),
  KEY `idx_t9_bigint_desc` (`bigint_col` DESC),
  KEY `idx_t9_year_char` (`year_col`,`char_col`),
  KEY `idx_t9_tiny_small_medium` (`tinyint_col`,`smallint_col`,`mediumint_col`),
  KEY `idx_t9_decimal_float_double` (`decimal_col`,`float_col`,`double_col`),
  KEY `idx_t9_date_time_mix` (`date_col`,`datetime_col` DESC,`timestamp_col`,`time_col`),
  KEY `idx_t9_varchar_prefix` (`varchar_col`(39)),
  KEY `idx_t9_binary_combo` (`binary_col`,`varbinary_col`),
  KEY `idx_t9_blob_prefix` (`tinyblob_col`(16),`blob_col`(32),`mediumblob_col`(32),`longblob_col`(32)),
  KEY `idx_t9_text_prefix` (`tinytext_col`(16),`text_col`(16),`mediumtext_col`(16),`longtext_col`(16)),
  KEY `idx_t9_enum_set_bit` (`enum_col`,`set_col`,`bit_col`),
  KEY `idx_t9_unsigned_desc` (`unsigned_int_col` DESC,`unsigned_decimal_col`),
  KEY `idx_t9_bool_invisible` (`bool_col`) INVISIBLE,
  KEY `idx_t9_lower_varchar` ((lower(`varchar_col`))),
  KEY `idx_t9_year_func` ((year(`datetime_col`))),
  KEY `idx_t9_arith_expr` (((`unsigned_int_col` + `smallint_col`))),
  KEY `idx_t9_json_expr` ((cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32)))),
  KEY `idx_t9_extra_float_double_desc` (`float_col`,`double_col` DESC),
  KEY `idx_t9_extra_json_k_lower` ((lower(cast(json_unquote(json_extract(`json_col`,_utf8mb4'$.k')) as char(32))))),
  KEY `idx_t9_extra_small_medium_desc` (`smallint_col` DESC,`mediumint_col`),
  KEY `idx_t9_extra_char_varchar` (`char_col`,`varchar_col`(32)),
  KEY `idx_t9_extra_tinytext_enum` (`tinytext_col`(12),`enum_col`),
  KEY `idx_t9_extra_datetime_date_desc` (`datetime_col`,`date_col` DESC),
  KEY `idx_t9_extra_date_days` ((to_days(`date_col`))),
  KEY `idx_t9_extra_metric_parent_desc` (`metric_parent_tenant_id`,`parent_bigint_col` DESC),
  KEY `idx_t9_extra_decimal_desc` (`decimal_col` DESC),
  KEY `idx_t9_extra_varbinary_binary` (`varbinary_col`(32),`binary_col`),
  KEY `idx_t9_extra_unsigned_coalesce` ((coalesce(`unsigned_int_col`,0))),
  UNIQUE KEY `idx_t9_extra_tenant_year_date` (`tenant_id`,`year_col`,`date_col`),
  KEY `idx_t9_extra_set_unsigned` (`set_col`,`unsigned_int_col`),
  KEY `idx_t9_extra_enum_scope` (`enum_col`,`tenant_id`,`subpart_id`),
  KEY `idx_t9_extra_subpart_big` (`subpart_id`,`bigint_col`),
  KEY `idx_t9_extra_dayofweek` ((dayofweek(`date_col`))),
  KEY `idx_t9_extra_parent_chain` (`parent_id_col`,`parent_int_col`,`parent_bigint_col`),
  KEY `idx_t9_extra_mediumtext_bit` (`mediumtext_col`(12),`bit_col`),
  KEY `idx_t9_extra_time_to_sec` ((time_to_sec(`time_col`))),
  KEY `idx_t9_extra_longtext_unsigned` (`longtext_col`(12),`unsigned_int_col`),
  KEY `idx_t9_extra_json_n` ((cast(json_extract(`json_col`,_utf8mb4'$.n') as unsigned))),
  KEY `idx_t9_extra_timestamp_seconds` ((timestampdiff(second,`datetime_col`,`timestamp_col`))),
  UNIQUE KEY `idx_t9_extra_blob_tenant` (`blob_col`(16),`tenant_id`),
  KEY `idx_t9_extra_decimal_round` ((round(`decimal_col`,2))),
  KEY `idx_t9_extra_text_set` (`text_col`(12),`set_col`),
  KEY `idx_t9_extra_crc32_varchar` ((crc32(`varchar_col`))),
  KEY `idx_t9_extra_abs_smallint` ((abs(`smallint_col`))),
  KEY `idx_t9_extra_month_datetime` ((month(`datetime_col`))),
  KEY `idx_t9_extra_double_ceiling` ((ceiling(`double_col`))),
  KEY `idx_t9_extra_concat_code` ((cast(left(concat(`char_col`,`varchar_col`),32) as char(32)))),
  KEY `idx_t9_extra_tiny_bool` (`tinyint_col`,`bool_col`),
  KEY `idx_t9_extra_bit_decimal` (`bit_col`,`unsigned_decimal_col`),
  KEY `idx_t9_extra_longblob` (`longblob_col`(16)),
  KEY `idx_t9_extra_mediumblob` (`mediumblob_col`(16)),
  KEY `idx_t9_extra_time_timestamp` (`time_col`,`timestamp_col`),
  KEY `idx_t9_extra_float_floor` ((floor(`float_col`))),
  UNIQUE KEY `idx_t9_extra_tenant_int` (`tenant_id`,`int_col`),
  KEY `idx_t9_extra_tinyblob` (`tinyblob_col`(8)),
  KEY `idx_t9_extra_text_length` ((char_length(`text_col`)))
) ENGINE=InnoDB AUTO_INCREMENT=89671 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
PARTITION BY LIST (`tenant_id`) (
  PARTITION p0 VALUES IN (1),
  PARTITION p1 VALUES IN (2),
  PARTITION p2 VALUES IN (3),
  PARTITION p3 VALUES IN (4),
  PARTITION p4 VALUES IN (5),
  PARTITION p5 VALUES IN (6),
  PARTITION p6 VALUES IN (7),
  PARTITION p7 VALUES IN (8)
);
SET FOREIGN_KEY_CHECKS=1;
