"""Coverage-driven deterministic schema, data, and query generation."""

from select_fuzz.generation.catalog import EvidenceRef, FeatureCatalog, FeatureSpec
from select_fuzz.generation.coverage import CoverageLedger, CoverageScheduler
from select_fuzz.generation.function_registry import (
    DETERMINISTIC_FUNCTION_SIGNATURES,
    DeterministicFunctionSignature,
    FunctionArgument,
    FunctionFamily,
    FunctionResult,
)
from select_fuzz.generation.mutation import (
    MutationBatch,
    MutationBatchGenerator,
    MutationOperation,
    MutationStatement,
)
from select_fuzz.generation.query_contract import ExpectedError, ExpectedErrorKind, QueryLane
from select_fuzz.generation.query_grammar import (
    CandidateQuery,
    CandidateRejected,
    FunctionValueProfile,
    GrammarColumn,
    GrammarError,
    GrammarQueryConfig,
    GrammarQueryGenerator,
    GrammarSchema,
    GrammarTable,
    SelectGrammar,
    TypeFamily,
)
from select_fuzz.generation.query_safety import ReadOnlyValidator, UnsafeQuery
from select_fuzz.generation.query_scope import (
    DEFAULT_QUERY_SCOPE,
    QueryCoverageScope,
    QueryExclusionReason,
)
from select_fuzz.generation.schema import (
    ColumnDef,
    ForeignKeyDef,
    IndexDef,
    IndexExpression,
    IndexExpressionKind,
    IndexKind,
    IndexPart,
    PartitionDef,
    SchemaGenerator,
    SchemaLimits,
    SchemaManifest,
    SchemaProfile,
    SortDirection,
    TableDef,
)
from select_fuzz.generation.schema_rules import SchemaRuleViolation, SchemaRules

__all__ = [
    "CoverageLedger",
    "CoverageScheduler",
    "DEFAULT_QUERY_SCOPE",
    "DETERMINISTIC_FUNCTION_SIGNATURES",
    "ColumnDef",
    "CandidateQuery",
    "CandidateRejected",
    "EvidenceRef",
    "DeterministicFunctionSignature",
    "ExpectedError",
    "ExpectedErrorKind",
    "FeatureCatalog",
    "FeatureSpec",
    "FunctionValueProfile",
    "ForeignKeyDef",
    "FunctionArgument",
    "FunctionFamily",
    "FunctionResult",
    "IndexDef",
    "IndexExpression",
    "IndexExpressionKind",
    "IndexKind",
    "IndexPart",
    "MutationBatch",
    "MutationBatchGenerator",
    "MutationOperation",
    "MutationStatement",
    "PartitionDef",
    "GrammarColumn",
    "GrammarError",
    "GrammarQueryConfig",
    "GrammarQueryGenerator",
    "GrammarSchema",
    "GrammarTable",
    "QueryCoverageScope",
    "QueryExclusionReason",
    "QueryLane",
    "ReadOnlyValidator",
    "SchemaGenerator",
    "SchemaLimits",
    "SchemaManifest",
    "SchemaProfile",
    "SchemaRuleViolation",
    "SchemaRules",
    "SortDirection",
    "SelectGrammar",
    "TableDef",
    "UnsafeQuery",
    "TypeFamily",
]
