"""Coverage-driven deterministic schema, data, and query generation."""

from select_fuzz.generation.catalog import EvidenceRef, FeatureCatalog, FeatureSpec
from select_fuzz.generation.coverage import CoverageLedger, CoverageScheduler
from select_fuzz.generation.query import (
    EvidenceGateError,
    GeneratedQuery,
    QueryBatchPlanner,
    QueryBudget,
    QueryBudgetExceeded,
    QueryComplexity,
    QueryGenerator,
    QueryLane,
    QueryMix,
    SUPPORTED_VARIANT_IDS,
    TargetNotReachable,
    UnsupportedQueryFeature,
)
from select_fuzz.generation.query_ast import ExpectedError, ExpectedErrorKind, QueryAst
from select_fuzz.generation.query_safety import ReadOnlyValidator, UnsafeQuery
from select_fuzz.generation.schema import (
    ColumnDef,
    ForeignKeyDef,
    IndexDef,
    IndexExpression,
    IndexExpressionKind,
    IndexKind,
    IndexPart,
    PartitionDef,
    SchemaGenerator,
    SchemaLimits,
    SchemaManifest,
    SchemaProfile,
    SortDirection,
    TableDef,
)
from select_fuzz.generation.schema_rules import SchemaRuleViolation, SchemaRules

__all__ = [
    "CoverageLedger",
    "CoverageScheduler",
    "ColumnDef",
    "EvidenceGateError",
    "EvidenceRef",
    "ExpectedError",
    "ExpectedErrorKind",
    "FeatureCatalog",
    "FeatureSpec",
    "ForeignKeyDef",
    "IndexDef",
    "IndexExpression",
    "IndexExpressionKind",
    "IndexKind",
    "IndexPart",
    "PartitionDef",
    "GeneratedQuery",
    "QueryAst",
    "QueryBatchPlanner",
    "QueryBudget",
    "QueryBudgetExceeded",
    "QueryComplexity",
    "QueryGenerator",
    "QueryLane",
    "QueryMix",
    "ReadOnlyValidator",
    "SUPPORTED_VARIANT_IDS",
    "SchemaGenerator",
    "SchemaLimits",
    "SchemaManifest",
    "SchemaProfile",
    "SchemaRuleViolation",
    "SchemaRules",
    "SortDirection",
    "TableDef",
    "TargetNotReachable",
    "UnsafeQuery",
    "UnsupportedQueryFeature",
]
